import { createFileRoute } from "@tanstack/react-router";
import {
  Activity,
  AlertTriangle,
  Box,
  Building2,
  Cloud,
  Container as ContainerIcon,
  CreditCard,
  Database,
  GitBranch,
  GraduationCap,
  Heart,
  Landmark,
  Layers,
  LineChart,
  Lock,
  Network,
  Rocket,
  Server,
  ShieldCheck,
  ShoppingBag,
  Truck,
  Users,
  Wand2,
  Workflow,
  Zap,
} from "lucide-react";
import {
  ServiceDetailPage,
  buildServiceHead,
  type ServiceDetailContent,
} from "@/components/site/ServiceDetailPage";

const CONTENT: ServiceDetailContent = {
  slug: "cloud-solutions",
  path: "/technologies/cloud-solutions",
  brand: "tech",
  eyebrow: "Cloud solutions",
  title: "Cloud foundations engineered for reliability and cost.",
  subtitle:
    "AWS, Azure, and Google Cloud architecture, migration, and FinOps — built with infrastructure as code, observability, and security baked in.",
  metaTitle: "Cloud Solutions, Migration & DevOps — HIGAET Technologies",
  metaDescription:
    "Cloud architecture, migration, DevOps, and FinOps by HIGAET Technologies. AWS, Azure, and Google Cloud foundations engineered for reliability, security, and cost.",
  heroHighlights: [
    "Cloud landing zones built with Terraform and IaC",
    "Migration plans tied to measurable business outcomes",
    "Observability, SRE, and incident response from day one",
    "FinOps reviews that protect gross margin as you scale",
  ],
  overviewTitle: "Cloud as a foundation — not a recurring surprise.",
  overviewBody:
    "We design cloud platforms that engineering teams can trust and finance teams can predict. Engagements combine landing zones, security baselines, and CI/CD with the operational rituals — observability, incident response, FinOps reviews — that determine whether cloud is an asset or a tax.",
  benefits: [
    { title: "Predictable cloud spend", body: "FinOps reviews, right-sizing, and reservation planning protect gross margin as you grow." },
    { title: "Higher reliability", body: "SLO-driven design, multi-AZ topology, and tested recovery procedures keep customer trust intact." },
    { title: "Faster delivery", body: "Reusable IaC modules and golden CI/CD pipelines let product teams ship without re-inventing infra." },
    { title: "Stronger security posture", body: "Identity, secrets, encryption, and least-privilege defaults that pass enterprise security review." },
    { title: "Easier audits", body: "Policy as code, drift detection, and audit trails that simplify SOC 2, ISO 27001, and customer reviews." },
    { title: "Cloud portability", body: "Architectures designed around standards so you keep optionality across providers and regions." },
  ],
  features: [
    { icon: Cloud, title: "Cloud architecture", body: "Reference architectures for web, data, and AI workloads matched to your scale and budget." },
    { icon: Workflow, title: "Migration & modernization", body: "Lift-and-shift, re-platform, and re-architect plans grounded in real workload analysis." },
    { icon: Layers, title: "Landing zones", body: "Multi-account, multi-region foundations with IAM, networking, and guardrails as code." },
    { icon: ContainerIcon, title: "Containers & Kubernetes", body: "EKS, AKS, and GKE platforms with golden pipelines, autoscaling, and zero-downtime deploys." },
    { icon: Server, title: "Serverless & edge", body: "Lambda, Cloud Functions, Workers, and edge runtimes for low-latency, event-driven systems." },
    { icon: GitBranch, title: "DevOps & CI/CD", body: "Trunk-based delivery pipelines with code review, testing, security scans, and progressive rollout." },
    { icon: Activity, title: "Observability & SRE", body: "Logs, metrics, traces, SLOs, error budgets, and on-call rotations tied to clear runbooks." },
    { icon: ShieldCheck, title: "Cloud security", body: "Identity baselines, secrets management, network segmentation, and continuous compliance." },
    { icon: CreditCard, title: "FinOps", body: "Tagging, allocation, anomaly detection, and quarterly reviews that keep cloud spend defensible." },
  ],
  process: [
    { title: "Assess", body: "Inventory workloads, dependencies, and risks to size migration or modernization opportunity.", deliverables: ["Workload map", "Cost baseline"] },
    { title: "Design", body: "Reference architecture, landing zone blueprint, and security baseline matched to your constraints.", deliverables: ["Architecture", "ADRs"] },
    { title: "Build", body: "Implement IaC modules, CI/CD pipelines, and observability so platform teams can self-serve.", deliverables: ["IaC", "Pipelines"] },
    { title: "Migrate", body: "Phased migration with parallel runs, rollback plans, and clear cutover criteria.", deliverables: ["Migration waves", "Cutover plan"] },
    { title: "Operate", body: "Run platforms under SLOs, manage incidents, and improve continuously against KPIs.", deliverables: ["SLOs", "Runbooks"] },
    { title: "Optimize", body: "FinOps reviews, right-sizing, and architectural tuning to keep cost and performance in balance.", deliverables: ["FinOps report", "Tuning backlog"] },
  ],
  techGroups: [
    { title: "Cloud providers", items: ["AWS", "Azure", "Google Cloud", "Cloudflare", "Oracle Cloud"] },
    { title: "Infrastructure as code", items: ["Terraform", "Pulumi", "AWS CDK", "Crossplane", "Helm"] },
    { title: "Containers & orchestration", items: ["Docker", "Kubernetes", "EKS", "AKS", "GKE", "Argo"] },
    { title: "CI/CD", items: ["GitHub Actions", "GitLab CI", "Jenkins", "CircleCI", "Buildkite"] },
    { title: "Observability", items: ["Datadog", "Grafana", "Prometheus", "OpenTelemetry", "Sentry"] },
    { title: "Security & FinOps", items: ["Vault", "Snyk", "Wiz", "Cloudability", "OPA"] },
  ],
  industries: [
    { icon: GraduationCap, name: "Education", body: "Reliable platforms for learning, admissions, and assessment with predictable seasonal scale." },
    { icon: Heart, name: "Healthcare", body: "HIPAA-aware architectures, isolated data zones, and high-availability clinical platforms." },
    { icon: Landmark, name: "Finance & FinTech", body: "Regulated cloud platforms with strong isolation, audit, and disaster recovery posture." },
    { icon: ShoppingBag, name: "Retail & E-commerce", body: "Elastic platforms tuned for peak traffic, search, and order flows that can't go down." },
    { icon: Truck, name: "Logistics", body: "Event-driven platforms for telemetry, routing, and warehouse systems at industrial scale." },
    { icon: Building2, name: "Enterprise & SaaS", body: "Multi-tenant SaaS infrastructure and internal platforms for established enterprises." },
  ],
  whyUs: [
    { icon: Zap, title: "Pragmatic, not dogmatic", body: "We pick the simplest architecture that meets your SLOs — and avoid expensive complexity for its own sake." },
    { icon: Lock, title: "Security by default", body: "Identity baselines, least privilege, and policy as code on every account from week one." },
    { icon: LineChart, title: "FinOps discipline", body: "Tagging, allocation, and quarterly reviews keep cost defensible to finance and leadership." },
    { icon: AlertTriangle, title: "Incident-ready", body: "Runbooks, on-call rotations, and post-incident reviews that turn outages into permanent improvements." },
    { icon: Network, title: "Cloud-agnostic when it counts", body: "Open standards and portable IaC keep you out of provider corner cases that erode optionality." },
    { icon: Users, title: "Capability transfer", body: "We pair and document so your platform team owns the foundations after the engagement ends." },
  ],
  related: [
    { name: "Custom software development", href: "/technologies/custom-software-development", body: "The applications and platforms that run on the cloud foundations we design." },
    { name: "AI solutions", href: "/technologies/ai-solutions", body: "Inference infrastructure, data pipelines, and FinOps tuned for AI workloads." },
    { name: "SaaS product development", href: "/technologies/saas-products", body: "Multi-tenant SaaS platforms built on the cloud foundations described here." },
  ],
  faqs: [
    { q: "Which cloud provider should we choose?", a: "It depends on workload shape, regulatory constraints, existing skills, and pricing leverage. We help you decide with a workload analysis rather than a generic recommendation." },
    { q: "How do you approach migrations?", a: "Discovery and dependency mapping first, then a phased plan: lift-and-shift workloads that don't justify refactor, re-platform where small changes unlock value, re-architect critical workloads to take real advantage of cloud-native services." },
    { q: "Can you run our cloud platform after launch?", a: "Yes. We offer 24/7 SRE engagements with SLOs, on-call rotations, incident management, and quarterly reliability and FinOps reviews." },
    { q: "How do you control cloud cost?", a: "We tag and allocate spend, right-size compute, plan reservations and savings plans, detect anomalies, and run quarterly FinOps reviews with finance and engineering together." },
    { q: "Do you work with hybrid or on-prem footprints?", a: "Yes. Many engagements include hybrid architectures, private cloud integration, or on-prem-to-cloud migration paths. We design for the reality, not the marketing slide." },
    { q: "How do you handle compliance like SOC 2 or HIPAA?", a: "We implement policy as code, document control mappings, and stand up the audit trail and runbooks that auditors actually ask for — not just the technical controls." },
  ],
  ctaTitle: "Build cloud foundations engineering and finance can trust.",
  ctaBody: "Tell us your workloads, your goals, and your constraints. We'll come back with an architecture recommendation, a migration or modernization plan, and a credible delivery timeline.",
};

export const Route = createFileRoute("/technologies/cloud-solutions")({
  head: () => buildServiceHead(CONTENT),
  component: () => <ServiceDetailPage content={CONTENT} />,
});
