import { createFileRoute } from "@tanstack/react-router";
import {
  Boxes,
  Building2,
  Cloud,
  Code2,
  Cpu,
  Database,
  GitBranch,
  GraduationCap,
  Heart,
  Landmark,
  Layers,
  LineChart,
  Lock,
  Rocket,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  TestTube2,
  Truck,
  Users,
  Workflow,
  Zap,
} from "lucide-react";
import {
  ServiceDetailPage,
  buildServiceHead,
  type ServiceDetailContent,
} from "@/components/site/ServiceDetailPage";

const CONTENT: ServiceDetailContent = {
  slug: "custom-software-development",
  path: "/technologies/custom-software-development",
  brand: "tech",
  eyebrow: "Custom software development",
  title: "Custom software built to scale with the business.",
  subtitle:
    "Web, mobile, and platform engineering by senior squads who own architecture, delivery, and quality — not staffing churn.",
  metaTitle: "Custom Software Development Services — HIGAET Technologies",
  metaDescription:
    "Enterprise custom software development by HIGAET Technologies. Senior engineering squads, modern stack, measurable outcomes for web, mobile, and platform builds.",
  heroHighlights: [
    "Senior engineers, no staffing churn",
    "Architecture, delivery, and SRE under one team",
    "Predictable two-week delivery cadence",
    "Code, tests, and docs handed over from day one",
  ],
  overviewTitle: "Software engineering, treated as a long-term asset.",
  overviewBody:
    "We build durable software for organizations that depend on it — internal platforms, customer products, marketplaces, and enterprise tools. Engagements start with a clear architecture decision record, follow a predictable release rhythm, and finish with a system your team can run confidently.",
  benefits: [
    { title: "Faster time-to-value", body: "Cut months from your roadmap with senior squads who scope, design, and ship from week one." },
    { title: "Lower total cost of ownership", body: "Clean architecture, automated tests, and observability reduce the cost of every future change." },
    { title: "Reduced execution risk", body: "Iterative delivery, working demos, and architecture reviews catch problems early — not at launch." },
    { title: "Engineering visibility", body: "Sprint demos, KPI dashboards, and access to source mean stakeholders are never in the dark." },
    { title: "Talent on tap", body: "Scale a squad up or down without hiring cycles, severance, or institutional knowledge loss." },
    { title: "Production-grade quality", body: "Security, accessibility, and performance are designed in — not bolted on after the launch date." },
  ],
  features: [
    { icon: Code2, title: "Full-stack web platforms", body: "Modern React, Next.js, Node.js, and TypeScript stacks for portals, marketplaces, and internal tools." },
    { icon: Smartphone, title: "Mobile applications", body: "Native iOS and Android plus cross-platform React Native and Flutter, with shared design systems." },
    { icon: Layers, title: "Microservices & APIs", body: "REST, GraphQL, and event-driven architectures with API contracts your other teams can rely on." },
    { icon: Database, title: "Data & integrations", body: "Relational and document stores, ETL pipelines, and integrations with ERPs, CRMs, and identity providers." },
    { icon: Workflow, title: "Workflow automation", body: "Internal tools, approval flows, and BPM systems that take repetitive work off the operations team." },
    { icon: ShieldCheck, title: "Security & compliance", body: "Threat modelling, SAST/DAST in CI, secrets management, and SOC 2-aligned engineering controls." },
    { icon: TestTube2, title: "Quality engineering", body: "Unit, integration, contract, and end-to-end test suites — written alongside the feature, not after." },
    { icon: GitBranch, title: "DevOps & SRE", body: "Infrastructure as code, CI/CD, observability, runbooks, and on-call rotations for what we ship." },
    { icon: Sparkles, title: "AI-ready architecture", body: "Hooks for retrieval, agents, and evaluations so AI features can be added without re-platforming." },
  ],
  process: [
    { title: "Discover", body: "Workshops and technical audits to size the opportunity, surface risks, and align on KPIs.", deliverables: ["Goals & KPIs", "Architecture sketch", "Roadmap"] },
    { title: "Design", body: "UX flows, design system, and architecture decision records validated with stakeholders.", deliverables: ["Design system", "ADRs", "Prototype"] },
    { title: "Build", body: "Senior squads ship in two-week iterations with code review, automated testing, and demos.", deliverables: ["Working software", "Test suite", "CI/CD"] },
    { title: "Launch", body: "Hardening for performance, security, and accessibility, then go-live with monitoring in place.", deliverables: ["SLOs", "Runbooks", "Go-live plan"] },
    { title: "Operate", body: "24/7 SRE, incident response, and continuous improvement against the metrics that matter.", deliverables: ["Dashboards", "Quarterly reviews"] },
    { title: "Iterate", body: "Quarterly planning loops grounded in product analytics, customer interviews, and business goals.", deliverables: ["Backlog refresh", "Roadmap update"] },
  ],
  techGroups: [
    { title: "Frontend", items: ["React", "Next.js", "TypeScript", "Angular", "Vue", "Tailwind"] },
    { title: "Backend", items: ["Node.js", "Express", "NestJS", "Python", "Java", ".NET", "Go"] },
    { title: "Mobile", items: ["React Native", "Flutter", "Swift / iOS", "Kotlin / Android"] },
    { title: "Data", items: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch"] },
    { title: "Cloud", items: ["AWS", "Azure", "Google Cloud", "Cloudflare", "Vercel"] },
    { title: "DevOps & QA", items: ["Docker", "Kubernetes", "Terraform", "GitHub Actions", "Playwright"] },
  ],
  industries: [
    { icon: GraduationCap, name: "Education", body: "Learning platforms, admissions workflows, faculty tools, and student-facing portals." },
    { icon: Heart, name: "Healthcare", body: "Patient portals, clinical workflows, and decision support built around privacy and uptime." },
    { icon: Landmark, name: "Finance & FinTech", body: "Core banking, payments, KYC, risk, and embedded finance with strict security baselines." },
    { icon: ShoppingBag, name: "Retail & E-commerce", body: "Storefronts, marketplaces, fulfillment integrations, and AI personalization." },
    { icon: Truck, name: "Logistics", body: "Ops dashboards, IoT telemetry, route optimization, and warehouse automation." },
    { icon: Building2, name: "Enterprise & SaaS", body: "Internal platforms, partner portals, and multi-tenant SaaS products at scale." },
  ],
  whyUs: [
    { icon: Users, title: "Senior squads, low churn", body: "We staff with engineers trained through the HIGAET Academy talent pipeline — no rotating juniors." },
    { icon: Zap, title: "Product-minded delivery", body: "Squads obsess over user outcomes and KPIs, not just ticket throughput or hours billed." },
    { icon: Lock, title: "Enterprise governance", body: "NDAs, IP assignment, audit logs, and SOC 2-aligned controls on every engagement." },
    { icon: Layers, title: "Full-stack capability", body: "Strategy, design, engineering, AI, data, and SRE — one accountable team, not a chain of vendors." },
    { icon: Cpu, title: "AI in the DNA", body: "Every project considers where intelligent automation creates leverage for users and operators." },
    { icon: Rocket, title: "Skin in the game", body: "We co-build with select partners, sharing both delivery risk and long-term upside." },
  ],
  related: [
    { name: "AI solutions", href: "/technologies/ai-solutions", body: "Bring applied AI into the platforms we build — with evaluations, guardrails, and observability." },
    { name: "SaaS product development", href: "/technologies/saas-products", body: "Take a software idea to a scalable, monetizable, multi-tenant product." },
    { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud foundations, migrations, and FinOps tuned for the platforms we deliver." },
  ],
  faqs: [
    { q: "How quickly can you start a custom software project?", a: "Typically within 2–4 weeks. We confirm scope, sign agreements, and stage the right squad — usually a tech lead, two to four engineers, a designer, and a delivery lead." },
    { q: "Do we own the source code and IP?", a: "Yes. Source, infrastructure as code, documentation, and IP transfer to you under the master services agreement." },
    { q: "Can you augment our existing engineering team?", a: "Yes. We offer dedicated squads, embedded individual engineers, and hybrid models where our team owns specific services within your platform." },
    { q: "How do you ensure code quality?", a: "Every change goes through code review, automated testing, static analysis, and CI pipelines. We publish coverage and quality metrics with each release." },
    { q: "What's your typical engagement length?", a: "Most engagements run 6–18 months from MVP to operate. We support shorter discovery and prototype sprints when you need to validate an idea first." },
    { q: "How do you handle data protection and compliance?", a: "We follow least-privilege access, encrypted secrets, audit logging, and SOC 2-aligned controls. For regulated sectors we extend with HIPAA, PCI-DSS, or GDPR-specific work." },
  ],
  ctaTitle: "Engineer software you can grow on, with HIGAET.",
  ctaBody: "Tell us the problem you need solved. We'll come back with a squad, a scope, and a credible plan to ship.",
};

export const Route = createFileRoute("/technologies/custom-software-development")({
  head: () => buildServiceHead(CONTENT),
  component: () => <ServiceDetailPage content={CONTENT} />,
});
