/**
 * PR-body composer. Returns { title, body, labels } — no GitHub side effect.
 * Actual PR creation is delegated to a separate adapter (kept out of the
 * Worker runtime because Octokit is heavy and unnecessary here).
 */

import type { RootCauseReport } from "./root-cause";
import type { FixSuggestion } from "./fix-planner";

export interface PRSuggestion {
  title: string;
  body: string;
  labels: string[];
  branchHint: string;
  requiresHumanReview: true;
}

export interface PRSuggesterInput {
  issueTitle: string;
  issueShortId?: string;
  issuePermalink?: string;
  rootCause: RootCauseReport;
  fixPlan: FixSuggestion[];
}

export function suggestPR(input: PRSuggesterInput): PRSuggestion {
  const { issueTitle, issueShortId, issuePermalink, rootCause, fixPlan } = input;

  const shortId = issueShortId ?? "UNKNOWN";
  const title = `fix(sre): ${issueTitle}`.slice(0, 120);

  const causeLines = rootCause.hypotheses
    .map(
      (h, i) =>
        `${i + 1}. **${h.category}** — ${h.description} _(weight ${h.weight.toFixed(2)})_`,
    )
    .join("\n");

  const fixLines =
    fixPlan.length > 0
      ? fixPlan
          .map(
            (f) =>
              `- **[${f.risk}]** ${f.action}\n  - target: \`${f.targetHint}\`\n  - test: \`${f.testHint}\``,
          )
          .join("\n")
      : "_No matched playbook entry — human triage required._";

  const body = `## 🤖 AI SRE — proposed fix for ${shortId}

${issuePermalink ? `Sentry issue: ${issuePermalink}` : ""}

### Root-cause hypotheses (confidence ${(rootCause.confidence * 100).toFixed(0)}%)
${causeLines}
${rootCause.systemic ? "\n> ⚠️ Signals suggest a **systemic** regression, not an isolated bug.\n" : ""}
### Suggested changes
${fixLines}

### Boundary
- Generated by the AI SRE engine (advisory only).
- Requires **human review** before merge.
- No deploy or merge is triggered by this PR.
- Outcome is logged back to RIV for learning.
`;

  return {
    title,
    body,
    labels: ["ai-sre", `root-cause:${rootCause.topCategory}`, "needs-human-review"],
    branchHint: `sre/${shortId.toLowerCase()}-${rootCause.topCategory}`,
    requiresHumanReview: true,
  };
}
