/**
 * Create-or-reuse a GitHub PR for an AI SRE analysis.
 *
 * Idempotency (three layers, first-wins):
 *   1. In-DB row keyed on (issue_id, analysis_hash) — same analysis never
 *      opens a second PR.
 *   2. Branch name is deterministic (from PR draft), and GitHub rejects
 *      duplicate refs — we look up existing branch SHA first.
 *   3. openPullRequest() looks up an existing PR by head branch and reuses
 *      it instead of erroring.
 *
 * We never commit a code diff automatically. The commit is a single
 * advisory markdown file under `.sre/proposals/<issue>.md` containing the
 * analysis + fix plan. Any real code changes must be added by a human on
 * the same branch before merge — enforced socially by the
 * 'sre-review-required' label + PR body checklist.
 */
import type { AISREAnalysis } from "@/lib/sre/ai/orchestrator";
import type { PRDraft } from "./pr-draft";
import { computePRConfidence } from "./pr-confidence";
import {
  addLabels,
  commitFile,
  ensureBranch,
  getDefaultBranch,
  isGithubConfigured,
  openPullRequest,
} from "@/lib/github/client.server";

async function admin() {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return supabaseAdmin;
}

export interface CreatePRInput {
  issueId: string;
  analysisHash: string;
  analysis: AISREAnalysis;
  draft: PRDraft;
}

export type CreatePRResult =
  | { status: "created"; id: string; url: string; number: number; confidence: number }
  | { status: "reused"; id: string; url?: string; number?: number; confidence: number }
  | { status: "skipped"; reason: string }
  | { status: "failed"; reason: string };

function proposalMarkdown(input: CreatePRInput, confidence: number, review: boolean): string {
  const { draft, analysis, issueId } = input;
  const bullets = analysis.fixPlan
    .map((f, i) => `${i + 1}. **${f.action}** (${f.risk} risk)\n   - target: \`${f.targetHint}\`\n   - test: ${f.testHint}`)
    .join("\n");
  const hyps = analysis.rootCause.hypotheses
    .map((h) => `- [${h.category}] ${h.description} (weight ${h.weight.toFixed(2)})`)
    .join("\n");
  return `# AI SRE Proposal — ${draft.title}

**Sentry issue:** ${issueId}${draft.sentryPermalink ? ` — <${draft.sentryPermalink}>` : ""}
**Category:** ${draft.category}
**Confidence:** ${(confidence * 100).toFixed(1)}%
**Review required:** ${review ? "yes" : "no (still human-gated)"}

## Root cause hypotheses
${hyps || "_none produced_"}

## Fix plan
${bullets || "_none produced_"}

---

_This file was written automatically by the AI SRE pipeline. It is advisory only —
no code has been modified. A human reviewer must implement the changes on this
branch before merging._
`;
}

function prBody(input: CreatePRInput, confidence: number, review: boolean): string {
  const { draft } = input;
  const checklist = [
    "Root cause verified against Sentry event",
    "Fix implemented in a follow-up commit on this branch",
    "Tests added/updated to reproduce and cover the regression",
    "Rollback plan documented",
  ]
    .map((x) => `- [ ] ${x}`)
    .join("\n");
  return `${draft.body}

## PR confidence
- Score: **${(confidence * 100).toFixed(1)}%**
- Review required: **${review ? "yes" : "no"}**

## Reviewer checklist
${checklist}

_Generated by the AI SRE pipeline. The commit on this branch adds an advisory
proposal file under \`.sre/proposals/\` — no application code has been changed._
`;
}

export async function createPRForAnalysis(input: CreatePRInput): Promise<CreatePRResult> {
  if (!isGithubConfigured()) return { status: "skipped", reason: "github-not-configured" };

  const supa = await admin();
  const repo = process.env.GITHUB_REPO!;
  const confidence = computePRConfidence(input.analysis);

  // Idempotency guard — same issue + analysis hash never opens twice.
  const { data: existing } = await supa
    .from("sentry_pull_requests" as never)
    .select("id,pr_number,pr_url,pr_state")
    .eq("issue_id", input.issueId)
    .eq("analysis_hash", input.analysisHash)
    .maybeSingle();
  const existingRow = existing as
    | { id: string; pr_number: number | null; pr_url: string | null; pr_state: string }
    | null;
  if (existingRow) {
    return {
      status: "reused",
      id: existingRow.id,
      url: existingRow.pr_url ?? undefined,
      number: existingRow.pr_number ?? undefined,
      confidence: confidence.score,
    };
  }

  // Insert placeholder so a concurrent run collides on the unique index
  // and short-circuits above rather than opening a duplicate PR.
  const { data: placeholderRaw, error: insErr } = await supa
    .from("sentry_pull_requests" as never)
    .insert({
      issue_id: input.issueId,
      analysis_hash: input.analysisHash,
      branch_name: input.draft.branch,
      repo,
      title: input.draft.title,
      confidence_score: confidence.score,
      requires_human_review: confidence.requiresHumanReview,
      labels: [...new Set([...input.draft.labels, ...confidence.labels])],
      pr_state: "pending",
    } as never)
    .select("id")
    .single();
  if (insErr) {
    // 23505 = another worker beat us; re-read and return that row.
    if ((insErr as { code?: string }).code === "23505") {
      const { data: raced } = await supa
        .from("sentry_pull_requests" as never)
        .select("id,pr_number,pr_url")
        .eq("issue_id", input.issueId)
        .eq("analysis_hash", input.analysisHash)
        .maybeSingle();
      const r = raced as { id: string; pr_number: number | null; pr_url: string | null } | null;
      if (r) {
        return {
          status: "reused",
          id: r.id,
          url: r.pr_url ?? undefined,
          number: r.pr_number ?? undefined,
          confidence: confidence.score,
        };
      }
    }
    return { status: "failed", reason: `placeholder insert failed: ${insErr.message}` };
  }
  const rowId = (placeholderRaw as { id: string }).id;

  try {
    const base = await getDefaultBranch();
    await ensureBranch(input.draft.branch, base);
    const commitSha = await commitFile({
      branch: input.draft.branch,
      path: `.sre/proposals/${input.issueId}.md`,
      content: proposalMarkdown(input, confidence.score, confidence.requiresHumanReview),
      message: `chore(sre): proposal for Sentry issue ${input.issueId}`,
    });
    const labels = [...new Set([...input.draft.labels, ...confidence.labels])];
    const pr = await openPullRequest({
      head: input.draft.branch,
      base,
      title: input.draft.title,
      body: prBody(input, confidence.score, confidence.requiresHumanReview),
      draft: confidence.requiresHumanReview,
    });
    try {
      await addLabels(pr.number, labels);
    } catch {
      // Non-fatal: labels may not exist yet in the repo.
    }

    await supa
      .from("sentry_pull_requests" as never)
      .update({
        base_branch: base,
        pr_number: pr.number,
        pr_url: pr.url,
        pr_state: pr.state,
        commit_sha: commitSha,
        labels,
        body: prBody(input, confidence.score, confidence.requiresHumanReview),
        last_error: null,
      } as never)
      .eq("id", rowId);

    return {
      status: "created",
      id: rowId,
      url: pr.url,
      number: pr.number,
      confidence: confidence.score,
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    await supa
      .from("sentry_pull_requests" as never)
      .update({ pr_state: "failed", last_error: msg.slice(0, 1000) } as never)
      .eq("id", rowId);
    return { status: "failed", reason: msg };
  }
}
