import {
  Activity,
  BarChart3,
  Bot,
  Boxes,
  Brain,
  Building2,
  Cable,
  ClipboardCheck,
  Cpu,
  CreditCard,
  Database,
  GraduationCap,
  Heart,
  Hotel,
  Landmark,
  Layers,
  LineChart,
  Lock,
  Network,
  Package,
  PiggyBank,
  Plane,
  Plug,
  Repeat,
  Rocket,
  ScanSearch,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Store,
  Truck,
  Users,
  Warehouse,
  Workflow,
} from "lucide-react";
import type { IndustryDetailContent } from "@/components/site/IndustryDetailPage";

function make(input: Omit<IndustryDetailContent, "path">): IndustryDetailContent {
  return { path: `/technologies/industries/${input.slug}`, ...input };
}

const PROCESS_STANDARD: IndustryDetailContent["process"] = [
  { title: "Discover", body: "Sector-specific discovery, stakeholder interviews, and KPI alignment.", deliverables: ["Goals", "Roadmap"] },
  { title: "Design", body: "Service blueprints, UX flows, and architecture decision records.", deliverables: ["Blueprint", "ADRs"] },
  { title: "Build", body: "Senior squads ship in two-week sprints with code review and automated testing.", deliverables: ["Working software", "Test suite"] },
  { title: "Launch", body: "Hardening for security, performance, compliance, and accessibility, then go-live.", deliverables: ["SLOs", "Runbooks"] },
  { title: "Operate", body: "24/7 SRE, incident response, and continuous improvement against KPIs.", deliverables: ["Dashboards", "Quarterly reviews"] },
];

export const INDUSTRIES: Record<string, IndustryDetailContent> = {
  education: make({
    slug: "education",
    eyebrow: "Education",
    title: "Education technology that scales learning — and learning outcomes.",
    subtitle: "Learning platforms, admissions automation, faculty tools, and AI tutors for schools, universities, and EdTech ventures.",
    metaTitle: "Education Technology Solutions — HIGAET Technologies",
    metaDescription: "Custom EdTech software, AI tutors, learning platforms, and admissions automation for schools, universities, and EdTech ventures. By HIGAET Technologies.",
    heroHighlights: ["LMS, SIS, and CRM integrations", "AI tutors and copilots", "Admissions and enrollment automation", "Accessibility and data privacy by default"],
    overviewTitle: "Built by an institute that runs its own education programs.",
    overviewBody: "HIGAET Technologies builds learning platforms with the lived experience of HIGAET Academy and Global Education Hub. We understand learner journeys, faculty workflows, accreditation, and the operational reality of running programs at scale.",
    challenges: [
      { title: "Fragmented systems", body: "LMS, SIS, CRM, finance, and admissions all run in silos with brittle CSV exports between them." },
      { title: "Low learner engagement", body: "Generic content and rigid pacing produce dropouts and weak outcomes that hurt accreditation." },
      { title: "Manual admissions", body: "Application review, document chasing, and counselor follow-ups consume thousands of staff hours each cycle." },
      { title: "Faculty overload", body: "Grading, feedback, and content prep crowd out the high-value teaching time students actually pay for." },
      { title: "Compliance & privacy", body: "FERPA, GDPR, and accessibility standards add complexity that many EdTech tools ignore." },
      { title: "AI uncertainty", body: "Schools want to use AI responsibly but lack policies, evaluations, and safe platforms." },
    ],
    solutions: [
      { icon: GraduationCap, title: "Learning platforms", body: "Cohort-based, self-paced, and blended learning experiences with rich assessments and analytics." },
      { icon: Bot, title: "AI tutors & copilots", body: "Subject-grounded tutors with retrieval, guardrails, and evaluation loops — not generic chatbots." },
      { icon: Workflow, title: "Admissions automation", body: "Application pipelines, document verification, counselor CRM, and visa-tracking workflows." },
      { icon: Users, title: "Faculty productivity", body: "Grading assistants, content authoring, and analytics that buy back faculty time." },
      { icon: ShieldCheck, title: "Privacy & accessibility", body: "FERPA, GDPR, and WCAG 2.2 baked into the design — not retrofitted." },
      { icon: BarChart3, title: "Outcome analytics", body: "Learner cohorts, completion, employability, and accreditation reporting in one place." },
    ],
    recommendedServices: ["custom-software-development", "ai-solutions", "web-development", "mobile-development", "data-engineering", "ui-ux-design"],
    techGroups: [
      { title: "Platforms", items: ["LMS (Moodle, Open edX)", "SIS", "CRM", "LTI"] },
      { title: "AI", items: ["OpenAI", "LangChain", "Vector DBs", "Evals"] },
      { title: "Web & mobile", items: ["React", "Next.js", "React Native", "Flutter"] },
      { title: "Data", items: ["PostgreSQL", "Snowflake", "dbt", "Metabase"] },
    ],
    aiOpportunities: [
      { icon: Brain, title: "Adaptive tutoring", body: "AI tutors that personalize pacing, hints, and assessments based on learner mastery." },
      { icon: ClipboardCheck, title: "Auto-grading & feedback", body: "AI graders for essays and code with rubric-based feedback humans can validate." },
      { icon: ScanSearch, title: "Admissions intelligence", body: "Document parsing, lead scoring, and counselor copilots that lift conversion." },
      { icon: Sparkles, title: "Content generation", body: "Curriculum drafts, quizzes, and explainers generated and curated by faculty." },
      { icon: BarChart3, title: "Outcome prediction", body: "Early-warning models for at-risk learners with intervention playbooks." },
      { icon: Network, title: "Knowledge graphs", body: "Linked curricula, skills, and roles for personalized learning paths." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Higher completion rates", body: "Adaptive pacing and AI tutors lift completion and outcomes across cohorts." },
      { title: "Faster admissions", body: "Automated applications and verifications cut cycle times from weeks to days." },
      { title: "Faculty hours back", body: "AI grading and content tools reclaim 20–40% of low-leverage time." },
      { title: "Accreditation-ready data", body: "Outcome dashboards turn quarterly scrambles into routine reports." },
      { title: "Stronger learner UX", body: "Mobile-first, accessible experiences that meet modern learner expectations." },
      { title: "Privacy by default", body: "FERPA, GDPR, and SOC 2 controls support international growth." },
    ],
    caseStudies: [
      { title: "EdTech platform launch", outcome: "Cohort-based learning platform with AI tutors and admissions CRM.", placeholder: true },
      { title: "University admissions overhaul", outcome: "70% faster application processing across multiple intakes.", placeholder: true },
      { title: "K-12 grading copilot", outcome: "Faculty grading time reduced with AI assistance and audit logs.", placeholder: true },
    ],
    faqs: [
      { q: "Can you integrate with our LMS and SIS?", a: "Yes. We integrate with Moodle, Canvas, Open edX, Blackboard, and most SIS platforms via LTI, REST, and SCIM." },
      { q: "How do you handle student privacy?", a: "FERPA, GDPR, and country-specific rules drive architecture decisions. We isolate PII, encrypt at rest and in transit, and produce audit trails by default." },
      { q: "Can AI be used responsibly in a classroom?", a: "Yes — with retrieval-grounded answers, faculty-in-the-loop review, evaluations, and clear academic-integrity policies." },
      { q: "Do you support multilingual learners?", a: "Yes. Multilingual UX, localized content, and AI translation pipelines are routine for cross-border programs." },
    ],
    ctaTitle: "Build learning experiences that earn outcomes — with HIGAET.",
    ctaBody: "Tell us about your program, learner base, or platform pain. We'll propose a focused engagement.",
  }),

  healthcare: make({
    slug: "healthcare",
    eyebrow: "Healthcare",
    title: "Healthcare technology engineered for safety, uptime, and privacy.",
    subtitle: "Patient portals, clinical workflows, telehealth, and AI decision support for providers, payers, and HealthTech ventures.",
    metaTitle: "Healthcare Software Solutions — HIGAET Technologies",
    metaDescription: "HIPAA-aligned healthcare software, telehealth, AI decision support, and clinical workflows for providers and HealthTech. By HIGAET Technologies.",
    heroHighlights: ["HIPAA / GDPR-aligned by default", "FHIR, HL7, DICOM integrations", "Telehealth and remote monitoring", "Clinical AI with human-in-the-loop"],
    overviewTitle: "Software clinicians and patients can actually rely on.",
    overviewBody: "We build healthcare software that respects how clinicians work and how patients live. Engagements start with safety and privacy as architecture inputs, not afterthoughts, and end with systems that integrate cleanly across the care continuum.",
    challenges: [
      { title: "Legacy clinical systems", body: "Aging EHRs, paper workflows, and brittle integrations slow every initiative." },
      { title: "Patient experience gap", body: "Booking, results, and communication still feel like 2005 next to consumer apps." },
      { title: "Regulatory complexity", body: "HIPAA, GDPR, MDR, and ISO 13485 each add real, costly engineering constraints." },
      { title: "Clinician burnout", body: "Documentation and admin work eat the hours clinicians want for patients." },
      { title: "Data silos", body: "Clinical, claims, lab, and device data rarely combine to support real decisions." },
      { title: "AI safety", body: "Clinical AI must be explainable, audited, and grounded — or it's a liability." },
    ],
    solutions: [
      { icon: Stethoscope, title: "Patient & provider portals", body: "Self-service portals, scheduling, secure messaging, and care plan tracking." },
      { icon: Activity, title: "Telehealth & RPM", body: "Video, asynchronous care, and remote monitoring with consent and audit baked in." },
      { icon: Cable, title: "EHR & FHIR integration", body: "FHIR, HL7v2, DICOM, X12 — integrated through governed pipelines, not point-to-point hacks." },
      { icon: Brain, title: "Clinical AI", body: "Documentation copilots, decision support, and triage AI with human-in-the-loop." },
      { icon: ShieldCheck, title: "Privacy by design", body: "HIPAA, GDPR, and country-specific controls, plus audit logging for every access." },
      { icon: BarChart3, title: "Population health analytics", body: "Unified clinical, claims, and SDoH data for risk and care management." },
    ],
    recommendedServices: ["custom-software-development", "ai-solutions", "data-engineering", "system-integration", "cloud-solutions", "qa-testing"],
    techGroups: [
      { title: "Standards", items: ["FHIR", "HL7v2", "DICOM", "X12", "SNOMED"] },
      { title: "Cloud", items: ["AWS HealthLake", "Azure Health Data", "GCP Healthcare API"] },
      { title: "AI", items: ["OpenAI", "Medical LLMs", "MONAI", "MLflow"] },
      { title: "Apps", items: ["React", "React Native", "Flutter", ".NET", "Python"] },
    ],
    aiOpportunities: [
      { icon: ClipboardCheck, title: "Ambient documentation", body: "Scribe AI that drafts clinical notes for clinician review, reclaiming hours per day." },
      { icon: ScanSearch, title: "Triage & risk scoring", body: "Decision support for ED triage, sepsis risk, and readmission risk." },
      { icon: Sparkles, title: "Patient summarization", body: "AI summaries of charts, labs, and imaging for safer handoffs and faster reviews." },
      { icon: Bot, title: "Patient copilots", body: "Conversational interfaces for booking, prep, and post-visit follow-up." },
      { icon: BarChart3, title: "Population analytics", body: "Cohort discovery, care-gap detection, and prior-auth prediction." },
      { icon: Network, title: "Knowledge graphs", body: "Linked guidelines, drugs, and conditions for grounded clinical AI." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Clinician hours back", body: "AI scribes and workflow automation cut documentation by 30%+." },
      { title: "Safer care", body: "Decision support and traceable AI reduce missed signals." },
      { title: "Faster access", body: "Streamlined booking, intake, and triage shorten time-to-care." },
      { title: "Stronger compliance", body: "Audit trails and access controls satisfy regulators and payers." },
      { title: "Better patient experience", body: "Modern portals and apps lift CAHPS and NPS scores." },
      { title: "Operational efficiency", body: "Integrated data and automation cut admin overhead." },
    ],
    caseStudies: [
      { title: "Telehealth platform launch", outcome: "End-to-end virtual care with FHIR and payer integrations.", placeholder: true },
      { title: "AI clinical scribe", outcome: "Documentation time reduced for primary care clinicians.", placeholder: true },
      { title: "Population health portal", outcome: "Unified clinical and claims data for care management teams.", placeholder: true },
    ],
    faqs: [
      { q: "Are you HIPAA-aligned?", a: "Yes. Our engagement model, infrastructure, and engineering practices map to HIPAA technical safeguards, with BAAs in place." },
      { q: "Can you integrate with our EHR?", a: "Yes — FHIR, HL7v2, and legacy interfaces across Epic, Cerner, Allscripts, and most EHRs." },
      { q: "How do you handle AI safety?", a: "Retrieval grounding, human-in-the-loop, evaluations, audit trails, and explicit clinical-validation gates before AI features influence care." },
      { q: "Can you support medical-device software?", a: "We support SaMD programs under IEC 62304 and aligned QMS frameworks; full Class III work is typically partnered." },
    ],
    ctaTitle: "Build healthcare software clinicians trust — with HIGAET.",
    ctaBody: "Tell us about your population, workflows, and regulatory context. We'll respond with a tailored engagement.",
  }),

  finance: make({
    slug: "finance",
    eyebrow: "Finance",
    title: "Financial software for risk, performance, and regulatory reality.",
    subtitle: "Core finance, treasury, risk, and reporting platforms for asset managers, insurers, and CFO offices.",
    metaTitle: "Finance Industry Software Solutions — HIGAET Technologies",
    metaDescription: "Financial software for asset managers, insurers, and corporate finance: risk, reporting, performance, and AI. By HIGAET Technologies.",
    heroHighlights: ["Risk, reporting, performance", "Real-time data and streaming", "SOC 2, ISO 27001 aligned", "Quant-grade infrastructure"],
    overviewTitle: "Finance systems built like the markets they serve.",
    overviewBody: "We build platforms for finance teams who need numbers fast, accurate, and traceable. From quant-grade pipelines to CFO dashboards, we combine engineering depth with financial domain fluency.",
    challenges: [
      { title: "Data quality", body: "Reconciliations across multiple sources still consume analyst hours that should be spent on insight." },
      { title: "Regulatory reporting", body: "Basel, IFRS 17, SOX, MiFID, and local regimes each demand defensible, auditable processes." },
      { title: "Legacy core systems", body: "Aging cores limit product velocity, integration speed, and analytical agility." },
      { title: "Risk visibility", body: "Market, credit, and operational risk often live in slow batches instead of real-time dashboards." },
      { title: "Talent leverage", body: "Quant and finance teams burn time on infrastructure instead of models and analysis." },
      { title: "AI governance", body: "Model risk, explainability, and bias controls are now non-negotiable for finance AI." },
    ],
    solutions: [
      { icon: LineChart, title: "Risk & performance", body: "Real-time risk, exposure, attribution, and performance reporting for portfolios and books." },
      { icon: Database, title: "Data platforms", body: "Lakehouses with golden masters for instruments, counterparties, and positions." },
      { icon: Workflow, title: "Regulatory reporting", body: "Configurable engines for IFRS 17, Basel, SFDR, and other regulatory submissions." },
      { icon: Brain, title: "Quant & AI", body: "Feature stores, signal pipelines, and ML platforms for systematic strategies." },
      { icon: ShieldCheck, title: "Controls & audit", body: "Lineage, change management, and access controls that pass internal and external audits." },
      { icon: Sparkles, title: "CFO copilots", body: "Conversational interfaces over governed data for board packs and ad-hoc analysis." },
    ],
    recommendedServices: ["data-engineering", "business-intelligence", "ai-solutions", "custom-software-development", "cloud-solutions", "enterprise-software"],
    techGroups: [
      { title: "Data", items: ["Snowflake", "Databricks", "kdb+", "Kafka"] },
      { title: "Quant", items: ["Python", "Pandas", "Polars", "MLflow"] },
      { title: "Apps", items: ["React", "TypeScript", "Java", ".NET"] },
      { title: "Cloud", items: ["AWS", "Azure", "Confluent"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "Document intelligence", body: "Term-sheet, KYC, and contract extraction with audit trails." },
      { icon: BarChart3, title: "Forecasting", body: "Cash, P&L, and demand forecasts with explainability built in." },
      { icon: Bot, title: "Analyst copilots", body: "RAG copilots over governed financial data for analysts and treasurers." },
      { icon: Network, title: "Knowledge graphs", body: "Linked entities, instruments, and exposures for risk and surveillance." },
      { icon: ShieldCheck, title: "Surveillance", body: "Anomaly detection for trading, AML, and operational risk." },
      { icon: PiggyBank, title: "Pricing optimization", body: "ML-driven pricing for insurance, lending, and treasury products." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Faster close", body: "Automation cuts month-end and regulatory close cycles materially." },
      { title: "Lower TCO", body: "Cloud-native cores cut licensing and infrastructure overhead." },
      { title: "Stronger controls", body: "Lineage and access controls support every audit cycle." },
      { title: "Real-time insight", body: "Streaming pipelines turn quarterly views into live ones." },
      { title: "Quant productivity", body: "Researchers spend time on models, not infrastructure." },
      { title: "Audit-ready AI", body: "Model risk, evaluations, and human-in-the-loop where required." },
    ],
    caseStudies: [
      { title: "Risk platform modernization", outcome: "Real-time exposure across asset classes with audit-grade lineage.", placeholder: true },
      { title: "IFRS 17 reporting", outcome: "Automated regulatory submissions across multiple jurisdictions.", placeholder: true },
      { title: "CFO copilot", outcome: "Natural-language interface over governed financial data.", placeholder: true },
    ],
    faqs: [
      { q: "Can you support model risk management?", a: "Yes. We implement model inventories, evaluations, drift monitoring, and challenger frameworks aligned to SR 11-7 and similar regimes." },
      { q: "Are you comfortable with quant stacks?", a: "Yes — Python/Pandas/Polars, kdb+, KX, and modern Rust pipelines for high-throughput workloads." },
      { q: "How do you handle regulatory change?", a: "Configurable rule engines and versioned data models so new reporting regimes can be added without rewrites." },
    ],
    ctaTitle: "Modernize finance technology — with HIGAET.",
    ctaBody: "Tell us about your finance stack and goals. We'll respond with a credible plan.",
  }),

  banking: make({
    slug: "banking",
    eyebrow: "Banking",
    title: "Banking platforms designed for trust, speed, and digital experience.",
    subtitle: "Core banking modernization, digital channels, lending, and BaaS for retail, commercial, and challenger banks.",
    metaTitle: "Banking Software Solutions — HIGAET Technologies",
    metaDescription: "Core banking modernization, digital channels, lending, and BaaS engineering for retail, commercial, and challenger banks. By HIGAET Technologies.",
    heroHighlights: ["Core banking modernization", "Omnichannel digital experiences", "Open banking and BaaS", "Fraud and AML AI"],
    overviewTitle: "Banking experiences that match the rest of customers' lives.",
    overviewBody: "We modernize banking stacks in waves — protecting core stability while unlocking modern channels, partner integration, and AI-powered services. Every engagement bakes in security, compliance, and resilience.",
    challenges: [
      { title: "Monolithic cores", body: "Decade-old cores constrain product velocity and partner integration." },
      { title: "Customer expectations", body: "Customers expect FinTech-grade apps; banks struggle to match the experience." },
      { title: "Regulatory weight", body: "PSD2, DORA, AML, KYC, and local regimes demand continuous, defensible compliance." },
      { title: "Fraud and AML", body: "Sophisticated, AI-augmented attacks need AI-augmented defenses." },
      { title: "Open banking", body: "APIs and partner ecosystems are now table stakes; many banks lag." },
      { title: "Data fragmentation", body: "Customer data lives in silos, blocking real personalization." },
    ],
    solutions: [
      { icon: Landmark, title: "Core modernization", body: "Strangler-fig migrations from monolithic cores to modern, modular architectures." },
      { icon: CreditCard, title: "Digital channels", body: "Web and mobile apps with biometric auth, real-time notifications, and unified experiences." },
      { icon: Plug, title: "Open banking & BaaS", body: "PSD2-compliant APIs, partner portals, and embedded finance infrastructure." },
      { icon: ShieldCheck, title: "Fraud & AML AI", body: "Real-time fraud detection, AML monitoring, and customer-friendly step-up." },
      { icon: Workflow, title: "Lending platforms", body: "Origination, underwriting, servicing, and collections with embedded decisioning." },
      { icon: BarChart3, title: "Customer 360", body: "Unified data and analytics for personalization, retention, and risk." },
    ],
    recommendedServices: ["enterprise-software", "legacy-modernization", "api-development", "ai-solutions", "system-integration", "cloud-solutions"],
    techGroups: [
      { title: "Core", items: ["Mambu", "Thought Machine", "Temenos", "Java", ".NET"] },
      { title: "Channels", items: ["React Native", "Swift", "Kotlin", "Next.js"] },
      { title: "Open banking", items: ["FAPI", "OIDC", "OpenAPI"] },
      { title: "AI & data", items: ["Snowflake", "Databricks", "Feature stores", "MLflow"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "Fraud detection", body: "Real-time graph and behavior models with low-latency scoring." },
      { icon: ClipboardCheck, title: "AML & KYC", body: "Document parsing, screening, and case management with audit trails." },
      { icon: Bot, title: "Customer copilots", body: "Personal banking assistants grounded in customer data." },
      { icon: Sparkles, title: "Underwriting AI", body: "Explainable credit decisioning with bias and adverse-action controls." },
      { icon: BarChart3, title: "Next-best-action", body: "Real-time offers and interventions across journeys." },
      { icon: Network, title: "Entity resolution", body: "Customer and counterparty graphs for risk and personalization." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Faster product velocity", body: "Modular cores cut time-to-market for new products from years to months." },
      { title: "Lower fraud losses", body: "AI-augmented detection cuts loss rates and false positives." },
      { title: "Modern experiences", body: "Digital channels lift NPS, app store ratings, and engagement." },
      { title: "New revenue", body: "Open banking and BaaS unlock partner-driven revenue lines." },
      { title: "Lower run cost", body: "Cloud-native infrastructure cuts run cost vs legacy data centers." },
      { title: "Regulator confidence", body: "Audit-ready architecture supports supervisory engagement." },
    ],
    caseStudies: [
      { title: "Core banking modernization", outcome: "Wave-based strangler-fig modernization with zero customer downtime.", placeholder: true },
      { title: "Digital wallet launch", outcome: "Mobile-first wallet integrated with core and partner ecosystem.", placeholder: true },
      { title: "Fraud AI rollout", outcome: "Real-time fraud scoring across cards and account-to-account.", placeholder: true },
    ],
    faqs: [
      { q: "Will you touch the core?", a: "Yes, in waves. We rarely advocate big-bang core replacements; modular strangler-fig modernization wins." },
      { q: "How do you handle regulators?", a: "We design controls and documentation up front so regulator engagement is routine, not reactive." },
      { q: "Can you support BaaS programs?", a: "Yes — partner onboarding, API portals, ledger integration, and compliance tooling." },
    ],
    ctaTitle: "Modernize banking experiences — with HIGAET.",
    ctaBody: "Tell us about your bank and the next move you'd like to make.",
  }),

  fintech: make({
    slug: "fintech",
    eyebrow: "FinTech",
    title: "FinTech engineering for startups, scaleups, and incumbent challengers.",
    subtitle: "Payments, ledgers, embedded finance, and AI products — built fast and ready for regulation.",
    metaTitle: "FinTech Software Development — HIGAET Technologies",
    metaDescription: "FinTech engineering for payments, ledgers, embedded finance, and AI products. Built fast and ready for regulation. By HIGAET Technologies.",
    heroHighlights: ["Payments, ledgers, embedded finance", "Compliance baked in", "API-first by default", "Crypto and stablecoin ready"],
    overviewTitle: "Ship fast — without the technical or regulatory debt.",
    overviewBody: "FinTech rewards speed, but punishes shortcuts. We help you ship rapidly without leaving the debt that breaks at scale — clean ledgers, regulated-grade controls, and APIs ready for partner growth.",
    challenges: [
      { title: "Time-to-market pressure", body: "Investor and customer pressure to ship fast competes with technical and regulatory rigor." },
      { title: "Ledger correctness", body: "Get the ledger wrong early and every future feature multiplies the pain." },
      { title: "Regulatory readiness", body: "Even pre-license, controls and audit trails make later license applications smoother." },
      { title: "Payments complexity", body: "Card schemes, ACH, SEPA, FPS, RTP, and crypto rails each have their own quirks." },
      { title: "Partner integrations", body: "Banks, processors, KYC, AML, and identity vendors must be wired in safely." },
      { title: "Fraud at growth", body: "Scaling FinTechs are prime targets; defenses need to grow ahead of revenue." },
    ],
    solutions: [
      { icon: Repeat, title: "Ledgers & accounting", body: "Double-entry ledgers, settlement, and reconciliation designed for scale." },
      { icon: CreditCard, title: "Payments", body: "Card, ACH, SEPA, FPS, RTP, and crypto rails integrated with idempotency and retries." },
      { icon: Plug, title: "Embedded finance", body: "Card issuing, BNPL, lending, and savings products delivered via partner APIs." },
      { icon: ShieldCheck, title: "Compliance tooling", body: "KYC, KYB, AML, and sanctions screening with case management and audit." },
      { icon: Brain, title: "AI products", body: "Personal finance copilots, underwriting AI, and document automation." },
      { icon: Cable, title: "Open banking", body: "AISP / PISP integrations, PSD2 flows, and aggregated data products." },
    ],
    recommendedServices: ["custom-software-development", "api-development", "ai-solutions", "cloud-solutions", "qa-testing", "devops"],
    techGroups: [
      { title: "Backend", items: ["Node.js", "Go", "Rust", "Java"] },
      { title: "Ledger", items: ["TigerBeetle", "Custom doubles", "Event sourcing"] },
      { title: "Payments", items: ["Stripe", "Adyen", "Modulr", "FIS"] },
      { title: "Compliance", items: ["Onfido", "Persona", "ComplyAdvantage"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "KYC & document AI", body: "Document parsing, verification, and case management with low manual touch." },
      { icon: Bot, title: "Personal finance copilots", body: "AI assistants over user transaction data — with privacy and grounding." },
      { icon: Sparkles, title: "Underwriting AI", body: "Explainable credit and risk models with bias and adverse-action controls." },
      { icon: ShieldCheck, title: "Fraud & AML", body: "Real-time scoring, link analysis, and case management." },
      { icon: BarChart3, title: "Pricing AI", body: "Dynamic pricing for FX, lending, and subscription products." },
      { icon: Network, title: "Entity graphs", body: "Customer, merchant, and counterparty graphs for risk and offers." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Faster launches", body: "MVP-to-scale roadmaps that avoid the rewrites founders dread." },
      { title: "License readiness", body: "Controls, audit, and documentation accelerate later license applications." },
      { title: "Lower fraud cost", body: "Defenses that grow with revenue, not after losses." },
      { title: "Partner-ready APIs", body: "Open banking and embedded finance APIs that partners actually integrate with." },
      { title: "Clean ledger", body: "Accounting and settlement that scale without manual reconciliation." },
      { title: "AI advantage", body: "Applied AI woven into product economics, not bolted on." },
    ],
    caseStudies: [
      { title: "Embedded lending launch", outcome: "Partner-integrated lending product with explainable underwriting.", placeholder: true },
      { title: "Cross-border payments", outcome: "Multi-rail payment platform with FX hedging and idempotency.", placeholder: true },
      { title: "KYC automation", outcome: "Document AI cuts manual review to a fraction of original cost.", placeholder: true },
    ],
    faqs: [
      { q: "Pre-license or post-license?", a: "Both. We design controls and engineering practices that simplify later license applications and supervisory engagement." },
      { q: "Should we build our own ledger?", a: "Sometimes yes (for new rails), often no (for standard banking and payments). We help you decide based on growth and risk." },
      { q: "Can you support crypto rails?", a: "Yes — custody integrations, stablecoin settlement, and on/off ramps with compliance baked in." },
    ],
    ctaTitle: "Ship FinTech that scales — with HIGAET.",
    ctaBody: "Tell us about your product and stage. We'll respond with a credible plan.",
  }),

  retail: make({
    slug: "retail",
    eyebrow: "Retail",
    title: "Retail technology for omnichannel growth and operational margin.",
    subtitle: "POS, OMS, inventory, store ops, and AI personalization for retailers competing on experience and speed.",
    metaTitle: "Retail Technology Solutions — HIGAET Technologies",
    metaDescription: "Retail technology: POS, OMS, inventory, omnichannel, and AI personalization. Margin-grade engineering by HIGAET Technologies.",
    heroHighlights: ["POS, OMS, inventory, store ops", "Real-time inventory and demand", "AI personalization and search", "Omnichannel done well"],
    overviewTitle: "Retail platforms that protect margin and lift customer loyalty.",
    overviewBody: "We help retailers turn fragmented systems into a real omnichannel operation: connected stores, accurate inventory, smart promotions, and personalized experiences that customers actually notice.",
    challenges: [
      { title: "Channel fragmentation", body: "Stores, web, and marketplace systems don't share a single view of customer or inventory." },
      { title: "Inventory accuracy", body: "Stockouts, overstocks, and shrink drain margin and customer trust." },
      { title: "Slow store technology", body: "Legacy POS and store apps frustrate associates and customers alike." },
      { title: "Promotion complexity", body: "Pricing, loyalty, and promotion rules outgrow what legacy systems can express." },
      { title: "Personalization lag", body: "Customer data lives in silos that block real-time personalization." },
      { title: "Workforce productivity", body: "Store associates spend too much time on admin and not enough on customers." },
    ],
    solutions: [
      { icon: Store, title: "Modern POS & store ops", body: "Cloud POS, store apps, and clienteling tools that work offline-first." },
      { icon: Boxes, title: "OMS & inventory", body: "Order routing, ship-from-store, and real-time inventory across channels." },
      { icon: ShoppingBag, title: "Headless commerce", body: "Composable storefronts with experimentation and high performance." },
      { icon: Sparkles, title: "AI personalization", body: "Search, recommendations, and content tailored to each customer." },
      { icon: BarChart3, title: "Retail analytics", body: "Margin, mix, and demand insights tied to operational decisions." },
      { icon: Workflow, title: "Workforce tools", body: "Scheduling, task management, and associate copilots that buy time back." },
    ],
    recommendedServices: ["custom-software-development", "web-development", "mobile-development", "ai-solutions", "system-integration", "data-engineering"],
    techGroups: [
      { title: "Commerce", items: ["Shopify", "BigCommerce", "Commercetools", "Medusa"] },
      { title: "POS / OMS", items: ["NetSuite", "Manhattan", "Custom"] },
      { title: "Mobile", items: ["React Native", "Flutter", "Swift", "Kotlin"] },
      { title: "Data & AI", items: ["Snowflake", "dbt", "Algolia", "Vector DBs"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "Semantic search", body: "Search that understands intent — and converts." },
      { icon: Bot, title: "Conversational shopping", body: "AI assistants that guide discovery across product and inventory." },
      { icon: Sparkles, title: "Recommendations", body: "Real-time, cross-channel personalization grounded in customer 360." },
      { icon: BarChart3, title: "Demand forecasting", body: "Store-, SKU-, and channel-level forecasts that lift in-stock and cut overstock." },
      { icon: Brain, title: "Pricing & promo", body: "Dynamic pricing and promotion optimization with guardrails." },
      { icon: Network, title: "Customer graphs", body: "Identity resolution across channels and devices for loyalty and CDP." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Higher conversion", body: "Search, personalization, and performance lift online and in-store conversion." },
      { title: "Margin protection", body: "Smarter inventory and pricing cut markdowns and stockouts." },
      { title: "Faster fulfilment", body: "Order routing and ship-from-store cut delivery times and cost." },
      { title: "Loyal customers", body: "Personalized experiences raise repeat rates and lifetime value." },
      { title: "Productive stores", body: "Workforce tools and copilots reclaim associate hours." },
      { title: "Insight to action", body: "Analytics tied to operational systems, not just dashboards." },
    ],
    caseStudies: [
      { title: "Omnichannel relaunch", outcome: "Unified inventory, OMS, and storefront with measurable conversion lift.", placeholder: true },
      { title: "Personalization engine", outcome: "Real-time personalization across web and CRM channels.", placeholder: true },
      { title: "Store associate app", outcome: "Clienteling and stock-lookup app rolled out across stores.", placeholder: true },
    ],
    faqs: [
      { q: "Headless or monolith?", a: "Depends on team maturity and roadmap. We help you decide and avoid headless-just-because." },
      { q: "Can you connect to our legacy ERP?", a: "Yes — SAP, Oracle, NetSuite, and bespoke ERPs with event-driven integration." },
      { q: "How do you handle peak traffic?", a: "Performance budgets, edge rendering, autoscaling, and game-day load testing before peak events." },
    ],
    ctaTitle: "Lift retail experience and margin — with HIGAET.",
    ctaBody: "Tell us about your channels, stores, and goals. We'll respond with a focused plan.",
  }),

  ecommerce: make({
    slug: "ecommerce",
    eyebrow: "E-Commerce",
    title: "E-commerce engineering for conversion, scale, and AI-driven experience.",
    subtitle: "Headless storefronts, marketplaces, subscriptions, and AI shopping built for global growth.",
    metaTitle: "E-Commerce Software Solutions — HIGAET Technologies",
    metaDescription: "E-commerce engineering: headless storefronts, marketplaces, subscriptions, and AI shopping. Built for conversion and scale by HIGAET Technologies.",
    heroHighlights: ["Composable, headless commerce", "Marketplaces and subscriptions", "AI search and personalization", "Core Web Vitals on every release"],
    overviewTitle: "Storefronts that convert — and platforms that scale globally.",
    overviewBody: "We build commerce experiences customers complete and platforms operators can grow on. Performance, content, search, personalization, and operations are designed as one system, not point tools.",
    challenges: [
      { title: "Performance debt", body: "Slow, bloated storefronts cost conversion every week they stay slow." },
      { title: "Catalog complexity", body: "Multi-brand, multi-region catalogs strain legacy commerce platforms." },
      { title: "Search and discovery", body: "Default search misses intent and synonyms; customers leave or buy less." },
      { title: "Subscription mechanics", body: "Recurring billing, pauses, swaps, and dunning need careful product engineering." },
      { title: "Operational integration", body: "OMS, ERP, 3PL, and tax engines have to integrate cleanly to scale." },
      { title: "Personalization", body: "Customer data and signals rarely come together to drive real-time experience." },
    ],
    solutions: [
      { icon: ShoppingCart, title: "Headless storefronts", body: "Composable storefronts on Shopify Hydrogen, Next.js Commerce, and Medusa." },
      { icon: Boxes, title: "Marketplaces", body: "Multi-vendor catalogs, payouts, ratings, and onboarding flows." },
      { icon: Repeat, title: "Subscriptions", body: "Recurring billing, customer portals, and retention tooling." },
      { icon: Sparkles, title: "AI shopping", body: "Semantic search, recommendations, and conversational commerce." },
      { icon: Plug, title: "Operational integration", body: "OMS, ERP, 3PL, and tax integrations with event-driven patterns." },
      { icon: BarChart3, title: "Commerce analytics", body: "Funnels, cohorts, attribution, and merchandising analytics." },
    ],
    recommendedServices: ["web-development", "custom-software-development", "ai-solutions", "system-integration", "data-engineering", "ui-ux-design"],
    techGroups: [
      { title: "Commerce", items: ["Shopify", "Commercetools", "BigCommerce", "Medusa", "Saleor"] },
      { title: "Frontend", items: ["Next.js", "Remix", "Astro", "Tailwind"] },
      { title: "Search & AI", items: ["Algolia", "Typesense", "Vector DBs", "OpenAI"] },
      { title: "Ops", items: ["NetSuite", "Manhattan", "ShipBob", "Avalara"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "Semantic search", body: "Intent-aware search that lifts add-to-cart and conversion." },
      { icon: Bot, title: "Conversational commerce", body: "AI shopping assistants embedded into the storefront." },
      { icon: Sparkles, title: "Recommendations", body: "Real-time, cross-session personalization at scale." },
      { icon: BarChart3, title: "Pricing & promo", body: "Dynamic pricing and promotion optimization with guardrails." },
      { icon: ClipboardCheck, title: "Catalog AI", body: "Auto-generated product copy, attributes, and translations." },
      { icon: Network, title: "Customer graphs", body: "Identity resolution and lookalike modeling for acquisition and retention." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Higher conversion", body: "Performance, search, and personalization lift conversion measurably." },
      { title: "Faster releases", body: "Headless architecture lets product and content ship daily." },
      { title: "Lower total cost", body: "Composable architecture replaces expensive monoliths over time." },
      { title: "Global reach", body: "Multi-region, multi-currency, multi-language as first-class capability." },
      { title: "Retention", body: "Subscriptions, loyalty, and personalization raise LTV." },
      { title: "AI advantage", body: "Search and merchandising powered by modern AI, not legacy heuristics." },
    ],
    caseStudies: [
      { title: "Headless storefront launch", outcome: "Composable storefront with measurable Core Web Vitals improvement.", placeholder: true },
      { title: "Marketplace platform", outcome: "Multi-vendor marketplace with payouts and ratings.", placeholder: true },
      { title: "AI search", outcome: "Semantic search rollout with measurable conversion lift.", placeholder: true },
    ],
    faqs: [
      { q: "Shopify, Commercetools, or custom?", a: "Depends on scale, catalog complexity, and team. We pick the lightest platform that can grow with the business." },
      { q: "Can you handle Black Friday peaks?", a: "Yes. Edge rendering, caching, and game-day load testing are standard for our commerce work." },
      { q: "Do you support international growth?", a: "Yes — multi-region, multi-currency, multi-language, and tax compliance built in." },
    ],
    ctaTitle: "Lift commerce conversion and scale — with HIGAET.",
    ctaBody: "Tell us about your platform and goals. We'll respond with a focused plan.",
  }),

  manufacturing: make({
    slug: "manufacturing",
    eyebrow: "Manufacturing",
    title: "Manufacturing software that connects the shop floor to the boardroom.",
    subtitle: "MES, IoT, quality, maintenance, and AI for smart factories and global manufacturers.",
    metaTitle: "Manufacturing Software Solutions — HIGAET Technologies",
    metaDescription: "Smart manufacturing software: MES, IoT, quality, maintenance, and AI for factories and global manufacturers. By HIGAET Technologies.",
    heroHighlights: ["MES, MOM, IoT integration", "Predictive maintenance AI", "Quality and traceability", "OT/IT integration done safely"],
    overviewTitle: "Smart factories without the smart-factory hype.",
    overviewBody: "We help manufacturers connect OT and IT, raise OEE, and bring AI to operations without disrupting production. Engagements start with shop-floor reality and end with measurable throughput and quality wins.",
    challenges: [
      { title: "OT/IT divide", body: "Plant systems and enterprise IT speak different languages, blocking insight." },
      { title: "Legacy SCADA & MES", body: "Aging plant software constrains visibility, agility, and supplier integration." },
      { title: "Quality and traceability", body: "Regulatory and customer demands for traceability outgrow paper and Excel." },
      { title: "Unplanned downtime", body: "Reactive maintenance erodes OEE; predictive approaches need data plumbing." },
      { title: "Talent shortages", body: "Aging workforce and complex tools demand better operator UX and copilots." },
      { title: "Supply volatility", body: "Demand and supplier shocks require faster sensing and replanning." },
    ],
    solutions: [
      { icon: Cpu, title: "MES & MOM", body: "Modern manufacturing execution and operations platforms tied to ERP." },
      { icon: Network, title: "IoT & connectivity", body: "Edge gateways, time-series data, and OPC UA / MQTT bridges to enterprise data." },
      { icon: ShieldCheck, title: "Quality & traceability", body: "Genealogy, eDHR, and CAPA workflows aligned to FDA, IATF, and customer audits." },
      { icon: Brain, title: "Predictive maintenance", body: "Telemetry-driven models with operator-facing copilots and CMMS integration." },
      { icon: Activity, title: "OEE & analytics", body: "Real-time line and plant KPIs visible to operators, supervisors, and execs." },
      { icon: Workflow, title: "Workforce apps", body: "Mobile-first operator and technician apps with AR/AI assistance." },
    ],
    recommendedServices: ["custom-software-development", "system-integration", "ai-solutions", "data-engineering", "cloud-solutions", "devops"],
    techGroups: [
      { title: "Edge & IoT", items: ["OPC UA", "MQTT", "Kepware", "AWS IoT", "Azure IoT"] },
      { title: "Data", items: ["TimescaleDB", "InfluxDB", "Snowflake", "Databricks"] },
      { title: "ERP / MES", items: ["SAP", "Oracle", "PTC", "Aveva"] },
      { title: "AI", items: ["MLflow", "Vertex AI", "Edge ML", "Vision AI"] },
    ],
    aiOpportunities: [
      { icon: BarChart3, title: "Predictive maintenance", body: "Models that flag failures before they cause downtime." },
      { icon: ScanSearch, title: "Vision-based QA", body: "Defect detection at the line with explainable models and feedback loops." },
      { icon: Brain, title: "Process optimization", body: "ML that recommends setpoints and parameters for OEE and yield." },
      { icon: Bot, title: "Operator copilots", body: "AI assistants for troubleshooting, SOPs, and changeovers." },
      { icon: Sparkles, title: "Generative engineering", body: "AI-assisted CAD, BOMs, and design-for-manufacture support." },
      { icon: Network, title: "Supply graphs", body: "Linked supplier, part, and constraint graphs for resilience and replanning." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Higher OEE", body: "Real-time visibility and predictive maintenance lift availability and quality." },
      { title: "Lower scrap", body: "Vision-based QA and process tuning reduce defects and rework." },
      { title: "Faster changeovers", body: "Operator apps and copilots cut downtime between runs." },
      { title: "Audit-ready traceability", body: "Genealogy and eDHR satisfy regulators and OEM customers." },
      { title: "Workforce leverage", body: "Mobile tools and AI assist operators and technicians." },
      { title: "Resilient supply", body: "Sensing and replanning shorten response to disruption." },
    ],
    caseStudies: [
      { title: "OEE platform rollout", outcome: "Real-time OEE across multiple plants with operator dashboards.", placeholder: true },
      { title: "Predictive maintenance", outcome: "Reduced unplanned downtime on critical lines with telemetry models.", placeholder: true },
      { title: "Vision QA", outcome: "Defect detection on packaging lines with explainable AI.", placeholder: true },
    ],
    faqs: [
      { q: "Can you work in regulated industries?", a: "Yes — automotive (IATF), medical (FDA), aerospace (AS9100), and food (HACCP) all part of our portfolio." },
      { q: "What about OT cybersecurity?", a: "We design segmented, IEC 62443-aligned architectures for safe OT/IT integration." },
      { q: "Cloud or on-premise?", a: "Hybrid. Critical OT stays at the edge; analytics and AI typically run in cloud or private cloud with controlled data flows." },
    ],
    ctaTitle: "Modernize the factory — with HIGAET.",
    ctaBody: "Tell us about your plants and goals. We'll respond with a tailored plan.",
  }),

  logistics: make({
    slug: "logistics",
    eyebrow: "Logistics & supply chain",
    title: "Supply chain technology for visibility, speed, and resilience.",
    subtitle: "TMS, WMS, last-mile, control towers, and AI for shippers, 3PLs, and global supply chains.",
    metaTitle: "Logistics & Supply Chain Software — HIGAET Technologies",
    metaDescription: "TMS, WMS, last-mile, control-tower, and AI software for shippers, 3PLs, and global supply chains. By HIGAET Technologies.",
    heroHighlights: ["TMS, WMS, last-mile", "Real-time control towers", "Route and slot optimization", "AI for ETAs and exceptions"],
    overviewTitle: "Supply chains you can see — and steer in real time.",
    overviewBody: "We build supply chain platforms that turn signals into action: connected carriers, accurate inventory, intelligent routing, and exception management that shrinks the time from problem to resolution.",
    challenges: [
      { title: "Visibility gaps", body: "Shipments, inventory, and orders fragment across carriers, warehouses, and partners." },
      { title: "Last-mile cost", body: "Last-mile dominates delivery cost; routing and density decide profitability." },
      { title: "Inventory accuracy", body: "Stockouts and overstocks erode service levels and working capital." },
      { title: "Exception handling", body: "Delays, damages, and shortages need fast, repeatable resolution playbooks." },
      { title: "Carrier complexity", body: "Multi-carrier APIs, rate cards, and tracking standards consume integration effort." },
      { title: "Workforce productivity", body: "Warehouse and driver workflows still rely on slow, paper-based processes." },
    ],
    solutions: [
      { icon: Truck, title: "TMS & multi-carrier", body: "Carrier integration, rating, booking, tracking, and freight audit." },
      { icon: Warehouse, title: "WMS & inventory", body: "Slotting, picking, packing, and inventory accuracy for own and 3PL warehouses." },
      { icon: Activity, title: "Control tower", body: "Unified visibility across orders, shipments, inventory, and exceptions." },
      { icon: BarChart3, title: "Optimization", body: "Route, slot, and load optimization with operational guardrails." },
      { icon: Workflow, title: "Workforce apps", body: "Driver, picker, and dispatcher apps designed for speed and reliability." },
      { icon: Brain, title: "AI exceptions", body: "Predictive ETAs, exception classification, and resolution copilots." },
    ],
    recommendedServices: ["custom-software-development", "system-integration", "ai-solutions", "data-engineering", "mobile-development", "cloud-solutions"],
    techGroups: [
      { title: "Platforms", items: ["Project44", "FourKites", "Manhattan", "Blue Yonder"] },
      { title: "Maps & routing", items: ["Google Maps", "HERE", "OR-Tools", "OptaPlanner"] },
      { title: "Mobile", items: ["React Native", "Flutter", "Android"] },
      { title: "Data & AI", items: ["Snowflake", "Databricks", "TimescaleDB", "MLflow"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "ETA prediction", body: "ML-driven ETAs that beat static estimates and reduce inbound chaos." },
      { icon: Sparkles, title: "Exception classification", body: "Auto-classify and route exceptions to the right resolver." },
      { icon: BarChart3, title: "Demand & inventory", body: "Forecasting and replenishment that lift service and cut stock." },
      { icon: Brain, title: "Route optimization", body: "Adaptive routing with live traffic and constraint solvers." },
      { icon: Bot, title: "Driver copilots", body: "Voice and chat assistants for routing changes and proof of delivery." },
      { icon: Network, title: "Supply graphs", body: "Linked suppliers, orders, and constraints for resilient planning." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Lower delivery cost", body: "Routing and density gains cut last-mile and middle-mile cost." },
      { title: "Better service", body: "Accurate ETAs and exception handling lift OTIF and customer satisfaction." },
      { title: "Working capital", body: "Inventory accuracy and turn improvements free working capital." },
      { title: "Faster operations", body: "Workforce apps and copilots cut handling and dwell time." },
      { title: "Resilience", body: "Sensing and replanning shorten response to disruption." },
      { title: "Insight-driven steering", body: "Control towers turn data into operational decisions." },
    ],
    caseStudies: [
      { title: "Control tower", outcome: "Unified shipment and exception visibility across carriers.", placeholder: true },
      { title: "Last-mile platform", outcome: "Driver app, routing, and tracking for high-density delivery.", placeholder: true },
      { title: "AI ETAs", outcome: "ML ETA model with measurable accuracy improvement.", placeholder: true },
    ],
    faqs: [
      { q: "Can you integrate with our TMS / WMS?", a: "Yes — Manhattan, Blue Yonder, SAP, Project44, FourKites, and custom platforms." },
      { q: "Routing and optimization?", a: "Yes. We use commercial solvers and OR-Tools, with constraint models tuned to operational reality." },
      { q: "Driver and warehouse mobile?", a: "Yes — React Native, native, and ruggedized device support including barcode and RFID." },
    ],
    ctaTitle: "See and steer your supply chain — with HIGAET.",
    ctaBody: "Tell us about your network and goals. We'll respond with a tailored plan.",
  }),

  "real-estate": make({
    slug: "real-estate",
    eyebrow: "Real estate",
    title: "Real estate technology for portfolios, transactions, and tenant experience.",
    subtitle: "Listings, transactions, property operations, and AI for residential, commercial, and PropTech ventures.",
    metaTitle: "Real Estate Software Solutions — HIGAET Technologies",
    metaDescription: "Real estate technology for listings, transactions, property operations, and AI. Residential, commercial, and PropTech. By HIGAET Technologies.",
    heroHighlights: ["Listings, leasing, transactions", "Property operations and tenant apps", "AI valuation and matching", "Smart building integration"],
    overviewTitle: "Property platforms that lift NOI and tenant satisfaction.",
    overviewBody: "We build PropTech that helps owners, operators, and agents work faster — from listing to lease to ongoing operations — with AI grounded in real property and market data.",
    challenges: [
      { title: "Fragmented data", body: "Listings, leases, financials, and maintenance live in separate, inconsistent systems." },
      { title: "Manual transactions", body: "Offers, negotiations, and contracts still rely on email and PDFs." },
      { title: "Tenant experience gap", body: "Tenants expect digital experiences that most property operators don't deliver." },
      { title: "Operations cost", body: "Maintenance, energy, and compliance costs eat NOI without good tooling." },
      { title: "Valuation accuracy", body: "Pricing and underwriting often depend on stale comps and manual analysis." },
      { title: "Building tech debt", body: "BMS, IoT, and access control systems rarely integrate cleanly." },
    ],
    solutions: [
      { icon: Building2, title: "Listings & marketplaces", body: "Multi-channel listing platforms with rich media and AI matching." },
      { icon: Workflow, title: "Transaction platforms", body: "Offer, contract, and signing flows with audit-grade trails." },
      { icon: Stethoscope, title: "Property operations", body: "Maintenance, inspections, and vendor management with mobile-first UX." },
      { icon: Bot, title: "Tenant apps", body: "Tenant portals, communications, and service requests with AI assist." },
      { icon: BarChart3, title: "Portfolio analytics", body: "NOI, occupancy, and risk dashboards across portfolios." },
      { icon: Network, title: "Smart buildings", body: "Integration with BMS, IoT, access control, and energy systems." },
    ],
    recommendedServices: ["custom-software-development", "web-development", "mobile-development", "ai-solutions", "data-engineering", "system-integration"],
    techGroups: [
      { title: "Frontend", items: ["Next.js", "React Native", "Flutter"] },
      { title: "Backend", items: ["Node.js", "Python", "Postgres"] },
      { title: "AI", items: ["OpenAI", "Vector DBs", "Vision AI"] },
      { title: "Integration", items: ["BMS", "Access control", "MLS", "CRM"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "AI valuation", body: "AVMs and underwriting models grounded in property, market, and macro data." },
      { icon: Sparkles, title: "Listing & matching", body: "Semantic search and matchmaking for buyers, renters, and agents." },
      { icon: Bot, title: "Tenant copilots", body: "AI assistants for service requests, payments, and amenity bookings." },
      { icon: BarChart3, title: "Energy optimization", body: "ML control of HVAC and building systems for cost and ESG goals." },
      { icon: ClipboardCheck, title: "Document AI", body: "Lease and contract parsing for portfolio analytics and compliance." },
      { icon: Brain, title: "Investment AI", body: "Deal sourcing and screening copilots for investment teams." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Higher NOI", body: "Energy, vacancy, and ops gains lift net operating income." },
      { title: "Faster transactions", body: "Digital offers and contracts shorten deal cycles." },
      { title: "Tenant satisfaction", body: "Modern apps lift retention and word-of-mouth." },
      { title: "Better underwriting", body: "AI and data lift accuracy and speed of investment decisions." },
      { title: "Lower ops cost", body: "Mobile workflows and copilots cut admin overhead." },
      { title: "Sustainability", body: "Smart buildings deliver measurable ESG outcomes." },
    ],
    caseStudies: [
      { title: "Portfolio analytics", outcome: "NOI and occupancy dashboards across mixed-use portfolio.", placeholder: true },
      { title: "Tenant app", outcome: "Mobile tenant app with payments, requests, and amenities.", placeholder: true },
      { title: "AI valuation", outcome: "AVM with explainability for underwriting teams.", placeholder: true },
    ],
    faqs: [
      { q: "Residential or commercial?", a: "Both. Engagements span multifamily, single-family, commercial, and mixed-use portfolios." },
      { q: "Can you integrate with our BMS?", a: "Yes — BACnet, Modbus, and modern building protocols, plus access control and energy systems." },
      { q: "Do you support brokers and agents?", a: "Yes — CRM, listing, and transaction tools tailored to brokerage operations." },
    ],
    ctaTitle: "Lift NOI and tenant experience — with HIGAET.",
    ctaBody: "Tell us about your portfolio or product. We'll respond with a focused plan.",
  }),

  hospitality: make({
    slug: "hospitality",
    eyebrow: "Hospitality & travel",
    title: "Hospitality and travel technology for guest delight and operational ease.",
    subtitle: "PMS, booking, guest apps, revenue management, and AI for hotels, resorts, restaurants, and travel brands.",
    metaTitle: "Hospitality & Travel Technology — HIGAET Technologies",
    metaDescription: "PMS, booking, guest apps, revenue management, and AI for hotels, resorts, and travel brands. By HIGAET Technologies.",
    heroHighlights: ["Booking, PMS, guest apps", "Revenue and pricing AI", "Loyalty and personalization", "Multi-property, multi-region"],
    overviewTitle: "Technology that lets staff focus on hospitality.",
    overviewBody: "We build hospitality platforms that remove friction for guests and busywork for staff — modern booking, integrated PMS, smart loyalty, and AI that supports judgment instead of replacing it.",
    challenges: [
      { title: "Legacy PMS", body: "Aging property management systems block channel integration and modern guest UX." },
      { title: "Guest expectations", body: "Guests expect digital check-in, messaging, and personalization across stays." },
      { title: "Revenue complexity", body: "Pricing, distribution, and inventory across channels demand smarter automation." },
      { title: "Staff scarcity", body: "Lean operations need software that does more of the work without losing the human touch." },
      { title: "Data silos", body: "PMS, POS, CRM, and channel manager data rarely combine for real personalization." },
      { title: "Loyalty fragmentation", body: "Brand, property, and partner loyalty programs sit in silos that confuse guests." },
    ],
    solutions: [
      { icon: Hotel, title: "Modern PMS & booking", body: "Cloud PMS, direct booking, and channel integration tied to modern guest UX." },
      { icon: Bot, title: "Guest apps & messaging", body: "Mobile check-in, in-stay messaging, requests, and upsell flows." },
      { icon: BarChart3, title: "Revenue management", body: "AI-assisted pricing, segmentation, and distribution across channels." },
      { icon: Sparkles, title: "Loyalty & personalization", body: "Unified loyalty, preferences, and offers across brand and property." },
      { icon: Workflow, title: "Operations apps", body: "Housekeeping, F&B, and maintenance apps designed for fast turn-over and quality." },
      { icon: Plug, title: "Channel & integration", body: "OTAs, GDS, payments, and PMS integrations done cleanly." },
    ],
    recommendedServices: ["custom-software-development", "mobile-development", "ai-solutions", "system-integration", "data-engineering", "ui-ux-design"],
    techGroups: [
      { title: "Hospitality", items: ["Mews", "Cloudbeds", "Opera", "Custom PMS"] },
      { title: "Distribution", items: ["SiteMinder", "Sabre", "Amadeus"] },
      { title: "AI", items: ["OpenAI", "RM models", "Vector DBs"] },
      { title: "Apps", items: ["React Native", "Flutter", "Next.js"] },
    ],
    aiOpportunities: [
      { icon: BarChart3, title: "Dynamic pricing", body: "Demand-aware pricing across properties, segments, and channels." },
      { icon: Bot, title: "Guest copilots", body: "AI concierges that handle requests, upsell, and answer questions 24/7." },
      { icon: Sparkles, title: "Personalization", body: "Offers and content tailored to stay history and preferences." },
      { icon: ScanSearch, title: "Review and sentiment AI", body: "Aggregate, classify, and act on reviews across platforms." },
      { icon: ClipboardCheck, title: "Operations AI", body: "Predict cleaning, F&B, and maintenance demand to staff smarter." },
      { icon: Network, title: "Loyalty graphs", body: "Unified guest profiles across brand, property, and partner ecosystems." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Higher RevPAR", body: "Smarter pricing and distribution lift revenue per room." },
      { title: "Direct booking lift", body: "Better booking UX shifts share away from OTAs." },
      { title: "Guest satisfaction", body: "Mobile UX and messaging lift reviews and repeat rates." },
      { title: "Staff productivity", body: "Operations apps and AI reduce admin time and rework." },
      { title: "Lower distribution cost", body: "Direct channels and smarter mix reduce OTA dependency." },
      { title: "Brand consistency", body: "Multi-property platforms maintain consistent guest experience." },
    ],
    caseStudies: [
      { title: "Direct booking platform", outcome: "Modern booking with measurable share shift from OTAs.", placeholder: true },
      { title: "AI concierge", outcome: "24/7 guest copilot with measurable response time improvement.", placeholder: true },
      { title: "Revenue management", outcome: "AI pricing engine across multi-property portfolio.", placeholder: true },
    ],
    faqs: [
      { q: "Hotels, restaurants, or travel?", a: "All three. Our hospitality work spans hotels, F&B, resorts, and travel brands." },
      { q: "Can you integrate with our PMS?", a: "Yes — Opera, Mews, Cloudbeds, custom and legacy PMS through certified or built integrations." },
      { q: "Do you support multi-property?", a: "Yes. Multi-brand, multi-region, multi-currency, and multi-language are routine." },
    ],
    ctaTitle: "Delight guests and unburden staff — with HIGAET.",
    ctaBody: "Tell us about your properties or product. We'll respond with a focused plan.",
  }),

  government: make({
    slug: "government",
    eyebrow: "Government & public sector",
    title: "Public-sector technology for citizen services, transparency, and trust.",
    subtitle: "Digital services, case management, and AI for ministries, agencies, and public utilities.",
    metaTitle: "Government & Public Sector Software — HIGAET Technologies",
    metaDescription: "Public-sector technology: digital citizen services, case management, and AI for ministries, agencies, and utilities. By HIGAET Technologies.",
    heroHighlights: ["Citizen-grade UX, accessibility-first", "Secure by design", "Open standards and APIs", "Audit and procurement-friendly"],
    overviewTitle: "Public services people can actually use.",
    overviewBody: "We design and build public-sector platforms that are accessible, secure, and accountable — and that ship in months, not years. Engagements respect procurement, privacy, and the people the service is for.",
    challenges: [
      { title: "Legacy systems", body: "Decades-old systems block service modernization and integration." },
      { title: "Procurement friction", body: "Long cycles and complex requirements slow delivery of needed services." },
      { title: "Citizen experience gap", body: "Public services often lag consumer-grade UX, hurting adoption and trust." },
      { title: "Security and privacy", body: "Threat landscape and regulatory load demand serious controls." },
      { title: "Data sharing", body: "Inter-agency data sharing is hard — policy, technical, and political." },
      { title: "AI policy", body: "Public-sector AI demands transparency, accountability, and bias controls." },
    ],
    solutions: [
      { icon: Users, title: "Citizen services", body: "Digital application, case tracking, and self-service across citizen journeys." },
      { icon: ClipboardCheck, title: "Case management", body: "Workflows, evidence, and decision support for caseworkers and reviewers." },
      { icon: ShieldCheck, title: "Identity & security", body: "Government identity, MFA, RBAC, and audit logging by default." },
      { icon: Cable, title: "Open APIs", body: "Standards-based APIs for inter-agency integration and partner ecosystems." },
      { icon: BarChart3, title: "Open data & analytics", body: "Open data portals, dashboards, and AI for evidence-based policy." },
      { icon: Bot, title: "Service copilots", body: "AI assistants for citizens and caseworkers — with policy guardrails." },
    ],
    recommendedServices: ["custom-software-development", "system-integration", "ai-solutions", "data-engineering", "cloud-solutions", "ui-ux-design"],
    techGroups: [
      { title: "Standards", items: ["OpenAPI", "OAuth", "OIDC", "WCAG"] },
      { title: "Cloud", items: ["Sovereign cloud", "AWS", "Azure", "GCP"] },
      { title: "Apps", items: ["React", "Next.js", "Node.js", ".NET"] },
      { title: "AI", items: ["OpenAI", "Open LLMs", "Evals"] },
    ],
    aiOpportunities: [
      { icon: ScanSearch, title: "Document AI", body: "Parsing and classification across applications, evidence, and correspondence." },
      { icon: Bot, title: "Citizen copilots", body: "Multilingual AI assistants grounded in policy with clear escalation." },
      { icon: ClipboardCheck, title: "Caseworker support", body: "Decision support and drafting tools that respect policy guardrails." },
      { icon: BarChart3, title: "Policy analytics", body: "Evidence-based policy with explainable models and audit trails." },
      { icon: Sparkles, title: "Service triage", body: "Routing and prioritization of demand with explainable scoring." },
      { icon: Network, title: "Knowledge graphs", body: "Linked policy, regulation, and case data for grounded AI." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Higher adoption", body: "Citizen-grade UX lifts digital uptake and reduces call-center load." },
      { title: "Faster delivery", body: "Modern stacks and agile delivery ship services in months, not years." },
      { title: "Lower cost-to-serve", body: "Automation and self-service reduce admin and contact-center cost." },
      { title: "Transparency", body: "Open data and audit trails build public trust." },
      { title: "Inter-agency data", body: "Standards-based APIs unlock collaboration with controls." },
      { title: "Accessibility", body: "WCAG 2.2 AA baked in for inclusive service delivery." },
    ],
    caseStudies: [
      { title: "Citizen service portal", outcome: "Unified digital service portal across agency services.", placeholder: true },
      { title: "Caseworker copilot", outcome: "AI drafting and decision-support tool for caseworkers.", placeholder: true },
      { title: "Open data platform", outcome: "Open data portal with analytics and APIs.", placeholder: true },
    ],
    faqs: [
      { q: "Are you procurement-ready?", a: "Yes. We're comfortable with framework procurements, GovTech, and bespoke procurement processes." },
      { q: "Sovereign cloud?", a: "Yes — sovereign and on-shore cloud regions on AWS, Azure, GCP, and government-specific providers." },
      { q: "Open source?", a: "Where it fits. We build on open standards and contribute back where possible." },
    ],
    ctaTitle: "Modernize public services — with HIGAET.",
    ctaBody: "Tell us about your service or department. We'll respond with a tailored plan.",
  }),

  startups: make({
    slug: "startups",
    eyebrow: "Startups",
    title: "Engineering partners for startups racing to product-market fit.",
    subtitle: "MVPs, scale-ups, and AI products built with the speed founders need — and the rigor investors expect.",
    metaTitle: "Startup Software Development — HIGAET Technologies",
    metaDescription: "Engineering for startups: MVPs, scale-ups, and AI products built with the speed founders need and the rigor investors expect. By HIGAET Technologies.",
    heroHighlights: ["MVPs in weeks", "Investor-grade engineering", "Founder-mode collaboration", "Scale-ready from day one"],
    overviewTitle: "Speed without the rewrite debt.",
    overviewBody: "Startups need to ship fast, learn faster, and avoid the rewrite tax. We build MVPs and scale-ready platforms that move quickly without the architectural shortcuts that kill momentum later.",
    challenges: [
      { title: "Time-to-validation", body: "Every month without users in front of the product erodes runway." },
      { title: "Founder bandwidth", body: "Founders need to be in customers and capital, not stuck reviewing PRs." },
      { title: "Hiring friction", body: "Senior engineers are slow and expensive to hire pre-Series A." },
      { title: "Investor scrutiny", body: "Diligence on architecture, security, and team is now standard." },
      { title: "Scaling cliffs", body: "Quick wins built on shortcuts often hit walls at the worst possible moment." },
      { title: "AI advantage", body: "Founders need to use AI well — both in product and in engineering velocity." },
    ],
    solutions: [
      { icon: Rocket, title: "MVPs in weeks", body: "Senior squads ship validated MVPs fast — without locking the product into rewrites." },
      { icon: Layers, title: "Scale-ready foundations", body: "Modular architecture, infra as code, and observability from day one." },
      { icon: Bot, title: "AI products", body: "RAG, agents, and applied AI features that customers actually use." },
      { icon: ShieldCheck, title: "Investor-ready", body: "Security, IP, documentation, and metrics that survive due diligence." },
      { icon: Users, title: "Founder mode", body: "Daily collaboration with founders, in your tools, on your schedule." },
      { icon: Repeat, title: "Hand-off ready", body: "Built so an in-house team can absorb ownership when you hire ahead." },
    ],
    recommendedServices: ["custom-software-development", "web-development", "mobile-development", "ai-solutions", "dedicated-team", "ui-ux-design"],
    techGroups: [
      { title: "Frontend", items: ["Next.js", "React Native", "Tailwind", "Shadcn"] },
      { title: "Backend", items: ["Node.js", "Python", "Postgres", "Supabase"] },
      { title: "AI", items: ["OpenAI", "LangChain", "Vector DBs", "Evals"] },
      { title: "Cloud", items: ["Vercel", "Cloudflare", "AWS", "Supabase"] },
    ],
    aiOpportunities: [
      { icon: Sparkles, title: "AI features", body: "Differentiated AI features (search, copilots, automation) shipped fast." },
      { icon: ScanSearch, title: "Data leverage", body: "Turn early customer data into models and products that compound." },
      { icon: Bot, title: "Engineering AI", body: "We use AI in our own SDLC to accelerate delivery without sacrificing quality." },
      { icon: BarChart3, title: "Growth analytics", body: "Activation, retention, and funnel analytics from week one." },
      { icon: Brain, title: "Product strategy AI", body: "AI experiments framed and evaluated with founders." },
      { icon: Network, title: "Customer graphs", body: "Identity and behavior graphs for personalization and retention." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Faster validation", body: "MVPs in weeks turn capital into customer signal sooner." },
      { title: "Lower hiring risk", body: "Senior squads close the talent gap without permanent overhead." },
      { title: "Investor confidence", body: "Engineering quality supports diligence and follow-on rounds." },
      { title: "Scale headroom", body: "Foundations that survive growth, not break at it." },
      { title: "AI-native product", body: "AI built into the product as a differentiator, not a sticker." },
      { title: "Optionality", body: "Hand off, augment, or scale our team as your roadmap evolves." },
    ],
    caseStudies: [
      { title: "AI SaaS MVP", outcome: "Validated AI SaaS MVP launched and revenue-ready in one quarter.", placeholder: true },
      { title: "Series A platform", outcome: "Production-grade platform built for diligence and post-raise scale.", placeholder: true },
      { title: "Mobile product launch", outcome: "Native-quality mobile app shipped to App Store and Play Store.", placeholder: true },
    ],
    faqs: [
      { q: "Can we move from MVP to scale with you?", a: "Yes. Most founders run the same squad from MVP through Series A and beyond." },
      { q: "Will you take equity?", a: "Selectively — we co-build with a small portfolio of founders where strategic fit is strong." },
      { q: "How fast can we start?", a: "Typically two weeks from contract to first working sprint." },
    ],
    ctaTitle: "Ship faster — with HIGAET.",
    ctaBody: "Tell us about your idea or current build. We'll respond with a credible plan.",
  }),

  sme: make({
    slug: "sme",
    eyebrow: "Small & medium businesses",
    title: "Pragmatic technology partners for growing SMEs.",
    subtitle: "Custom software, automation, and AI tailored to the budgets and reality of small and medium businesses.",
    metaTitle: "SME Software Solutions — HIGAET Technologies",
    metaDescription: "Custom software, automation, and AI for small and medium businesses. Pragmatic, ROI-focused engagements by HIGAET Technologies.",
    heroHighlights: ["ROI-focused engagements", "Buy-vs-build advice you can trust", "Automation that pays back fast", "AI without the hype"],
    overviewTitle: "Real impact for businesses without enterprise budgets.",
    overviewBody: "SMEs don't need a six-month transformation program. They need targeted software, automation, and AI that solve real problems quickly. We size engagements to ROI and pick the lightest path that works.",
    challenges: [
      { title: "Off-the-shelf gaps", body: "SaaS tools don't quite fit the way the business actually runs." },
      { title: "Manual processes", body: "Spreadsheets and email automations break as the business grows." },
      { title: "IT capacity", body: "Lean IT teams need partners who do — not just advise." },
      { title: "Limited budgets", body: "Every dollar must show ROI; vanity tech is a non-starter." },
      { title: "AI overwhelm", body: "Owners hear AI everywhere but don't know where to start safely." },
      { title: "Cyber risk", body: "SMEs are favored targets; defenses need to be solid without being heavy." },
    ],
    solutions: [
      { icon: Workflow, title: "Custom apps", body: "Targeted apps that fill the gaps where SaaS doesn't quite fit." },
      { icon: Repeat, title: "Automation", body: "Workflow, document, and integration automation with quick payback." },
      { icon: Bot, title: "AI assistants", body: "Customer service, ops, and sales copilots grounded in your data." },
      { icon: ShieldCheck, title: "Security baseline", body: "Right-sized security and identity controls that satisfy customers and insurers." },
      { icon: BarChart3, title: "Analytics", body: "Dashboards and reporting tied to the decisions that matter." },
      { icon: Cable, title: "Integrations", body: "Connect accounting, CRM, ecommerce, and ops tools cleanly." },
    ],
    recommendedServices: ["custom-software-development", "ai-solutions", "system-integration", "web-development", "business-intelligence", "software-maintenance"],
    techGroups: [
      { title: "SaaS stack", items: ["HubSpot", "Salesforce", "Xero", "QuickBooks"] },
      { title: "Apps", items: ["Next.js", "Supabase", "Postgres"] },
      { title: "AI", items: ["OpenAI", "Vector DBs", "LangChain"] },
      { title: "Automation", items: ["Zapier", "Make", "n8n", "Workato"] },
    ],
    aiOpportunities: [
      { icon: Bot, title: "Customer service AI", body: "AI assistants for FAQs, bookings, and order updates — with human handoff." },
      { icon: ClipboardCheck, title: "Document automation", body: "Quote-to-cash, invoice processing, and contract parsing." },
      { icon: Sparkles, title: "Marketing AI", body: "Content, segmentation, and lifecycle marketing automation." },
      { icon: BarChart3, title: "Sales analytics", body: "Pipeline, forecast, and rep coaching analytics." },
      { icon: ScanSearch, title: "Lead scoring", body: "Prioritize the inbox and pipeline with explainable scores." },
      { icon: Brain, title: "Ops copilots", body: "Internal AI assistants for SOPs, training, and operations." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Fast payback", body: "Automation engagements typically pay back within months." },
      { title: "Hours back", body: "Owners and staff reclaim hours from low-value admin." },
      { title: "Growth headroom", body: "Software that scales as customers and revenue grow." },
      { title: "Lower SaaS sprawl", body: "Consolidation and integration cut tool cost and confusion." },
      { title: "Customer experience", body: "Modern, mobile-friendly experiences match what customers expect." },
      { title: "Risk down", body: "Right-sized security protects revenue and reputation." },
    ],
    caseStudies: [
      { title: "Operations automation", outcome: "Document and workflow automation across operations.", placeholder: true },
      { title: "Custom CRM extension", outcome: "Tailored extension on top of standard CRM for a niche workflow.", placeholder: true },
      { title: "AI customer service", outcome: "AI assistant deflects routine inquiries with human handoff.", placeholder: true },
    ],
    faqs: [
      { q: "Are you affordable for SMEs?", a: "Yes — we size engagements to outcomes and budget, and recommend SaaS over custom build whenever it's the right call." },
      { q: "Can you maintain what you build?", a: "Yes — ongoing maintenance and support under clear SLAs." },
      { q: "Can you help us start with AI?", a: "Yes. We run focused discovery sprints to find high-ROI AI use cases before any build." },
    ],
    ctaTitle: "Get real ROI from technology — with HIGAET.",
    ctaBody: "Tell us about your business and goals. We'll respond with a focused plan.",
  }),

  enterprise: make({
    slug: "enterprise",
    eyebrow: "Large enterprises",
    title: "Enterprise technology programs that ship — and stick.",
    subtitle: "Strategy, platforms, modernization, and AI for global enterprises operating at scale.",
    metaTitle: "Enterprise Technology Solutions — HIGAET Technologies",
    metaDescription: "Enterprise technology programs: strategy, platforms, modernization, and AI for global enterprises operating at scale. By HIGAET Technologies.",
    heroHighlights: ["Strategy through delivery, one partner", "SOC 2 / ISO 27001 aligned", "Global, multi-region delivery", "AI woven across the value chain"],
    overviewTitle: "Programs that respect enterprise reality — and still ship.",
    overviewBody: "We deliver enterprise programs without the slide-only consulting overhead. The same senior people who advise also build, and the work is structured to land in the operating model — not just the deck.",
    challenges: [
      { title: "Program drag", body: "Big programs slow under governance weight, vendor chains, and integration debt." },
      { title: "Legacy estates", body: "Decades of systems make every initiative a careful integration exercise." },
      { title: "Talent leverage", body: "Internal teams are stretched across BAU and strategic initiatives." },
      { title: "Vendor coordination", body: "Multiple integrators and SaaS vendors fight rather than align." },
      { title: "AI scaling", body: "Pilots stall; few enterprises run AI at scale with the governance to match." },
      { title: "Adoption", body: "Change management determines whether new platforms actually get used." },
    ],
    solutions: [
      { icon: Building2, title: "Enterprise platforms", body: "Modular, secure, scalable platforms with enterprise governance." },
      { icon: Layers, title: "Modernization programs", body: "Strangler-fig migrations and replatforms tied to business outcomes." },
      { icon: Plug, title: "Integration", body: "Event-driven, API-first integration across SaaS, ERP, and bespoke systems." },
      { icon: Brain, title: "Applied AI", body: "AI across operations, customer experience, and decision support with governance." },
      { icon: ShieldCheck, title: "Security & compliance", body: "SOC 2, ISO 27001, HIPAA, PCI baked into platform and SDLC." },
      { icon: Users, title: "Change & enablement", body: "Adoption, training, and operating-model design tied to delivery." },
    ],
    recommendedServices: ["enterprise-software", "legacy-modernization", "system-integration", "ai-solutions", "cloud-solutions", "it-consulting"],
    techGroups: [
      { title: "Platforms", items: ["SAP", "Oracle", "Microsoft", "Salesforce"] },
      { title: "Cloud", items: ["AWS", "Azure", "GCP", "Private cloud"] },
      { title: "Data & AI", items: ["Snowflake", "Databricks", "Vector DBs", "MLOps"] },
      { title: "Integration", items: ["MuleSoft", "Apigee", "Kafka", "Event streams"] },
    ],
    aiOpportunities: [
      { icon: ClipboardCheck, title: "Process automation", body: "Document, workflow, and decision automation at enterprise scale." },
      { icon: Bot, title: "Enterprise copilots", body: "Role-specific copilots grounded in enterprise data with governance." },
      { icon: BarChart3, title: "Decision analytics", body: "Forecasting, optimization, and decision support across functions." },
      { icon: ScanSearch, title: "Knowledge AI", body: "Enterprise search and grounded answers across systems and documents." },
      { icon: Sparkles, title: "Customer experience AI", body: "Personalization, support, and sales AI across enterprise channels." },
      { icon: Network, title: "Enterprise graphs", body: "Linked customer, product, and process graphs for AI grounding." },
    ],
    process: PROCESS_STANDARD,
    benefits: [
      { title: "Faster outcomes", body: "Tight scopes and senior squads compress program timelines." },
      { title: "Lower TCO", body: "Modern platforms and FinOps cut run cost meaningfully." },
      { title: "Audit-ready", body: "Programs designed to pass internal audit and regulator scrutiny." },
      { title: "AI at scale", body: "AI moves from pilots to production with governance." },
      { title: "Vendor leverage", body: "Independent advice on SaaS, hyperscaler, and integrator choices." },
      { title: "Adoption", body: "Change management lands the work in the operating model." },
    ],
    caseStudies: [
      { title: "Enterprise platform program", outcome: "Modular enterprise platform delivered across regions and brands.", placeholder: true },
      { title: "Modernization wave", outcome: "Strangler-fig modernization of legacy core under regulatory cover.", placeholder: true },
      { title: "Enterprise AI rollout", outcome: "Role-specific copilots deployed with governance and adoption.", placeholder: true },
    ],
    faqs: [
      { q: "Do you work with our incumbents?", a: "Yes. We're vendor-pragmatic and routinely deliver alongside SIs, hyperscalers, and SaaS vendors." },
      { q: "Sovereign or multi-region?", a: "Both. Architectures and operating models are designed for the jurisdictions you operate in." },
      { q: "How do you handle change management?", a: "Embedded change leads, training, and operating-model design land delivery in the business." },
    ],
    ctaTitle: "Run enterprise programs that ship — with HIGAET.",
    ctaBody: "Tell us about the program. We'll respond with a structured proposal.",
  }),
};
