import {
  AppWindow,
  BarChart3,
  Boxes,
  Brush,
  Building2,
  Cloud,
  Code2,
  Cpu,
  Database,
  GitBranch,
  GraduationCap,
  Heart,
  Landmark,
  Layers,
  LineChart,
  Lock,
  Network,
  Package,
  PenTool,
  Repeat,
  Rocket,
  Server,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  TestTube2,
  Truck,
  Users,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";
import type { ServiceDetailContent } from "@/components/site/ServiceDetailPage";

// Shared building blocks reused across service detail pages.
const COMMON_INDUSTRIES: ServiceDetailContent["industries"] = [
  { icon: GraduationCap, name: "Education", body: "Learning platforms, admissions workflows, faculty tools, and student-facing portals." },
  { icon: Heart, name: "Healthcare", body: "Patient portals, clinical workflows, and decision support built around privacy and uptime." },
  { icon: Landmark, name: "Finance & FinTech", body: "Core banking, payments, KYC, risk, and embedded finance with strict security baselines." },
  { icon: ShoppingBag, name: "Retail & E-commerce", body: "Storefronts, marketplaces, fulfillment integrations, and AI personalization." },
  { icon: Truck, name: "Logistics", body: "Ops dashboards, IoT telemetry, route optimization, and warehouse automation." },
  { icon: Building2, name: "Enterprise & SaaS", body: "Internal platforms, partner portals, and multi-tenant SaaS products at scale." },
];

const COMMON_WHY_US: ServiceDetailContent["whyUs"] = [
  { icon: Users, title: "Senior squads, low churn", body: "We staff with engineers trained through the HIGAET Academy talent pipeline — no rotating juniors." },
  { icon: Zap, title: "Product-minded delivery", body: "Squads obsess over user outcomes and KPIs, not just ticket throughput or hours billed." },
  { icon: Lock, title: "Enterprise governance", body: "NDAs, IP assignment, audit logs, and SOC 2-aligned controls on every engagement." },
  { icon: Layers, title: "Full-stack capability", body: "Strategy, design, engineering, AI, data, and SRE — one accountable team, not a chain of vendors." },
  { icon: Cpu, title: "AI in the DNA", body: "Every project considers where intelligent automation creates leverage for users and operators." },
  { icon: Rocket, title: "Skin in the game", body: "We co-build with select partners, sharing both delivery risk and long-term upside." },
];

// Helper to compose a service definition with sensible defaults.
function makeService(input: Partial<ServiceDetailContent> & {
  slug: string;
  title: string;
  subtitle: string;
  eyebrow: string;
  metaTitle: string;
  metaDescription: string;
  overviewBody: string;
  benefits: ServiceDetailContent["benefits"];
  features: ServiceDetailContent["features"];
  process: ServiceDetailContent["process"];
  techGroups: ServiceDetailContent["techGroups"];
  faqs: ServiceDetailContent["faqs"];
  ctaTitle: string;
  ctaBody: string;
  related: ServiceDetailContent["related"];
  overviewTitle: string;
  heroHighlights: string[];
}): ServiceDetailContent {
  return {
    brand: "tech",
    path: `/technologies/${input.slug}`,
    industries: COMMON_INDUSTRIES,
    whyUs: COMMON_WHY_US,
    ...input,
  };
}

export const SERVICES: Record<string, ServiceDetailContent> = {
  "web-development": makeService({
    slug: "web-development",
    eyebrow: "Web application development",
    title: "Web applications engineered for scale, speed, and SEO.",
    subtitle: "From customer portals to multi-tenant SaaS, we ship fast, accessible, AI-ready web platforms on modern stacks.",
    metaTitle: "Web Application Development Services — HIGAET Technologies",
    metaDescription: "Enterprise web application development with React, Next.js, TypeScript. SSR, performance, accessibility, and SEO built in by HIGAET Technologies.",
    heroHighlights: ["Core Web Vitals on every release", "Accessible by default (WCAG 2.2)", "SSR/SSG for SEO and speed", "Component libraries you can extend"],
    overviewTitle: "Web platforms users — and search engines — love.",
    overviewBody: "We build modern web applications that load instantly, rank well, and stay maintainable. Senior teams own architecture, design systems, performance budgets, and the CI pipeline so every release is faster and safer than the last.",
    benefits: [
      { title: "Conversion that compounds", body: "Performance, UX, and SEO improvements stack into measurable revenue lift quarter over quarter." },
      { title: "Reusable design system", body: "Tokens, components, and patterns scale across products without re-inventing the UI each time." },
      { title: "Always-on accessibility", body: "WCAG 2.2 AA tested in CI — not retro-fitted after a compliance audit." },
      { title: "Future-proof architecture", body: "Modular, framework-current code keeps you off the upgrade treadmill and ready for AI features." },
      { title: "Lower hosting bills", body: "Edge rendering, image optimization, and smart caching cut infrastructure costs from day one." },
      { title: "Confident releases", body: "Preview deploys, visual regression, and feature flags make weekly releases a non-event." },
    ],
    features: [
      { icon: AppWindow, title: "Customer portals", body: "Account, billing, support, and self-service flows wired into your back office." },
      { icon: Boxes, title: "Multi-tenant SaaS", body: "Tenancy, RBAC, billing, and admin tooling baked into the platform from day one." },
      { icon: Layers, title: "Headless commerce", body: "Composable storefronts on Shopify, BigCommerce, Medusa, or custom backends." },
      { icon: Workflow, title: "Internal tools & dashboards", body: "Replace spreadsheets with safe, audited internal apps your ops team actually uses." },
      { icon: Sparkles, title: "AI-enhanced UX", body: "Search, chat, summarization, and personalization built on retrieval and evaluation pipelines." },
      { icon: ShieldCheck, title: "Security & compliance", body: "SSO, MFA, audit logging, and SOC 2-aligned controls included by default." },
    ],
    process: [
      { title: "Discover", body: "User research, KPIs, technical audit, and a roadmap stakeholders can sign off on.", deliverables: ["KPIs", "Architecture sketch", "Roadmap"] },
      { title: "Design", body: "UX flows, design system, content model, and prototypes tested with real users.", deliverables: ["Design system", "Prototypes"] },
      { title: "Build", body: "Senior squads ship in two-week sprints with code review, automated tests, and demos.", deliverables: ["Working software", "Test suite"] },
      { title: "Launch", body: "Performance budgets, accessibility audit, SEO checks, and go-live with monitoring.", deliverables: ["SLOs", "Runbooks"] },
      { title: "Operate", body: "24/7 SRE, incident response, and continuous improvement against product KPIs.", deliverables: ["Dashboards", "Quarterly reviews"] },
    ],
    techGroups: [
      { title: "Frontend", items: ["React", "Next.js", "Remix", "TanStack", "TypeScript", "Tailwind"] },
      { title: "Backend", items: ["Node.js", "NestJS", "Python", "Go", ".NET", "GraphQL"] },
      { title: "Data", items: ["PostgreSQL", "MongoDB", "Redis", "Elasticsearch"] },
      { title: "Edge / Cloud", items: ["Vercel", "Cloudflare", "AWS", "Azure", "Google Cloud"] },
      { title: "Quality", items: ["Playwright", "Vitest", "Storybook", "Lighthouse CI"] },
    ],
    faqs: [
      { q: "Do you work with our existing codebase?", a: "Yes. We start with an audit, write an architecture decision record, and ship incremental improvements without a rewrite where possible." },
      { q: "How do you guarantee performance?", a: "Performance budgets are part of the definition of done. Lighthouse CI and real-user monitoring block regressions before they ship." },
      { q: "Can you handle SEO migrations?", a: "Yes. We map redirects, preserve URLs, ship structured data, and monitor rankings during cut-over." },
      { q: "What about accessibility?", a: "We test against WCAG 2.2 AA with both automated and manual audits, and ship VPATs when required." },
      { q: "Who owns the design system?", a: "You do. We hand over tokens, components, documentation, and Storybook so your team can extend it independently." },
    ],
    related: [
      { name: "Mobile development", href: "/technologies/mobile-development", body: "Native and cross-platform apps that share design and APIs with your web platform." },
      { name: "UI / UX design", href: "/technologies/ui-ux-design", body: "Research-led product design for web, mobile, and enterprise tooling." },
      { name: "Custom software", href: "/technologies/custom-software-development", body: "End-to-end engineering for platforms beyond the browser." },
    ],
    ctaTitle: "Ship a faster, smarter web platform with HIGAET.",
    ctaBody: "Send us your goals and constraints. We'll respond with a credible plan, a senior squad, and a delivery cadence.",
  }),

  "mobile-development": makeService({
    slug: "mobile-development",
    eyebrow: "Mobile application development",
    title: "Native-quality mobile apps, shipped on a predictable cadence.",
    subtitle: "iOS, Android, React Native, and Flutter apps engineered for performance, offline reliability, and store success.",
    metaTitle: "Mobile App Development Services — HIGAET Technologies",
    metaDescription: "Enterprise mobile app development for iOS, Android, React Native, and Flutter. Performance, offline support, and app store readiness by HIGAET Technologies.",
    heroHighlights: ["iOS, Android, React Native, Flutter", "60fps interactions, low crash rate", "Offline-first data sync", "App Store and Play Store ready"],
    overviewTitle: "Mobile experiences that earn the home screen.",
    overviewBody: "We design and engineer mobile apps users keep — fast launches, fluid interactions, reliable offline behavior, and observability you can trust. From greenfield apps to rescuing stalled builds, we own the work end-to-end.",
    benefits: [
      { title: "Higher retention", body: "Performance, onboarding, and notification strategy designed to bring users back week after week." },
      { title: "Lower crash rate", body: "Test pyramids, crash analytics, and staged rollouts catch issues before they reach the storefront." },
      { title: "Faster releases", body: "Fastlane, EAS, and store automation cut release cycles from weeks to days." },
      { title: "Shared code, native feel", body: "Cross-platform where it pays off, native modules where users will notice the difference." },
      { title: "Offline reliability", body: "Local-first data layers keep the app useful on flaky networks and unstable connections." },
      { title: "Store-ready quality", body: "Listings, screenshots, privacy disclosures, and review responses managed alongside engineering." },
    ],
    features: [
      { icon: Smartphone, title: "Native iOS & Android", body: "Swift, SwiftUI, Kotlin, and Jetpack Compose for apps that need every ounce of platform power." },
      { icon: Layers, title: "Cross-platform builds", body: "React Native and Flutter with TypeScript or Dart, sharing 80%+ of code across platforms." },
      { icon: Cloud, title: "Backend-for-frontend", body: "Lean APIs and edge functions optimized for mobile bandwidth and battery." },
      { icon: Sparkles, title: "On-device AI", body: "Core ML, MLKit, and on-device LLM integrations for private, low-latency intelligence." },
      { icon: ShieldCheck, title: "Mobile security", body: "Certificate pinning, biometrics, encrypted storage, and OWASP MASVS-aligned reviews." },
      { icon: TestTube2, title: "QA & device labs", body: "Real-device test farms, accessibility audits, and battery / performance profiling." },
    ],
    process: [
      { title: "Discover", body: "User research, store benchmarks, and a feasibility study for native vs cross-platform.", deliverables: ["Tech recommendation", "Roadmap"] },
      { title: "Design", body: "Platform-aware UX, motion, and component libraries for both iOS and Android conventions.", deliverables: ["Prototypes", "Component library"] },
      { title: "Build", body: "Two-week sprints, weekly TestFlight / internal track builds, automated test suites.", deliverables: ["Beta builds", "Test reports"] },
      { title: "Launch", body: "Store submission, privacy nutrition labels, screenshots, and phased rollout.", deliverables: ["Store listings", "Launch checklist"] },
      { title: "Operate", body: "Crash analytics, performance dashboards, and steady release trains.", deliverables: ["Dashboards", "Quarterly reviews"] },
    ],
    techGroups: [
      { title: "Native", items: ["Swift", "SwiftUI", "Kotlin", "Jetpack Compose"] },
      { title: "Cross-platform", items: ["React Native", "Expo", "Flutter", "Dart"] },
      { title: "Backend", items: ["Node.js", "GraphQL", "Firebase", "Supabase"] },
      { title: "Tooling", items: ["Fastlane", "EAS", "Sentry", "Firebase Crashlytics"] },
    ],
    faqs: [
      { q: "Native, React Native, or Flutter?", a: "We pick based on hardware needs, team skills, and roadmap. Most product apps thrive on React Native; high-performance or hardware-intensive apps go native." },
      { q: "Can you take over an existing app?", a: "Yes. We audit, stabilize, and modernize stalled or inherited apps without a rewrite where the code base is salvageable." },
      { q: "Do you handle store submissions?", a: "Yes — Apple and Google submissions, privacy disclosures, store optimization, and responses to review feedback." },
      { q: "How is offline handled?", a: "We design with local-first data, conflict resolution, and background sync so the app is useful regardless of connectivity." },
    ],
    related: [
      { name: "Web development", href: "/technologies/web-development", body: "Companion web experiences that share design, APIs, and content models." },
      { name: "UI / UX design", href: "/technologies/ui-ux-design", body: "Platform-aware mobile design that respects iOS and Android conventions." },
      { name: "QA & testing", href: "/technologies/qa-testing", body: "Device labs, automated suites, and release certification for mobile apps." },
    ],
    ctaTitle: "Launch a mobile app users actually keep — with HIGAET.",
    ctaBody: "Share your idea or stalled build. We'll respond with a delivery plan and a senior mobile squad.",
  }),

  "ui-ux-design": makeService({
    slug: "ui-ux-design",
    eyebrow: "Product design",
    title: "Product design that turns complex software into clear outcomes.",
    subtitle: "Research, UX, UI, and design systems for SaaS, mobile, enterprise tools, and AI-first products.",
    metaTitle: "UI / UX Design Services — HIGAET Technologies",
    metaDescription: "Product design, UX research, UI design, and design systems for SaaS, mobile, and enterprise software. Conversion- and accessibility-first by HIGAET.",
    heroHighlights: ["Research before pixels", "Design systems you can scale", "Accessible by default (WCAG 2.2)", "Engineering-ready handoff"],
    overviewTitle: "Design teams that ship — not just specs.",
    overviewBody: "We pair senior product designers with researchers and front-end engineers, so what you approve in Figma is what ships in production. Every project starts with the user and ends with measurable outcomes.",
    benefits: [
      { title: "Validated decisions", body: "Research, prototypes, and usability testing reduce the risk of building the wrong thing." },
      { title: "Consistent product surface", body: "Design systems eliminate UI drift across teams, products, and platforms." },
      { title: "Accessible to everyone", body: "Inclusive design and WCAG 2.2 AA baked into components, not retrofitted." },
      { title: "Faster engineering", body: "Token-driven design and detailed handoff cut implementation time and rework." },
      { title: "Conversion wins", body: "Funnel reviews, micro-copy, and CRO experiments lift activation and retention." },
      { title: "Brand cohesion", body: "Visual identity, motion, and content guidelines align with the broader HIGAET brand stack." },
    ],
    features: [
      { icon: PenTool, title: "Product & UX design", body: "Information architecture, flows, wireframes, and high-fidelity UI for web and mobile." },
      { icon: Brush, title: "Design systems", body: "Tokens, components, documentation, and Storybook integrations engineering teams love." },
      { icon: Users, title: "UX research", body: "Interviews, usability tests, surveys, and competitive analysis grounded in your KPIs." },
      { icon: Sparkles, title: "AI-first UX", body: "Patterns for chat, agents, copilots, and generative interfaces — with safety and clarity built in." },
      { icon: ShieldCheck, title: "Accessibility", body: "WCAG 2.2 AA audits, remediations, and VPAT documentation for procurement." },
      { icon: BarChart3, title: "Conversion design", body: "Funnel diagnostics, copy experiments, and design A/B tests that move the metric." },
    ],
    process: [
      { title: "Discover", body: "Stakeholder interviews, JTBD, and analytics review to frame the real problem.", deliverables: ["Insight report", "Opportunity map"] },
      { title: "Define", body: "User flows, information architecture, and content model agreed with stakeholders.", deliverables: ["IA", "Flows"] },
      { title: "Design", body: "High-fidelity UI, motion, and component library with prototypes for testing.", deliverables: ["UI", "Prototype"] },
      { title: "Validate", body: "Usability testing, accessibility audits, and stakeholder reviews.", deliverables: ["Test reports", "Iteration plan"] },
      { title: "Handover", body: "Tokens, components, Storybook, and engineering pairing during build.", deliverables: ["Design system", "Handoff docs"] },
    ],
    techGroups: [
      { title: "Design", items: ["Figma", "FigJam", "Framer", "Principle"] },
      { title: "Research", items: ["Maze", "Dovetail", "Lookback", "Hotjar"] },
      { title: "Systems", items: ["Tokens Studio", "Storybook", "Chromatic"] },
      { title: "Front-end", items: ["React", "Tailwind", "Radix", "Shadcn"] },
    ],
    faqs: [
      { q: "Can you work without an internal design team?", a: "Yes. We embed design leadership and execution, then build your internal team over time if you want." },
      { q: "Do you do design-only engagements?", a: "Yes. Many clients start with discovery and design, then bring in our engineering squads — or theirs — to build." },
      { q: "How do you measure design success?", a: "Activation, retention, task success, accessibility scores, and engineering velocity — all agreed up front." },
      { q: "Can you audit an existing product?", a: "Yes. UX, accessibility, and conversion audits with prioritized, costed recommendations." },
    ],
    related: [
      { name: "Web development", href: "/technologies/web-development", body: "Engineering teams who turn the design system into shipped, performant code." },
      { name: "Mobile development", href: "/technologies/mobile-development", body: "Platform-aware mobile UI implemented on iOS, Android, and cross-platform stacks." },
      { name: "AI solutions", href: "/technologies/ai-solutions", body: "Design and engineering for chat, agents, and generative UX." },
    ],
    ctaTitle: "Design products users understand — with HIGAET.",
    ctaBody: "Tell us about your product and users. We'll respond with a research and design plan.",
  }),

  "devops": makeService({
    slug: "devops",
    eyebrow: "DevOps & SRE",
    title: "DevOps that makes shipping safe, fast, and boring.",
    subtitle: "CI/CD, infrastructure as code, Kubernetes, observability, and SRE practices for teams that need to move every day.",
    metaTitle: "DevOps & SRE Services — HIGAET Technologies",
    metaDescription: "Enterprise DevOps and SRE: CI/CD, IaC, Kubernetes, observability, on-call. Ship faster with HIGAET Technologies.",
    heroHighlights: ["CI/CD that runs in minutes", "Infra as code, fully versioned", "SLOs, dashboards, and runbooks", "On-call coverage 24/7"],
    overviewTitle: "Engineering velocity, without the firefighting.",
    overviewBody: "We modernize platforms so engineering teams ship multiple times a day with confidence. Pipelines, infrastructure, observability, and on-call practices are designed to reduce risk and free up engineering time.",
    benefits: [
      { title: "Shorter lead time", body: "From commit to production in minutes, not days, with automated quality gates." },
      { title: "Lower change-fail rate", body: "Progressive delivery, automated tests, and instant rollback reduce risky releases." },
      { title: "Predictable costs", body: "FinOps practices, right-sized clusters, and reserved capacity cut cloud bills." },
      { title: "Resilience by default", body: "Multi-AZ, autoscaling, chaos drills, and tested disaster recovery." },
      { title: "Developer happiness", body: "Self-service environments and golden paths so engineers focus on product, not infra." },
      { title: "Audit-ready", body: "Immutable infrastructure, signed builds, and provenance for SOC 2 and ISO controls." },
    ],
    features: [
      { icon: GitBranch, title: "CI/CD pipelines", body: "GitHub Actions, GitLab CI, Argo CD, and progressive delivery with feature flags." },
      { icon: Server, title: "Kubernetes & containers", body: "EKS, AKS, GKE, and managed clusters with Helm, Kustomize, and platform engineering practices." },
      { icon: Code2, title: "Infrastructure as code", body: "Terraform, Pulumi, and Crossplane modules with automated drift detection." },
      { icon: LineChart, title: "Observability", body: "Logs, metrics, traces, and SLOs in Datadog, Grafana, New Relic, or open-source stacks." },
      { icon: ShieldCheck, title: "DevSecOps", body: "SAST, DAST, SBOMs, secrets scanning, and policy-as-code in every pipeline." },
      { icon: Repeat, title: "SRE & on-call", body: "Runbooks, incident response, blameless postmortems, and on-call rotations." },
    ],
    process: [
      { title: "Assess", body: "Platform audit, value-stream mapping, and DORA metrics baseline.", deliverables: ["Audit", "Baseline metrics"] },
      { title: "Design", body: "Reference architecture, golden paths, and platform engineering blueprint.", deliverables: ["Architecture", "Roadmap"] },
      { title: "Implement", body: "Pipelines, infrastructure, observability, and policy controls rolled out in waves.", deliverables: ["IaC modules", "Pipelines"] },
      { title: "Enable", body: "Workshops, paved-road templates, and internal docs so teams adopt the platform.", deliverables: ["Training", "Templates"] },
      { title: "Operate", body: "Continuous improvement, FinOps reviews, and 24/7 on-call coverage.", deliverables: ["Dashboards", "Runbooks"] },
    ],
    techGroups: [
      { title: "Pipelines", items: ["GitHub Actions", "GitLab CI", "Argo CD", "Flux"] },
      { title: "Infra", items: ["Terraform", "Pulumi", "Crossplane", "Ansible"] },
      { title: "Containers", items: ["Kubernetes", "EKS", "AKS", "GKE", "Helm"] },
      { title: "Observability", items: ["Datadog", "Grafana", "Prometheus", "OpenTelemetry"] },
      { title: "Security", items: ["Snyk", "Trivy", "OPA", "Vault"] },
    ],
    faqs: [
      { q: "Do we need Kubernetes?", a: "Not always. We start from your goals and team size; managed PaaS or serverless often beats Kubernetes for small teams." },
      { q: "Can you take over our existing platform?", a: "Yes — incremental modernization with no big-bang migrations, and full handover documentation." },
      { q: "Do you cover security?", a: "Yes. DevSecOps practices, SBOMs, secrets management, and SOC 2-aligned controls are part of every engagement." },
      { q: "What about cost?", a: "We bake FinOps in: right-sizing, autoscaling, reserved capacity, and quarterly cost reviews." },
    ],
    related: [
      { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud foundations, landing zones, and migrations underpinning the platform." },
      { name: "QA & testing", href: "/technologies/qa-testing", body: "Test automation that turns CI green into a meaningful release signal." },
      { name: "Custom software", href: "/technologies/custom-software-development", body: "The product engineering squads who ship on top of the platform." },
    ],
    ctaTitle: "Make shipping boring — with HIGAET DevOps.",
    ctaBody: "Tell us about your platform pain. We'll respond with a platform audit and modernization plan.",
  }),

  "qa-testing": makeService({
    slug: "qa-testing",
    eyebrow: "Quality engineering",
    title: "Quality engineering that ships confidence, not just bug counts.",
    subtitle: "Test strategy, automation, performance, accessibility, and security testing baked into the SDLC.",
    metaTitle: "QA & Software Testing Services — HIGAET Technologies",
    metaDescription: "Quality engineering, test automation, performance, accessibility, and security testing for enterprise software. By HIGAET Technologies.",
    heroHighlights: ["Test pyramid on every team", "Automation across web, mobile, API", "Accessibility & performance baked in", "Security testing in CI"],
    overviewTitle: "Test strategy that earns trust in every release.",
    overviewBody: "We design quality engineering practices that match your risk profile — from regulated finance to fast-moving SaaS. Automation, exploratory testing, and quality coaching combine to make releases predictable.",
    benefits: [
      { title: "Fewer escaped defects", body: "Risk-based test strategy and CI gates catch issues long before customers do." },
      { title: "Faster releases", body: "Automation replaces slow manual cycles so teams ship daily, not quarterly." },
      { title: "Audit-ready coverage", body: "Traceability from requirements to tests for ISO, SOC 2, and regulatory audits." },
      { title: "Accessibility compliance", body: "WCAG 2.2 AA testing and VPATs for enterprise procurement." },
      { title: "Better performance", body: "Load, stress, and soak testing tied to clear SLOs and capacity plans." },
      { title: "Engineering coaching", body: "We train your team in TDD, contract testing, and quality ownership." },
    ],
    features: [
      { icon: TestTube2, title: "Test automation", body: "Playwright, Cypress, Appium, REST Assured, and Postman across web, mobile, and APIs." },
      { icon: BarChart3, title: "Performance testing", body: "k6, JMeter, and Gatling tied to SLOs, load profiles, and capacity planning." },
      { icon: ShieldCheck, title: "Security testing", body: "OWASP-aligned testing, SAST/DAST in CI, and penetration testing for high-risk releases." },
      { icon: Users, title: "Accessibility testing", body: "Automated and manual WCAG 2.2 audits, screen-reader testing, and VPATs." },
      { icon: Workflow, title: "Manual & exploratory", body: "Structured exploratory sessions, charters, and bug bashes for complex flows." },
      { icon: Repeat, title: "Continuous quality", body: "Quality dashboards, flake tracking, and test maintenance plans baked into delivery." },
    ],
    process: [
      { title: "Assess", body: "Risk profile, current coverage, and quality maturity assessment.", deliverables: ["Audit", "Strategy"] },
      { title: "Plan", body: "Test pyramid, environments, and tooling roadmap agreed with engineering.", deliverables: ["Strategy", "Roadmap"] },
      { title: "Automate", body: "Build automation suites, integrate with CI, and add quality gates.", deliverables: ["Test suites", "CI gates"] },
      { title: "Validate", body: "Performance, security, and accessibility test runs against agreed SLOs.", deliverables: ["Reports", "Action plan"] },
      { title: "Operate", body: "Continuous test maintenance, flake reduction, and quality coaching.", deliverables: ["Dashboards", "Coaching"] },
    ],
    techGroups: [
      { title: "Web & API", items: ["Playwright", "Cypress", "Postman", "REST Assured"] },
      { title: "Mobile", items: ["Appium", "Detox", "XCUITest", "Espresso"] },
      { title: "Performance", items: ["k6", "JMeter", "Gatling", "Locust"] },
      { title: "Security", items: ["OWASP ZAP", "Burp Suite", "Snyk", "Semgrep"] },
      { title: "Accessibility", items: ["axe-core", "Pa11y", "NVDA", "VoiceOver"] },
    ],
    faqs: [
      { q: "Can you build a QA team from scratch?", a: "Yes. We define strategy, hire and train, and hand over to an internal quality leader." },
      { q: "What if our automation is flaky?", a: "We stabilize, refactor, and apply flake-management practices, then build maintainability into every new test." },
      { q: "Do you do performance or security testing?", a: "Both — under one umbrella with engineering and DevOps, so issues are fixed where they belong." },
    ],
    related: [
      { name: "DevOps & SRE", href: "/technologies/devops", body: "The CI/CD pipelines that turn quality signals into safer releases." },
      { name: "Custom software", href: "/technologies/custom-software-development", body: "Product engineering squads with built-in quality engineering." },
      { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud foundations that make performance and resilience testing meaningful." },
    ],
    ctaTitle: "Ship with confidence — partner with HIGAET QA.",
    ctaBody: "Tell us where quality hurts. We'll respond with a focused strategy and team.",
  }),

  "data-engineering": makeService({
    slug: "data-engineering",
    eyebrow: "Data engineering & BI",
    title: "Data platforms that fuel analytics, AI, and operations.",
    subtitle: "Modern data stacks, real-time pipelines, lakehouses, and BI built for trustworthy, decision-ready data.",
    metaTitle: "Data Engineering & BI Services — HIGAET Technologies",
    metaDescription: "Modern data platforms, ETL/ELT, lakehouse, real-time streaming, and BI by HIGAET Technologies. AI-ready, governed, decision-grade data.",
    heroHighlights: ["Modern data stack (dbt, Snowflake, BigQuery)", "Streaming pipelines with Kafka / Kinesis", "Governance and lineage end-to-end", "AI-ready feature stores"],
    overviewTitle: "Decision-grade data, ready for AI.",
    overviewBody: "We build data platforms that engineers, analysts, and AI systems can all trust. From ingestion to BI, from feature stores to embedded analytics — designed with governance, lineage, and cost discipline.",
    benefits: [
      { title: "One source of truth", body: "Unified models, dbt-based transformations, and tested data products end the metric arguments." },
      { title: "Real-time insight", body: "Streaming pipelines bring operations, finance, and product onto live dashboards." },
      { title: "AI-ready foundations", body: "Feature stores, vector indices, and clean metadata accelerate ML and GenAI projects." },
      { title: "Governed & compliant", body: "Lineage, masking, and access controls aligned to GDPR, HIPAA, and internal policy." },
      { title: "Lower cloud spend", body: "Warehouse FinOps, query tuning, and storage tiering control runaway data bills." },
      { title: "Self-service analytics", body: "Semantic layers and curated marts let business teams answer their own questions." },
    ],
    features: [
      { icon: Database, title: "Lakehouse & warehouses", body: "Snowflake, BigQuery, Databricks, Redshift, and Iceberg-based open lakehouses." },
      { icon: GitBranch, title: "ELT & transformation", body: "dbt, Airflow, Dagster, and Prefect with tested, version-controlled models." },
      { icon: Network, title: "Streaming pipelines", body: "Kafka, Kinesis, Flink, and Materialize for real-time analytics and operations." },
      { icon: BarChart3, title: "BI & dashboards", body: "Looker, Power BI, Metabase, Superset — with semantic models and KPI catalogs." },
      { icon: Sparkles, title: "ML & feature stores", body: "Feature platforms, vector databases, and pipelines designed for ML and GenAI." },
      { icon: ShieldCheck, title: "Governance", body: "Lineage, catalogs, masking, and access controls aligned to your compliance posture." },
    ],
    process: [
      { title: "Discover", body: "Use-case interviews, source-system mapping, and data quality baseline.", deliverables: ["Use-case backlog", "Audit"] },
      { title: "Design", body: "Reference architecture, data contracts, and governance model.", deliverables: ["Architecture", "Contracts"] },
      { title: "Build", body: "Pipelines, models, and BI assets shipped in iterative releases.", deliverables: ["Pipelines", "Models", "Dashboards"] },
      { title: "Operate", body: "SLAs on freshness, quality, and cost — with on-call coverage.", deliverables: ["SLAs", "Dashboards"] },
      { title: "Enable", body: "Training, documentation, and analytics engineering enablement for your teams.", deliverables: ["Docs", "Training"] },
    ],
    techGroups: [
      { title: "Warehouses", items: ["Snowflake", "BigQuery", "Databricks", "Redshift"] },
      { title: "Transformation", items: ["dbt", "Airflow", "Dagster", "Prefect"] },
      { title: "Streaming", items: ["Kafka", "Kinesis", "Flink", "Materialize"] },
      { title: "BI", items: ["Looker", "Power BI", "Metabase", "Superset"] },
      { title: "ML & AI", items: ["Feature stores", "Vector DBs", "MLflow", "Vertex AI"] },
    ],
    faqs: [
      { q: "Do we need a lakehouse or warehouse?", a: "We assess data volumes, latency, and BI needs. Most mid-market teams thrive on a managed warehouse; lakehouse fits high-volume or ML-heavy use cases." },
      { q: "Can you fix our existing pipelines?", a: "Yes. We audit, stabilize, and modernize without a big-bang migration where the existing platform is workable." },
      { q: "How do you handle PII?", a: "Tokenization, masking, RBAC, and lineage — aligned with GDPR, HIPAA, or industry rules." },
      { q: "Do you support GenAI use cases?", a: "Yes. Feature stores, vector indexes, retrieval pipelines, and evaluation harnesses are part of the offer." },
    ],
    related: [
      { name: "AI solutions", href: "/technologies/ai-solutions", body: "Applied AI built on the data platform we deliver." },
      { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud foundations and FinOps under your data platform." },
      { name: "DevOps & SRE", href: "/technologies/devops", body: "Platform and pipeline reliability for data-intensive systems." },
    ],
    ctaTitle: "Build a data platform you can bet on — with HIGAET.",
    ctaBody: "Tell us about your data goals. We'll respond with a reference architecture and roadmap.",
  }),

  "digital-transformation": makeService({
    slug: "digital-transformation",
    eyebrow: "Digital transformation",
    title: "Modernize the business — not just the tech stack.",
    subtitle: "Strategy, platform modernization, automation, and change management for enterprises ready to operate differently.",
    metaTitle: "Digital Transformation Services — HIGAET Technologies",
    metaDescription: "Enterprise digital transformation: strategy, modernization, automation, AI, and change management. By HIGAET Technologies.",
    heroHighlights: ["Strategy tied to P&L outcomes", "Modernization without rewrites where possible", "AI and automation woven in", "Change management that sticks"],
    overviewTitle: "Transformation, measured in business outcomes.",
    overviewBody: "We pair business strategists with engineers, designers, and AI specialists so digital change actually lands. Roadmaps are tied to KPIs, modernization is incremental, and people are part of the design from day one.",
    benefits: [
      { title: "P&L-linked outcomes", body: "Every program ties to revenue, cost, risk, or experience metrics — not vanity dashboards." },
      { title: "Lower legacy drag", body: "Strangler-fig migrations cut total cost of ownership without halting the business." },
      { title: "Operational AI", body: "Automation and AI woven into core processes, not isolated pilots." },
      { title: "Engaged workforce", body: "Change management, training, and design partnerships build adoption you can sustain." },
      { title: "Faster decision cycles", body: "Modern data and BI accelerate the OODA loop across functions." },
      { title: "Compliance built in", body: "Privacy, security, and audit controls designed into the new operating model." },
    ],
    features: [
      { icon: LineChart, title: "Digital strategy", body: "Operating model design, capability maps, and a portfolio of funded initiatives." },
      { icon: Layers, title: "Legacy modernization", body: "Strangler-fig migrations, API enablement, and platform replatforms with minimal disruption." },
      { icon: Workflow, title: "Process automation", body: "BPM, RPA, and AI agents removing repetitive work across operations." },
      { icon: Sparkles, title: "Applied AI", body: "Embedded copilots, decision support, and document intelligence across the value chain." },
      { icon: Users, title: "Change & enablement", body: "Org design, communications, and training that bring people with the change." },
      { icon: ShieldCheck, title: "Risk & governance", body: "Security, privacy, and compliance built into the target state from day one." },
    ],
    process: [
      { title: "Diagnose", body: "Discovery sprints across business and tech surfacing real opportunities and risks.", deliverables: ["Diagnosis", "Opportunity portfolio"] },
      { title: "Design", body: "Target operating model, capability roadmap, and initial business cases.", deliverables: ["Target model", "Business cases"] },
      { title: "Mobilize", body: "Stand up squads, governance, and a delivery cadence the org can sustain.", deliverables: ["Squad model", "Governance"] },
      { title: "Deliver", body: "Iterative releases of platform, process, and AI changes against agreed KPIs.", deliverables: ["Releases", "KPIs"] },
      { title: "Embed", body: "Training, change management, and operating-model handover.", deliverables: ["Playbooks", "Training"] },
    ],
    techGroups: [
      { title: "Strategy", items: ["Operating model", "Capability maps", "Portfolio design"] },
      { title: "Platforms", items: ["Cloud", "API platforms", "Event streams"] },
      { title: "Automation", items: ["BPM", "RPA", "AI agents"] },
      { title: "Data & AI", items: ["Lakehouses", "MLOps", "GenAI"] },
    ],
    faqs: [
      { q: "Where do most transformations fail?", a: "On change management. We invest as much in adoption, governance, and capability building as in code and platforms." },
      { q: "Do we need to rewrite legacy systems?", a: "Rarely. Strangler-fig patterns, API enablement, and selective replatforming usually outperform big-bang rewrites." },
      { q: "How do you measure success?", a: "Outcome KPIs tied to P&L — cost-to-serve, revenue per employee, time-to-market, NPS — agreed up front." },
    ],
    related: [
      { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud foundations underpinning the modernized platform." },
      { name: "AI solutions", href: "/technologies/ai-solutions", body: "Applied AI woven into modernized business processes." },
      { name: "Custom software", href: "/technologies/custom-software-development", body: "Squads that build the new platforms and integrations." },
    ],
    ctaTitle: "Modernize with measurable outcomes — with HIGAET.",
    ctaBody: "Share your transformation goals. We'll respond with a diagnosis and program plan.",
  }),

  "dedicated-team": makeService({
    slug: "dedicated-team",
    eyebrow: "Dedicated development team",
    title: "Dedicated engineering squads, embedded into your roadmap.",
    subtitle: "Senior, long-tenured teams who learn your domain, integrate with your processes, and ship continuously.",
    metaTitle: "Dedicated Development Team Services — HIGAET Technologies",
    metaDescription: "Hire dedicated software development teams. Senior engineers, low churn, full-stack, AI-ready. By HIGAET Technologies.",
    heroHighlights: ["Senior engineers, no rotating juniors", "Embedded in your tools and process", "Two-week sprint cadence", "Scale up or down quarterly"],
    overviewTitle: "An engineering team that thinks like part of your business.",
    overviewBody: "We assemble dedicated squads — engineering, design, QA, DevOps, and product — that integrate into your tools, ceremonies, and roadmap. You get the focus of an in-house team without the hiring drag.",
    benefits: [
      { title: "Lower hiring friction", body: "Skip months of recruiting; we staff senior squads from our talent pipeline within weeks." },
      { title: "Predictable cost", body: "Monthly rates with no severance, no benefits overhead, and no idle bench time." },
      { title: "Institutional memory", body: "Long tenures and clean documentation mean the team's knowledge stays with your business." },
      { title: "Flexible scale", body: "Add or release roles each quarter as the roadmap evolves — no painful restructures." },
      { title: "Senior throughput", body: "Senior-heavy teams ship more in fewer hands and need less hand-holding." },
      { title: "Full-stack capability", body: "Engineering, design, QA, DevOps, and AI under one roof — no vendor chain." },
    ],
    features: [
      { icon: Users, title: "Dedicated squads", body: "Tech leads, full-stack engineers, designers, QA, and DevOps assembled to fit your roadmap." },
      { icon: Workflow, title: "Embedded in your process", body: "Slack, Jira, Linear, GitHub — your tools, your ceremonies, our delivery rigor." },
      { icon: Repeat, title: "Two-week cadence", body: "Sprint planning, demos, retros, and clear KPIs from week one." },
      { icon: ShieldCheck, title: "IP & security", body: "NDAs, IP assignment, audit logging, and SOC 2-aligned controls on every squad." },
      { icon: Sparkles, title: "AI-augmented", body: "Squads use copilots, evaluation harnesses, and internal AI tooling responsibly." },
      { icon: GraduationCap, title: "Talent pipeline", body: "Engineers trained through the HIGAET Academy — senior, vetted, low churn." },
    ],
    process: [
      { title: "Scope", body: "Roadmap workshop, role mix, and squad design agreed with your leadership.", deliverables: ["Squad plan", "Engagement model"] },
      { title: "Stand up", body: "Engineers onboarded into your tools, codebase, and ceremonies in 2–4 weeks.", deliverables: ["Team", "Onboarding plan"] },
      { title: "Deliver", body: "Sprints, demos, and KPI tracking with full transparency into velocity and quality.", deliverables: ["Releases", "KPI dashboards"] },
      { title: "Adapt", body: "Quarterly roadmap reviews and squad composition tweaks as priorities shift.", deliverables: ["Roadmap review", "Team adjustments"] },
      { title: "Sustain", body: "Long-tenure squads keep institutional knowledge so velocity compounds.", deliverables: ["Quarterly reports"] },
    ],
    techGroups: [
      { title: "Engineering", items: ["React", "Next.js", "Node.js", "Python", "Java", ".NET", "Go"] },
      { title: "Mobile", items: ["React Native", "Flutter", "Swift", "Kotlin"] },
      { title: "Data & AI", items: ["dbt", "Airflow", "LangChain", "OpenAI"] },
      { title: "DevOps", items: ["Kubernetes", "Terraform", "GitHub Actions"] },
    ],
    faqs: [
      { q: "How fast can a squad start?", a: "Typically 2–4 weeks from contract to first sprint, depending on roles and security onboarding." },
      { q: "Who owns the code?", a: "You do. Source, IP, and infrastructure as code transfer to you under the master services agreement." },
      { q: "Can we interview engineers?", a: "Yes. We propose a shortlist; you interview and approve the squad before it starts." },
      { q: "What's the typical engagement length?", a: "Most squads run 12+ months. Short engagements work for discovery sprints and rescue missions." },
    ],
    related: [
      { name: "Custom software", href: "/technologies/custom-software-development", body: "Outcome-based delivery when you'd rather hand over a problem than manage a team." },
      { name: "AI solutions", href: "/technologies/ai-solutions", body: "Applied AI squads embedded in your product team." },
      { name: "DevOps & SRE", href: "/technologies/devops", body: "Platform squads that pair with your engineering team." },
    ],
    ctaTitle: "Stand up a dedicated HIGAET squad in weeks.",
    ctaBody: "Tell us your roadmap and roles. We'll respond with a shortlist and engagement plan.",
  }),
};
