import {
  Activity,
  BarChart3,
  Boxes,
  Building2,
  Cable,
  Cloud,
  CloudCog,
  Code2,
  Compass,
  Database,
  GitBranch,
  GraduationCap,
  Headset,
  Heart,
  Landmark,
  Layers,
  LifeBuoy,
  LineChart,
  Lock,
  Network,
  Package,
  PieChart,
  Plug,
  RefreshCw,
  Repeat,
  Rocket,
  Server,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Truck,
  Users,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";
import type { ServiceDetailContent } from "@/components/site/ServiceDetailPage";

const COMMON_INDUSTRIES: ServiceDetailContent["industries"] = [
  { icon: GraduationCap, name: "Education", body: "Learning platforms, admissions workflows, faculty tools, and student-facing portals." },
  { icon: Heart, name: "Healthcare", body: "Patient portals, clinical workflows, and decision support built around privacy and uptime." },
  { icon: Landmark, name: "Finance & FinTech", body: "Core banking, payments, KYC, risk, and embedded finance with strict security baselines." },
  { icon: ShoppingBag, name: "Retail & E-commerce", body: "Storefronts, marketplaces, fulfillment integrations, and AI personalization." },
  { icon: Truck, name: "Logistics", body: "Ops dashboards, IoT telemetry, route optimization, and warehouse automation." },
  { icon: Building2, name: "Enterprise & SaaS", body: "Internal platforms, partner portals, and multi-tenant SaaS products at scale." },
];

const COMMON_WHY_US: ServiceDetailContent["whyUs"] = [
  { icon: Users, title: "Senior squads, low churn", body: "We staff with engineers trained through the HIGAET Academy talent pipeline — no rotating juniors." },
  { icon: Zap, title: "Product-minded delivery", body: "Squads obsess over user outcomes and KPIs, not just ticket throughput or hours billed." },
  { icon: Lock, title: "Enterprise governance", body: "NDAs, IP assignment, audit logs, and SOC 2-aligned controls on every engagement." },
  { icon: Layers, title: "Full-stack capability", body: "Strategy, design, engineering, AI, data, and SRE — one accountable team, not a chain of vendors." },
  { icon: Sparkles, title: "AI in the DNA", body: "Every project considers where intelligent automation creates leverage for users and operators." },
  { icon: Rocket, title: "Skin in the game", body: "We co-build with select partners, sharing both delivery risk and long-term upside." },
];

function make(input: Omit<ServiceDetailContent, "brand" | "path" | "industries" | "whyUs"> & {
  industries?: ServiceDetailContent["industries"];
  whyUs?: ServiceDetailContent["whyUs"];
}): ServiceDetailContent {
  return {
    brand: "tech",
    path: `/technologies/${input.slug}`,
    industries: input.industries ?? COMMON_INDUSTRIES,
    whyUs: input.whyUs ?? COMMON_WHY_US,
    ...input,
  };
}

export const SERVICES_EXTRA: Record<string, ServiceDetailContent> = {
  "enterprise-software": make({
    slug: "enterprise-software",
    eyebrow: "Enterprise software development",
    title: "Enterprise software that holds up to scale, audit, and reality.",
    subtitle: "Mission-critical platforms for large organizations — built for security, performance, and the next ten years of change.",
    metaTitle: "Enterprise Software Development Services — HIGAET Technologies",
    metaDescription: "Enterprise software development with security, scalability, and compliance built in. Mission-critical platforms by HIGAET Technologies.",
    heroHighlights: ["SOC 2, ISO 27001, HIPAA aligned", "SSO, RBAC, audit logs by default", "99.9%+ availability targets", "Decade-long maintainability"],
    overviewTitle: "Platforms that big organizations bet on.",
    overviewBody: "We design and build enterprise-grade platforms — ERPs, internal tooling, partner portals, regulated workflows — with the controls, observability, and governance large organizations demand.",
    benefits: [
      { title: "Compliance, baked in", body: "SOC 2, ISO 27001, HIPAA, and PCI-DSS controls designed into the platform — not retrofitted." },
      { title: "Predictable scale", body: "Capacity planning, load testing, and elastic infrastructure ready for enterprise growth." },
      { title: "Audit-ready", body: "Lineage, change history, and access logs satisfy internal audit and regulators alike." },
      { title: "Low TCO", body: "Modular architecture and automated tests cut the cost of every future change." },
      { title: "Procurement-friendly", body: "Security questionnaires, DPIAs, and VPATs handled by our delivery team." },
      { title: "Long-term partner", body: "Decade-long platforms, supported by squads that stay." },
    ],
    features: [
      { icon: Boxes, title: "ERP & operational platforms", body: "Custom ERPs, supply chain systems, and back-office platforms tailored to your operating model." },
      { icon: ShieldCheck, title: "Identity & access", body: "SSO (SAML, OIDC), RBAC, ABAC, JIT provisioning, and SCIM directory sync." },
      { icon: Workflow, title: "Workflow & approvals", body: "BPM, approval chains, and case management for regulated processes." },
      { icon: Server, title: "High-availability infra", body: "Multi-region, multi-AZ designs with tested DR and clear RTO/RPO targets." },
      { icon: Activity, title: "Observability", body: "Metrics, traces, logs, and SLOs reporting straight to your enterprise tooling." },
      { icon: Code2, title: "Integration first", body: "REST, GraphQL, gRPC, and event-driven integrations with the rest of your enterprise stack." },
    ],
    process: [
      { title: "Diagnose", body: "Capability map, current-state audit, and risk assessment.", deliverables: ["Audit", "Risk register"] },
      { title: "Architect", body: "Target architecture, ADRs, and security model agreed with enterprise architecture.", deliverables: ["Architecture", "ADRs"] },
      { title: "Build", body: "Senior squads ship in two-week sprints with code review, automated tests, and demos.", deliverables: ["Working software", "Test suite"] },
      { title: "Certify", body: "Security, performance, and accessibility testing; UAT and stakeholder sign-off.", deliverables: ["Test reports", "Sign-off"] },
      { title: "Operate", body: "24/7 SRE, incident response, and continuous improvement against agreed SLAs.", deliverables: ["SLAs", "Runbooks"] },
    ],
    techGroups: [
      { title: "Backend", items: ["Java", ".NET", "Node.js", "Python", "Go"] },
      { title: "Frontend", items: ["React", "Angular", "TypeScript"] },
      { title: "Data", items: ["PostgreSQL", "Oracle", "SQL Server", "Snowflake"] },
      { title: "Integration", items: ["Kafka", "MuleSoft", "Apigee", "Camunda"] },
      { title: "Cloud", items: ["AWS", "Azure", "GCP", "Private cloud"] },
    ],
    faqs: [
      { q: "Can you work alongside our enterprise architecture team?", a: "Yes — our architects integrate with EA, security, and platform teams from day one and deliver against your reference architecture." },
      { q: "How do you handle compliance?", a: "We design controls (access, logging, encryption, change management) to map directly to your SOC 2, ISO 27001, or regulator requirements." },
      { q: "Can you take over an inherited platform?", a: "Yes. We audit, stabilize, and modernize without big-bang rewrites where the codebase is workable." },
      { q: "What about long-term support?", a: "Most enterprise engagements run multi-year, with a dedicated squad providing build + run under agreed SLAs." },
    ],
    related: [
      { name: "Legacy modernization", href: "/technologies/legacy-modernization", body: "Strangle and replace legacy systems without halting the business." },
      { name: "System integration", href: "/technologies/system-integration", body: "Connect your enterprise stack with event-driven, API-first integration." },
      { name: "IT consulting", href: "/technologies/it-consulting", body: "Strategy, architecture, and operating-model design for enterprise IT." },
    ],
    ctaTitle: "Build enterprise software you can bet on — with HIGAET.",
    ctaBody: "Tell us about your platform. We'll respond with an architecture sketch and squad plan.",
  }),

  "cloud-migration": make({
    slug: "cloud-migration",
    eyebrow: "Cloud migration",
    title: "Cloud migration without downtime, drama, or surprise bills.",
    subtitle: "Assessment, replatforming, and modernization to AWS, Azure, and Google Cloud — with FinOps from day one.",
    metaTitle: "Cloud Migration Services — HIGAET Technologies",
    metaDescription: "Enterprise cloud migration to AWS, Azure, and GCP. Assessment, replatforming, modernization, and FinOps by HIGAET Technologies.",
    heroHighlights: ["6 Rs assessment per workload", "Landing zones and guardrails", "FinOps from day one", "Zero-downtime cutovers"],
    overviewTitle: "Migrate with a plan — and a steady hand.",
    overviewBody: "We assess every workload against the 6 Rs (rehost, replatform, refactor, repurchase, retire, retain), stand up secure landing zones, and execute migrations in waves with rollback plans and clear KPIs.",
    benefits: [
      { title: "Lower run cost", body: "Right-sized compute, reserved capacity, and storage tiering cut bills from the first month." },
      { title: "Faster innovation", body: "Cloud-native services unlock managed databases, AI, and edge capabilities you can build on." },
      { title: "Resilience", body: "Multi-AZ and multi-region designs deliver SLAs your data centers can't match." },
      { title: "Security uplift", body: "Modern identity, encryption, and audit baselines come with the move — not as a phase 2." },
      { title: "Talent leverage", body: "Managed services free your team from patching to focus on product." },
      { title: "Sustainability", body: "Hyperscaler efficiency and Scope 3 reporting support your ESG commitments." },
    ],
    features: [
      { icon: Compass, title: "Discovery & 6 Rs", body: "Workload inventory, dependency mapping, and a costed migration wave plan." },
      { icon: ShieldCheck, title: "Landing zones", body: "Account, network, IAM, and guardrail baselines aligned to Well-Architected and security best practice." },
      { icon: CloudCog, title: "Replatform & refactor", body: "Containers, managed databases, and serverless where they unlock value." },
      { icon: Database, title: "Data migration", body: "Schema, ETL, and CDC migrations with zero or near-zero downtime." },
      { icon: PieChart, title: "FinOps", body: "Tagging, showback, rightsizing, and reserved-capacity strategy from week one." },
      { icon: Activity, title: "Cutover & hypercare", body: "Wave-based cutovers, rollback plans, and 24/7 hypercare for high-stakes moves." },
    ],
    process: [
      { title: "Assess", body: "Workload inventory, 6 Rs, business case, and migration wave plan.", deliverables: ["Business case", "Wave plan"] },
      { title: "Foundation", body: "Landing zone, guardrails, identity, and CI/CD ready for production.", deliverables: ["Landing zone", "IaC modules"] },
      { title: "Migrate", body: "Wave-by-wave migration with automated testing, observability, and cutover runbooks.", deliverables: ["Migrated workloads", "Runbooks"] },
      { title: "Optimize", body: "FinOps reviews, rightsizing, and reliability tuning post-migration.", deliverables: ["FinOps report", "Reliability plan"] },
      { title: "Operate", body: "Managed services, SRE, and continuous modernization roadmap.", deliverables: ["Dashboards", "Quarterly reviews"] },
    ],
    techGroups: [
      { title: "Cloud", items: ["AWS", "Azure", "Google Cloud"] },
      { title: "IaC", items: ["Terraform", "Pulumi", "CloudFormation"] },
      { title: "Migration", items: ["AWS DMS", "Azure Migrate", "Velostrata", "CloudEndure"] },
      { title: "Containers", items: ["Kubernetes", "EKS", "AKS", "GKE"] },
      { title: "Observability", items: ["Datadog", "CloudWatch", "Azure Monitor", "Grafana"] },
    ],
    faqs: [
      { q: "How do you avoid runaway cloud bills?", a: "FinOps practices — tagging, showback, rightsizing, reserved/savings plans — start during migration design, not after the invoices arrive." },
      { q: "Can you migrate without downtime?", a: "For most workloads, yes. We use CDC, blue/green, and traffic shifting to stage cutovers and prove rollback before go-live." },
      { q: "Will you train our team?", a: "Yes. Knowledge transfer, paved-road templates, and pairing are part of every migration." },
    ],
    related: [
      { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud foundations and platform engineering after the migration." },
      { name: "DevOps & SRE", href: "/technologies/devops", body: "CI/CD, observability, and SRE practices for cloud-native platforms." },
      { name: "Legacy modernization", href: "/technologies/legacy-modernization", body: "Strangler-fig modernization for workloads that need more than a lift-and-shift." },
    ],
    ctaTitle: "Migrate to cloud with HIGAET — without the drama.",
    ctaBody: "Tell us about your estate. We'll respond with a 6 Rs sketch and an indicative wave plan.",
  }),

  "business-intelligence": make({
    slug: "business-intelligence",
    eyebrow: "Business intelligence",
    title: "Business intelligence that drives decisions, not dashboards.",
    subtitle: "Semantic models, self-service analytics, embedded BI, and KPI programs designed around how your teams actually decide.",
    metaTitle: "Business Intelligence Services — HIGAET Technologies",
    metaDescription: "Business intelligence, semantic modeling, self-service analytics, and embedded BI by HIGAET Technologies. Decisions, not just dashboards.",
    heroHighlights: ["Trusted metric definitions", "Self-service for business teams", "Embedded BI in your products", "Governance and access controls"],
    overviewTitle: "BI that actually changes what gets done.",
    overviewBody: "We design BI programs around your decisions — the recurring choices the business needs to make better. That means clean metric layers, intuitive dashboards, embedded analytics where users work, and the governance to keep it all trustworthy.",
    benefits: [
      { title: "One source of truth", body: "Semantic models and KPI catalogs end the metric arguments and version conflicts." },
      { title: "Faster decisions", body: "Insights show up where decisions are made — in tools, dashboards, and alerts." },
      { title: "Self-service that works", body: "Curated marts and modeled metrics let business teams explore without drowning IT in tickets." },
      { title: "Embedded value", body: "Analytics inside your products turn data into customer-facing differentiation." },
      { title: "Governed access", body: "Row-level security, masking, and audit logs meet privacy and compliance bars." },
      { title: "Lower BI cost", body: "Tool rationalization and warehouse tuning often pay back the engagement within a year." },
    ],
    features: [
      { icon: BarChart3, title: "Dashboards & reports", body: "Power BI, Looker, Tableau, Metabase, and Superset done well — not just templated." },
      { icon: Layers, title: "Semantic modeling", body: "dbt + semantic layer (Cube, dbt MetricFlow, LookML) for one definition of every KPI." },
      { icon: Workflow, title: "KPI programs", body: "Define, instrument, and govern the metrics your leadership actually steers by." },
      { icon: Plug, title: "Embedded BI", body: "Customer-facing analytics with row-level security inside your SaaS products." },
      { icon: ShieldCheck, title: "Governance", body: "Catalogs, lineage, access controls, and masking aligned with GDPR/HIPAA." },
      { icon: Sparkles, title: "AI-augmented", body: "Natural-language querying, anomaly detection, and narrative generation on top of trusted data." },
    ],
    process: [
      { title: "Decisions audit", body: "Identify recurring decisions and the KPIs that should drive them.", deliverables: ["Decisions map", "KPI catalog"] },
      { title: "Model", body: "dbt models, semantic layer, and KPI definitions versioned and tested.", deliverables: ["Models", "Semantic layer"] },
      { title: "Build", body: "Dashboards, embedded analytics, and alerts shipped iteratively with users.", deliverables: ["Dashboards", "Alerts"] },
      { title: "Govern", body: "Access, lineage, masking, and freshness SLAs operating from day one.", deliverables: ["Governance plan"] },
      { title: "Enable", body: "Analytics engineering coaching and self-service playbooks for your teams.", deliverables: ["Training", "Docs"] },
    ],
    techGroups: [
      { title: "BI tools", items: ["Power BI", "Looker", "Tableau", "Metabase", "Superset"] },
      { title: "Modeling", items: ["dbt", "Cube", "MetricFlow", "LookML"] },
      { title: "Warehouses", items: ["Snowflake", "BigQuery", "Databricks", "Redshift"] },
      { title: "Embedded", items: ["Cube", "Sigma", "Embeddable"] },
      { title: "Governance", items: ["Collibra", "Alation", "Atlan", "DataHub"] },
    ],
    faqs: [
      { q: "We have dashboards no one uses. Help.", a: "We start with a decisions audit. Most BI debt comes from building reports without a clear consumer or decision; we fix that first." },
      { q: "Can you embed analytics inside our SaaS product?", a: "Yes — with row-level security, white-label theming, and APIs that fit your product UX." },
      { q: "Power BI or Looker?", a: "Depends on org structure, license posture, and the embedded story. We make the recommendation during discovery." },
    ],
    related: [
      { name: "Data engineering", href: "/technologies/data-engineering", body: "The pipelines and warehouses your BI sits on." },
      { name: "AI solutions", href: "/technologies/ai-solutions", body: "Predictive and generative AI on top of your data platform." },
      { name: "Digital transformation", href: "/technologies/digital-transformation", body: "Decision programs woven into operating-model change." },
    ],
    ctaTitle: "Turn BI into decisions — with HIGAET.",
    ctaBody: "Tell us where decisions are slow or unsupported by data. We'll respond with a focused BI plan.",
  }),

  "api-development": make({
    slug: "api-development",
    eyebrow: "API development",
    title: "APIs your partners, your products, and your AI agents can rely on.",
    subtitle: "REST, GraphQL, gRPC, and event-driven APIs designed with contracts, governance, and developer experience first.",
    metaTitle: "API Development Services — HIGAET Technologies",
    metaDescription: "Enterprise API development: REST, GraphQL, gRPC, event-driven. Contract-first, governed, and AI-ready. By HIGAET Technologies.",
    heroHighlights: ["Contract-first design", "Versioning and deprecation that works", "Developer portal, SDKs, sandboxes", "AI-agent-friendly"],
    overviewTitle: "APIs as long-lived product surfaces.",
    overviewBody: "APIs outlive UIs. We design them like products — contracts, governance, SDKs, sandboxes, and observability — so your partners, internal teams, and AI agents can build on them with confidence.",
    benefits: [
      { title: "Faster integrations", body: "Clear contracts, SDKs, and sandboxes cut partner onboarding from months to days." },
      { title: "Lower change cost", body: "Versioning, deprecation, and contract tests make change safe for consumers." },
      { title: "Monetizable", body: "Plans, quotas, billing, and analytics make APIs revenue lines, not cost centers." },
      { title: "AI-ready", body: "Typed, well-described APIs become the backbone for agentic workflows." },
      { title: "Security baseline", body: "OAuth 2.1, mTLS, JWT, scopes, and rate limits designed in from day one." },
      { title: "Operationally observable", body: "Per-consumer SLOs, error budgets, and dashboards keep API health visible." },
    ],
    features: [
      { icon: Cable, title: "REST & GraphQL", body: "Idiomatic REST and federated GraphQL aligned to your domain model." },
      { icon: Network, title: "gRPC & events", body: "High-throughput service-to-service and event-driven (Kafka, Pulsar, EventBridge) APIs." },
      { icon: Code2, title: "Contract-first", body: "OpenAPI, AsyncAPI, and Protobuf as the source of truth, with generated SDKs and tests." },
      { icon: Plug, title: "Developer portals", body: "Docs, sandboxes, key management, and analytics through Backstage, Stoplight, or Apigee." },
      { icon: ShieldCheck, title: "API security", body: "OAuth 2.1, scopes, mTLS, signing, and threat protection at the gateway." },
      { icon: Activity, title: "Observability", body: "Per-consumer SLOs, anomaly detection, and detailed traces across the call graph." },
    ],
    process: [
      { title: "Design", body: "Domain model, API style guide, and contract-first OpenAPI / AsyncAPI specs.", deliverables: ["Style guide", "Specs"] },
      { title: "Build", body: "Implementation, contract tests, SDK generation, and CI quality gates.", deliverables: ["Endpoints", "SDKs"] },
      { title: "Publish", body: "Developer portal, sandboxes, and partner onboarding flow live.", deliverables: ["Portal", "Sandbox"] },
      { title: "Govern", body: "Versioning, deprecation, security review, and lifecycle policies.", deliverables: ["Policies", "Lifecycle plan"] },
      { title: "Operate", body: "Observability, SLOs, and incident response with consumer-facing status.", deliverables: ["Dashboards", "Status page"] },
    ],
    techGroups: [
      { title: "Protocols", items: ["REST", "GraphQL", "gRPC", "WebSockets", "Webhooks"] },
      { title: "Gateways", items: ["Kong", "Apigee", "AWS API Gateway", "Azure APIM"] },
      { title: "Streaming", items: ["Kafka", "Pulsar", "EventBridge", "NATS"] },
      { title: "Tooling", items: ["OpenAPI", "AsyncAPI", "Protobuf", "Stoplight", "Backstage"] },
      { title: "Security", items: ["OAuth 2.1", "OIDC", "mTLS", "JWT"] },
    ],
    faqs: [
      { q: "REST or GraphQL?", a: "We pick based on consumer needs. Partner / public APIs lean REST; complex product clients often benefit from GraphQL or federation." },
      { q: "Can you monetize our APIs?", a: "Yes — plans, quotas, billing integration, and analytics designed to turn APIs into revenue." },
      { q: "How do you handle breaking changes?", a: "Versioning policy, deprecation timelines, contract tests, and consumer-driven contracts." },
    ],
    related: [
      { name: "System integration", href: "/technologies/system-integration", body: "Connect APIs across your enterprise stack with event-driven patterns." },
      { name: "Custom software", href: "/technologies/custom-software-development", body: "Product engineering squads that consume — or expose — these APIs." },
      { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud-native foundations for high-throughput API platforms." },
    ],
    ctaTitle: "Build APIs as a product — with HIGAET.",
    ctaBody: "Tell us about your API estate. We'll respond with a design and platform plan.",
  }),

  "system-integration": make({
    slug: "system-integration",
    eyebrow: "System integration",
    title: "System integration that turns siloed software into one operating system.",
    subtitle: "Event-driven, API-first integration across SaaS, ERPs, and bespoke systems — with governance and observability included.",
    metaTitle: "System Integration Services — HIGAET Technologies",
    metaDescription: "Enterprise system integration: API-first, event-driven, iPaaS, ESB modernization. By HIGAET Technologies.",
    heroHighlights: ["Event-driven by default", "iPaaS, ESB, and custom", "Idempotent, observable flows", "AI-ready integration layer"],
    overviewTitle: "Integration that compounds, not collapses.",
    overviewBody: "We connect ERPs, CRMs, HRIS, SaaS, custom apps, and partner systems with event-driven patterns and contracts that survive change. The result is fewer point-to-point integrations and a foundation for AI workflows.",
    benefits: [
      { title: "Less fragile glue", body: "Event-driven, contract-tested integrations replace brittle batch jobs and one-off scripts." },
      { title: "Lower run cost", body: "Consolidating onto a managed integration layer cuts duplicate connectors and licensing." },
      { title: "Faster onboarding", body: "Reusable connectors and templates accelerate every new partner or system." },
      { title: "AI-ready data flow", body: "Streaming events become the substrate for agents, copilots, and real-time analytics." },
      { title: "Observability", body: "End-to-end traceability across systems — no more guessing where a record stopped." },
      { title: "Governed", body: "Schemas, contracts, access controls, and data-residency policies enforced in one place." },
    ],
    features: [
      { icon: Plug, title: "iPaaS programs", body: "Workato, Boomi, MuleSoft, and Tray implementations done with engineering rigor." },
      { icon: Network, title: "Event streaming", body: "Kafka, Pulsar, EventBridge, and Solace topologies for real-time integration." },
      { icon: Cable, title: "API integration", body: "REST, GraphQL, gRPC, and webhook integrations with idempotency and retries built in." },
      { icon: Workflow, title: "Process orchestration", body: "Temporal, Camunda, and Step Functions for long-running, stateful workflows." },
      { icon: RefreshCw, title: "Data replication", body: "CDC pipelines for syncing ERPs, CRMs, and warehouses without batch lag." },
      { icon: ShieldCheck, title: "Integration governance", body: "Schema registries, contracts, masking, and audit logging across every flow." },
    ],
    process: [
      { title: "Map", body: "Catalog systems, flows, and integration debt; surface highest-value targets.", deliverables: ["Integration map"] },
      { title: "Design", body: "Patterns, contracts, and platform decisions aligned to architecture.", deliverables: ["Patterns", "Reference architecture"] },
      { title: "Build", body: "Connectors, flows, and orchestrations shipped iteratively with tests.", deliverables: ["Flows", "Tests"] },
      { title: "Govern", body: "Schema registry, access controls, and observability operating from day one.", deliverables: ["Governance", "Dashboards"] },
      { title: "Operate", body: "On-call, incident response, and continuous rationalization of connectors.", deliverables: ["Runbooks", "Quarterly reviews"] },
    ],
    techGroups: [
      { title: "iPaaS", items: ["Workato", "Boomi", "MuleSoft", "Tray"] },
      { title: "Streaming", items: ["Kafka", "Pulsar", "EventBridge", "Solace"] },
      { title: "Orchestration", items: ["Temporal", "Camunda", "Step Functions", "Airflow"] },
      { title: "Data sync", items: ["Debezium", "Fivetran", "AWS DMS"] },
      { title: "Governance", items: ["Schema Registry", "Apicurio", "OPA"] },
    ],
    faqs: [
      { q: "iPaaS or custom?", a: "iPaaS for standard SaaS connectivity; custom (events, orchestration) for differentiated business processes. Most clients need both, with clear ownership." },
      { q: "How do you avoid integration spaghetti?", a: "Event-driven core, contract-first APIs, and a small set of patterns reused across teams." },
      { q: "Can you connect us to legacy?", a: "Yes — including SOAP, EDI, mainframe, and file-based systems wrapped in modern, observable adapters." },
    ],
    related: [
      { name: "API development", href: "/technologies/api-development", body: "Production-grade APIs as the contract surface for integration." },
      { name: "Legacy modernization", href: "/technologies/legacy-modernization", body: "Modernize systems your integrations depend on." },
      { name: "Data engineering", href: "/technologies/data-engineering", body: "Move integration events into a governed analytics layer." },
    ],
    ctaTitle: "Connect your stack without the spaghetti — with HIGAET.",
    ctaBody: "Tell us about your systems. We'll respond with an integration map and platform plan.",
  }),

  "legacy-modernization": make({
    slug: "legacy-modernization",
    eyebrow: "Legacy application modernization",
    title: "Modernize legacy systems without halting the business.",
    subtitle: "Strangler-fig migrations, replatforming, and rewrites — sized to risk and tied to clear business outcomes.",
    metaTitle: "Legacy Application Modernization Services — HIGAET Technologies",
    metaDescription: "Legacy modernization: strangler-fig migrations, replatforming, mainframe-to-cloud. By HIGAET Technologies. Incremental, risk-managed, outcome-driven.",
    heroHighlights: ["Strangler-fig, not big-bang", "Mainframe, .NET, Java, PHP, COBOL", "Business continuity guaranteed", "Outcome-tied roadmaps"],
    overviewTitle: "Modernize at the speed the business can absorb.",
    overviewBody: "We modernize legacy software in incremental waves — each one shipping a measurable improvement. Architecture decisions, risk management, and change management run alongside engineering, not after it.",
    benefits: [
      { title: "Lower TCO", body: "Cloud-native replacements cut licensing, infrastructure, and patching costs." },
      { title: "Reduced risk", body: "Incremental delivery lets you pause, adjust, or roll back — no all-or-nothing migrations." },
      { title: "Faster delivery", body: "Modern stacks and CI/CD turn quarterly releases into weekly ones." },
      { title: "Security uplift", body: "Modern identity, encryption, and patching baselines replace aging controls." },
      { title: "Talent appeal", body: "Engineers stay on stacks they can grow with." },
      { title: "AI readiness", body: "Modernized systems become the substrate for copilots, automation, and analytics." },
    ],
    features: [
      { icon: Layers, title: "Strangler-fig", body: "Carve off bounded contexts and replace them behind a stable façade — no big-bang rewrites." },
      { icon: CloudCog, title: "Replatform", body: "Lift-and-shift, containerize, or move to managed services with measurable cost savings." },
      { icon: Code2, title: "Targeted rewrites", body: "Greenfield rewrites where the codebase is beyond salvage — with a clear cutover plan." },
      { icon: RefreshCw, title: "Data migration", body: "Zero-downtime data migrations with CDC, dual-write, and rollback strategies." },
      { icon: ShieldCheck, title: "Risk management", body: "Architecture decision records, threat models, and rollback plans on every wave." },
      { icon: Users, title: "Change management", body: "Comms, training, and support so the business adopts the new system on day one." },
    ],
    process: [
      { title: "Assess", body: "Code, architecture, and dependency audit with business-aligned modernization options.", deliverables: ["Audit", "Options paper"] },
      { title: "Plan", body: "Wave roadmap, target architecture, and risk register agreed with stakeholders.", deliverables: ["Roadmap", "Architecture"] },
      { title: "Modernize", body: "Senior squads ship wave-by-wave with measurable outcomes per release.", deliverables: ["Releases", "KPIs"] },
      { title: "Cutover", body: "Dual-running, data sync, and staged user migration with rollback ready.", deliverables: ["Cutover plan", "Rollback plan"] },
      { title: "Stabilize", body: "Hypercare, defect triage, and quarterly modernization roadmap reviews.", deliverables: ["Hypercare", "Roadmap update"] },
    ],
    techGroups: [
      { title: "From", items: ["COBOL", "VB6", ".NET Framework", "Legacy Java", "PHP 5", "Delphi"] },
      { title: "To", items: ["Modern .NET", "Java 21", "Node.js", "Python", "Go"] },
      { title: "Cloud", items: ["AWS", "Azure", "GCP", "Kubernetes"] },
      { title: "Data", items: ["PostgreSQL", "MongoDB", "Snowflake", "BigQuery"] },
      { title: "Tooling", items: ["Strangler façade", "CDC", "Feature flags"] },
    ],
    faqs: [
      { q: "Should we rewrite or strangle?", a: "Almost always strangle. Big-bang rewrites are high-risk and rarely deliver on time. We rewrite only where the existing code is beyond salvage and the wave plan justifies it." },
      { q: "Will the business notice?", a: "Only the improvements. We dual-run, migrate users in cohorts, and keep rollback options open until each wave is proven." },
      { q: "Can you modernize mainframe workloads?", a: "Yes — COBOL, JCL, and z/OS workloads through repatriation, replatforming, or replacement, depending on the business case." },
    ],
    related: [
      { name: "Cloud migration", href: "/technologies/cloud-migration", body: "Move modernized workloads to AWS, Azure, or GCP with FinOps built in." },
      { name: "Enterprise software", href: "/technologies/enterprise-software", body: "Build the modern platforms that replace the legacy ones." },
      { name: "System integration", href: "/technologies/system-integration", body: "Keep legacy and modern systems in lockstep during the migration." },
    ],
    ctaTitle: "Modernize legacy — with HIGAET, without the drama.",
    ctaBody: "Tell us about the system. We'll respond with an audit and wave plan.",
  }),

  "software-maintenance": make({
    slug: "software-maintenance",
    eyebrow: "Software maintenance & support",
    title: "Maintenance and support that keeps software healthy — and improving.",
    subtitle: "L2/L3 support, SRE, security patching, and continuous improvement under clear SLAs.",
    metaTitle: "Software Maintenance & Support Services — HIGAET Technologies",
    metaDescription: "L2/L3 software support, SRE, security patching, and continuous improvement under SLAs. By HIGAET Technologies.",
    heroHighlights: ["Clear SLAs and SLOs", "L2, L3, and SRE coverage", "Security patching on cadence", "Continuous improvement, not just keep-the-lights-on"],
    overviewTitle: "Run the system — and make it better every quarter.",
    overviewBody: "We treat maintenance as a product practice: defects fixed at root cause, vulnerabilities patched on cadence, performance tuned against SLOs, and a slice of every sprint reserved for measurable improvement.",
    benefits: [
      { title: "Predictable uptime", body: "SLOs and error budgets keep reliability promises grounded in engineering reality." },
      { title: "Lower defect rate", body: "Root-cause fixes and regression tests prevent the same bug from coming back." },
      { title: "Security posture", body: "CVE monitoring, dependency upgrades, and patch cadences keep risk in check." },
      { title: "Lower total cost", body: "Tech-debt paydown sprints prevent the slow drift toward expensive rewrites." },
      { title: "User trust", body: "Public status, incident comms, and post-incident reviews build customer confidence." },
      { title: "Insightful", body: "Quarterly reviews surface trends across defects, performance, and usage." },
    ],
    features: [
      { icon: LifeBuoy, title: "L2 / L3 support", body: "Tiered support with ticketing, on-call coverage, and clear escalation paths." },
      { icon: Activity, title: "SRE & SLOs", body: "Service level objectives, error budgets, and reliability programs aligned to business risk." },
      { icon: ShieldCheck, title: "Security patching", body: "CVE monitoring, dependency upgrades, and emergency patch capability." },
      { icon: RefreshCw, title: "Tech-debt paydown", body: "Engineered backlog of debt items, prioritized by risk and cost, shipped each quarter." },
      { icon: BarChart3, title: "Performance tuning", body: "Profiling, query tuning, and capacity planning against SLOs and growth forecasts." },
      { icon: Headset, title: "Hypercare", body: "Post-launch hypercare with extended hours and senior responders for high-risk releases." },
    ],
    process: [
      { title: "Onboard", body: "Knowledge transfer, runbooks, tooling integration, and SLA setup.", deliverables: ["Runbooks", "SLA"] },
      { title: "Stabilize", body: "Defect triage, dependency upgrades, and observability baseline.", deliverables: ["Stability plan"] },
      { title: "Run", body: "Tiered support, on-call rotations, and incident response under agreed SLAs.", deliverables: ["Ticket flow", "On-call"] },
      { title: "Improve", body: "Continuous improvement backlog shipped each sprint against SLOs.", deliverables: ["Improvement releases"] },
      { title: "Review", body: "Quarterly reviews of defects, performance, security, and roadmap.", deliverables: ["QBR report"] },
    ],
    techGroups: [
      { title: "ITSM", items: ["Jira Service Management", "Zendesk", "ServiceNow"] },
      { title: "Observability", items: ["Datadog", "Grafana", "New Relic", "Sentry"] },
      { title: "On-call", items: ["PagerDuty", "Opsgenie", "Incident.io"] },
      { title: "Security", items: ["Snyk", "Dependabot", "Renovate", "Trivy"] },
    ],
    faqs: [
      { q: "Will you support apps you didn't build?", a: "Yes. We start with a structured onboarding (codebase audit, runbooks, observability) before taking SLA ownership." },
      { q: "What SLAs can you offer?", a: "Standard business hours through 24/7 with response/resolution targets per severity. Set during onboarding to match your risk profile." },
      { q: "Will you add features or just keep the lights on?", a: "Both. Every engagement carves out continuous improvement capacity, not just defect fixes." },
    ],
    related: [
      { name: "DevOps & SRE", href: "/technologies/devops", body: "Platform engineering and SRE practices we run support on top of." },
      { name: "QA & testing", href: "/technologies/qa-testing", body: "Quality engineering that prevents the defects support has to chase." },
      { name: "Cloud solutions", href: "/technologies/cloud-solutions", body: "Cloud foundations that make availability and recovery routine." },
    ],
    ctaTitle: "Keep software healthy — with HIGAET support.",
    ctaBody: "Tell us about the application and your SLAs. We'll respond with an onboarding plan.",
  }),

  "it-consulting": make({
    slug: "it-consulting",
    eyebrow: "IT consulting",
    title: "IT consulting that lands — because the people who advise also build.",
    subtitle: "Strategy, architecture, sourcing, and operating-model advice from senior practitioners, not slide-only consultants.",
    metaTitle: "IT Consulting Services — HIGAET Technologies",
    metaDescription: "IT strategy, architecture, sourcing, and operating-model consulting by senior practitioners. By HIGAET Technologies.",
    heroHighlights: ["Practitioner advisors", "Strategy that ships", "Architecture, sourcing, and operating model", "AI-first thinking"],
    overviewTitle: "Advice from people who'll be on the build team if you say go.",
    overviewBody: "Our consultants are senior engineers, architects, and product leaders — the same people who run our delivery teams. The advice is grounded in what actually ships, not just what looks good on a deck.",
    benefits: [
      { title: "Implementable strategy", body: "Roadmaps come with cost, risk, and capability honesty — not just ambition." },
      { title: "Faster decisions", body: "Outside perspective accelerates trade-offs your team has been circling for months." },
      { title: "Vendor leverage", body: "Independent sourcing advice for cloud, SaaS, and integrator selection." },
      { title: "AI-first lens", body: "Every recommendation considers where AI changes the economics of the problem." },
      { title: "Capability building", body: "Coaching and pairing leave your teams more capable than we found them." },
      { title: "Optional delivery", body: "If you want, the same team that advised can execute — under one accountable contract." },
    ],
    features: [
      { icon: Compass, title: "IT strategy", body: "Operating model, capability maps, and portfolio prioritization aligned to business strategy." },
      { icon: Layers, title: "Architecture", body: "Enterprise architecture, reference architectures, and ADRs for high-stakes decisions." },
      { icon: Workflow, title: "Operating model", body: "Squad design, governance, sourcing mix, and capability building plans." },
      { icon: Package, title: "Vendor selection", body: "RFPs, evaluations, and contract advisory for cloud, SaaS, and integrator choices." },
      { icon: Sparkles, title: "AI strategy", body: "Use-case prioritization, governance, and platform decisions for applied AI." },
      { icon: ShieldCheck, title: "Risk & compliance", body: "Security, privacy, and regulatory advisory tied to delivery realities." },
    ],
    process: [
      { title: "Frame", body: "Discovery interviews, document review, and decision framing.", deliverables: ["Discovery summary", "Decision frame"] },
      { title: "Diagnose", body: "Current-state analysis, benchmarking, and option generation.", deliverables: ["Diagnosis", "Options"] },
      { title: "Decide", body: "Recommendation, business case, and implementation roadmap with stakeholder alignment.", deliverables: ["Recommendation", "Roadmap"] },
      { title: "Mobilize", body: "Stand up the work — internal teams, partners, or HIGAET squads — with governance.", deliverables: ["Mobilization plan"] },
      { title: "Review", body: "Optional ongoing advisory and quarterly check-ins.", deliverables: ["Quarterly reviews"] },
    ],
    techGroups: [
      { title: "Strategy", items: ["Operating models", "Portfolio design", "Capability maps"] },
      { title: "Architecture", items: ["Enterprise architecture", "Domain-driven design", "Event-driven"] },
      { title: "AI", items: ["Use-case maps", "Platform selection", "Governance"] },
      { title: "Sourcing", items: ["RFPs", "Cloud cost", "SaaS rationalization"] },
    ],
    faqs: [
      { q: "Are you slide-only or hands-on?", a: "Hands-on. Our consultants run delivery teams; the recommendations are sized to what we'd be willing to execute." },
      { q: "Will you sell us your own services?", a: "Only if it's the right answer. We routinely recommend in-house builds or other vendors when that's the better fit." },
      { q: "Can you support board-level decisions?", a: "Yes. We package recommendations for executive and board audiences, with the underlying analysis on tap." },
    ],
    related: [
      { name: "Digital transformation", href: "/technologies/digital-transformation", body: "Programmatic execution of the strategies we help define." },
      { name: "Enterprise software", href: "/technologies/enterprise-software", body: "Delivery squads when the recommendation is to build." },
      { name: "AI solutions", href: "/technologies/ai-solutions", body: "From AI strategy to working systems in production." },
    ],
    ctaTitle: "Get advice that ships — with HIGAET.",
    ctaBody: "Tell us the decision you're working through. We'll respond with a short engagement plan.",
  }),

  "staff-augmentation": make({
    slug: "staff-augmentation",
    eyebrow: "Staff augmentation",
    title: "Staff augmentation with engineers who fit in fast — and stay.",
    subtitle: "Embed vetted senior engineers, designers, and SREs into your team within weeks, on the contract model that suits you.",
    metaTitle: "IT Staff Augmentation Services — HIGAET Technologies",
    metaDescription: "Staff augmentation: vetted senior engineers, designers, and SREs embedded into your team. Flexible contracts. By HIGAET Technologies.",
    heroHighlights: ["Senior, vetted, low churn", "Onboarded in weeks, not months", "Time & materials or fixed monthly", "Cultural fit guaranteed"],
    overviewTitle: "Talent that joins your team — not a separate pod.",
    overviewBody: "We embed senior engineers into your team to close skill gaps and accelerate roadmaps. Each candidate is vetted technically and culturally, onboarded into your tooling, and managed by you under your delivery process.",
    benefits: [
      { title: "Fast capacity", body: "Add senior capacity in weeks without the cost and risk of permanent hires." },
      { title: "Skill targeting", body: "Surgical access to React, Node.js, .NET, Java, Python, AI, Data, DevOps, mobile, and design talent." },
      { title: "Low churn", body: "We invest in long tenures and shared incentives; rotations are rare and planned." },
      { title: "Cultural fit", body: "Every candidate is interviewed for collaboration, communication, and product mindset." },
      { title: "Flexible contracts", body: "Time & materials, monthly retainer, or hybrid — whichever suits the engagement." },
      { title: "Optional escalation", body: "Scale individual roles into a full HIGAET dedicated squad if scope grows." },
    ],
    features: [
      { icon: Users, title: "Engineering roles", body: "Full-stack, frontend, backend, mobile, AI, data, and SRE engineers." },
      { icon: Compass, title: "Design & product", body: "Product designers, UX researchers, and product managers embedded into your team." },
      { icon: ShieldCheck, title: "Vetting", body: "Technical interviews, references, security checks, and cultural-fit screening." },
      { icon: Workflow, title: "Your process", body: "Your standups, tools, repos, and Definition of Done — we adapt, not impose." },
      { icon: RefreshCw, title: "Coverage continuity", body: "Backups, shadowing, and KT plans so a planned departure doesn't derail delivery." },
      { icon: GraduationCap, title: "HIGAET pipeline", body: "Engineers trained through the HIGAET Academy talent program." },
    ],
    process: [
      { title: "Brief", body: "Role definition, must-haves, nice-to-haves, and team context.", deliverables: ["Role brief"] },
      { title: "Shortlist", body: "Curated, vetted candidates within one to two weeks of the brief.", deliverables: ["Shortlist"] },
      { title: "Interview", body: "You interview and select; we coordinate scheduling and feedback.", deliverables: ["Hiring decision"] },
      { title: "Onboard", body: "Tooling access, NDAs, and structured onboarding into your process.", deliverables: ["Productive engineer"] },
      { title: "Review", body: "Regular check-ins on fit, performance, and roadmap match.", deliverables: ["Reviews"] },
    ],
    techGroups: [
      { title: "Engineering", items: ["React", "Next.js", "Node.js", "Python", "Java", ".NET", "Go"] },
      { title: "Mobile", items: ["React Native", "Flutter", "Swift", "Kotlin"] },
      { title: "AI & Data", items: ["LangChain", "OpenAI", "dbt", "Snowflake"] },
      { title: "DevOps", items: ["Kubernetes", "Terraform", "GitHub Actions"] },
      { title: "Design", items: ["Figma", "Storybook", "Design systems"] },
    ],
    faqs: [
      { q: "How is this different from a dedicated team?", a: "Staff augmentation embeds individuals into your team under your management. Dedicated teams ship outcomes under ours. We do both." },
      { q: "What if a hire doesn't work out?", a: "Quick replacement within an agreed window, no exit fees, with the previous engineer continuing during handover." },
      { q: "Can we scale up or down?", a: "Yes. Most contracts allow monthly adjustments with reasonable notice." },
    ],
    related: [
      { name: "Dedicated team", href: "/technologies/dedicated-team", body: "Outcome-owning squads when you'd rather hand over a problem than manage individuals." },
      { name: "Custom software", href: "/technologies/custom-software-development", body: "Fixed-scope or T&M engineering on a defined outcome." },
      { name: "IT consulting", href: "/technologies/it-consulting", body: "Advisory work when the question is what to build, not just who builds it." },
    ],
    ctaTitle: "Add senior capacity in weeks — with HIGAET.",
    ctaBody: "Tell us about the roles you need. We'll respond with a shortlist within two weeks.",
  }),
};
