// HIGAET University Knowledge Base — static content registry.
// 50 universities across USA (20), UK (10), Canada (10), Australia (10).
// Used by /global-education/knowledge-base/universities[/$slug] routes.

export type CountryCode = "US" | "UK" | "CA" | "AU";

export interface UniversityFAQ {
  q: string;
  a: string;
}

export interface UniversityKB {
  slug: string;
  name: string;
  country: CountryCode;
  countryName: string;
  city: string;
  website: string;
  founded: number;
  worldRanking?: number;
  overview: string;
  programs: string[];
  tuitionUsd: { undergrad?: string; postgrad?: string; notes?: string };
  admissions: string[];
  scholarships: string[];
  faqs: UniversityFAQ[];
}

const COUNTRY_NAMES: Record<CountryCode, string> = {
  US: "United States",
  UK: "United Kingdom",
  CA: "Canada",
  AU: "Australia",
};

function u(
  partial: Omit<UniversityKB, "countryName"> & { countryName?: string },
): UniversityKB {
  return { countryName: COUNTRY_NAMES[partial.country], ...partial } as UniversityKB;
}

export const UNIVERSITIES_KB: UniversityKB[] = [
  // ===== USA (20) =====
  u({ slug: "mit", name: "Massachusetts Institute of Technology", country: "US", city: "Cambridge, MA", website: "https://web.mit.edu", founded: 1861, worldRanking: 1,
    overview: "World-leading research university known for engineering, computer science, AI, and entrepreneurship. Renowned for hands-on, problem-solving culture.",
    programs: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "AI & Machine Learning", "MBA (Sloan)", "Data Science"],
    tuitionUsd: { undergrad: "$60,000/yr", postgrad: "$62,000/yr" },
    admissions: ["High academic record", "SAT/ACT (test-optional varies)", "Strong essays", "TOEFL 90+ / IELTS 7.0+"],
    scholarships: ["Need-based financial aid", "MIT Presidential Fellowship (grad)"],
    faqs: [
      { q: "Is MIT need-blind for international students?", a: "Yes. MIT is need-blind for all applicants, including international students, and meets full demonstrated need." },
      { q: "What is the acceptance rate?", a: "Around 4–5% in recent cycles." },
    ],
  }),
  u({ slug: "stanford-university", name: "Stanford University", country: "US", city: "Stanford, CA", website: "https://www.stanford.edu", founded: 1885, worldRanking: 3,
    overview: "Silicon Valley powerhouse with top programs in CS, AI, engineering, business, and design. Deep ties to tech industry and venture capital.",
    programs: ["Computer Science", "AI", "Engineering", "MBA (GSB)", "Symbolic Systems", "Data Science"],
    tuitionUsd: { undergrad: "$62,000/yr", postgrad: "$65,000/yr" },
    admissions: ["Top academic profile", "SAT/ACT", "Essays + LORs", "TOEFL 100+"],
    scholarships: ["Need-based aid", "Knight-Hennessy Scholars"],
    faqs: [
      { q: "Does Stanford offer merit scholarships?", a: "Most aid is need-based. The Knight-Hennessy Scholars program funds graduate study." },
    ],
  }),
  u({ slug: "harvard-university", name: "Harvard University", country: "US", city: "Cambridge, MA", website: "https://www.harvard.edu", founded: 1636, worldRanking: 4,
    overview: "Oldest US university; global leader in law, business, medicine, public policy, and the liberal arts.",
    programs: ["Law (JD)", "MBA (HBS)", "Public Policy (HKS)", "Computer Science", "Medicine", "Economics"],
    tuitionUsd: { undergrad: "$59,000/yr", postgrad: "$55,000–$78,000/yr" },
    admissions: ["Holistic review", "SAT/ACT (test-optional through 2026)", "TOEFL 100+"],
    scholarships: ["Harvard Financial Aid Initiative (need-based)"],
    faqs: [
      { q: "Is Harvard affordable for international students?", a: "Families earning under ~$85k typically pay $0 tuition; aid is need-based and generous." },
    ],
  }),
  u({ slug: "caltech", name: "California Institute of Technology", country: "US", city: "Pasadena, CA", founded: 1891, website: "https://www.caltech.edu", worldRanking: 7,
    overview: "Small, intense research institute focused on science and engineering with one of the highest faculty-to-student ratios in the world.",
    programs: ["Physics", "Computer Science", "Aerospace", "Chemistry", "Astronomy"],
    tuitionUsd: { undergrad: "$60,000/yr", postgrad: "$58,000/yr" },
    admissions: ["Exceptional STEM record", "SAT/ACT", "TOEFL 100+"],
    scholarships: ["Need-based aid", "Graduate fellowships"],
    faqs: [{ q: "How large is Caltech?", a: "About 1,000 undergrads and 1,400 graduate students — tiny by US standards." }],
  }),
  u({ slug: "princeton-university", name: "Princeton University", country: "US", city: "Princeton, NJ", founded: 1746, website: "https://www.princeton.edu", worldRanking: 16,
    overview: "Ivy League leader in undergraduate education with strong programs in economics, math, public affairs, and engineering.",
    programs: ["Economics", "Computer Science", "Public Policy (SPIA)", "Mathematics", "Engineering"],
    tuitionUsd: { undergrad: "$59,000/yr", postgrad: "$60,000/yr" },
    admissions: ["Top academics", "SAT/ACT", "Strong recommendations", "TOEFL 100+"],
    scholarships: ["Princeton Financial Aid (need-based, full grants — no loans)"],
    faqs: [{ q: "Does Princeton offer loans in financial aid?", a: "No. Aid is grant-based, so students graduate debt-free." }],
  }),
  u({ slug: "yale-university", name: "Yale University", country: "US", city: "New Haven, CT", founded: 1701, website: "https://www.yale.edu", worldRanking: 23,
    overview: "Ivy League institution renowned for law, drama, the humanities, and a distinctive residential college system.",
    programs: ["Law", "Liberal Arts", "Drama", "Economics", "Computer Science"],
    tuitionUsd: { undergrad: "$64,000/yr", postgrad: "$48,000–$72,000/yr" },
    admissions: ["Holistic review", "SAT/ACT", "TOEFL 100+"],
    scholarships: ["Need-based aid", "Yale World Fellows"],
    faqs: [{ q: "Is Yale need-blind for internationals?", a: "Yes — Yale is need-blind worldwide and meets 100% of need." }],
  }),
  u({ slug: "columbia-university", name: "Columbia University", country: "US", city: "New York, NY", founded: 1754, website: "https://www.columbia.edu", worldRanking: 17,
    overview: "Ivy League research university in Manhattan with elite programs across journalism, business, engineering, and the arts.",
    programs: ["Journalism", "MBA", "Computer Science", "International Affairs (SIPA)", "Engineering"],
    tuitionUsd: { undergrad: "$66,000/yr", postgrad: "$55,000–$80,000/yr" },
    admissions: ["SAT/ACT (test-optional)", "TOEFL 100+", "Essays + LORs"],
    scholarships: ["Need-based aid", "Departmental fellowships"],
    faqs: [{ q: "Is Columbia good for STEM?", a: "Yes — SEAS is highly ranked and benefits from NYC industry access." }],
  }),
  u({ slug: "university-of-chicago", name: "University of Chicago", country: "US", city: "Chicago, IL", founded: 1890, website: "https://www.uchicago.edu", worldRanking: 11,
    overview: "Renowned for economics, the social sciences, and a rigorous Core curriculum. Home to 100+ Nobel laureates.",
    programs: ["Economics", "MBA (Booth)", "Computer Science", "Public Policy (Harris)", "Mathematics"],
    tuitionUsd: { undergrad: "$66,000/yr", postgrad: "$78,000/yr (Booth MBA)" },
    admissions: ["Distinctive essays", "SAT/ACT optional", "TOEFL 104+"],
    scholarships: ["Odyssey Scholarship", "Need-based aid"],
    faqs: [{ q: "What is the Core?", a: "A required interdisciplinary curriculum that anchors every undergraduate degree." }],
  }),
  u({ slug: "upenn", name: "University of Pennsylvania", country: "US", city: "Philadelphia, PA", founded: 1740, website: "https://www.upenn.edu", worldRanking: 12,
    overview: "Ivy League with Wharton's flagship business program, strong CS, nursing, and a culture of pre-professional excellence.",
    programs: ["MBA (Wharton)", "Finance", "Computer Science", "Nursing", "Bioengineering"],
    tuitionUsd: { undergrad: "$63,000/yr", postgrad: "$84,000/yr (Wharton MBA)" },
    admissions: ["Strong academics", "SAT/ACT", "TOEFL 100+"],
    scholarships: ["Need-based aid", "Joseph Wharton Scholars"],
    faqs: [{ q: "Is Wharton open to undergraduates?", a: "Yes — Wharton offers a BS in Economics with concentrations." }],
  }),
  u({ slug: "cornell-university", name: "Cornell University", country: "US", city: "Ithaca, NY", founded: 1865, website: "https://www.cornell.edu", worldRanking: 16,
    overview: "Ivy League with the broadest range of programs — engineering, business (Dyson, Johnson), agriculture, hospitality, and a NYC tech campus.",
    programs: ["Engineering", "Hotel Administration", "Computer Science", "Applied Economics", "Veterinary Medicine"],
    tuitionUsd: { undergrad: "$67,000/yr", postgrad: "$30,000–$80,000/yr" },
    admissions: ["College-specific review", "SAT/ACT optional", "TOEFL 100+"],
    scholarships: ["Need-based aid", "Cornell Tech fellowships"],
    faqs: [{ q: "Are some Cornell colleges state-funded?", a: "Yes — four contract colleges receive NY state support, with lower tuition for NY residents." }],
  }),
  u({ slug: "carnegie-mellon", name: "Carnegie Mellon University", country: "US", city: "Pittsburgh, PA", founded: 1900, website: "https://www.cmu.edu", worldRanking: 52,
    overview: "Top-tier in computer science, AI, robotics, design, and drama. SCS is widely considered the #1 CS program in the world.",
    programs: ["Computer Science", "AI", "Robotics", "Information Systems", "Design", "Drama"],
    tuitionUsd: { undergrad: "$63,000/yr", postgrad: "$50,000–$60,000/yr" },
    admissions: ["Strong STEM record", "SAT/ACT", "TOEFL 102+"],
    scholarships: ["CMU Scholars", "Need-based aid"],
    faqs: [{ q: "How competitive is CMU SCS admissions?", a: "Acceptance hovers near 6% — among the most selective CS programs globally." }],
  }),
  u({ slug: "uc-berkeley", name: "University of California, Berkeley", country: "US", city: "Berkeley, CA", founded: 1868, website: "https://www.berkeley.edu", worldRanking: 12,
    overview: "Top US public university with elite programs in EECS, business (Haas), and the sciences. Strong startup and research output.",
    programs: ["EECS", "Computer Science", "MBA (Haas)", "Data Science", "Economics"],
    tuitionUsd: { undergrad: "$48,000/yr (intl)", postgrad: "$32,000–$67,000/yr" },
    admissions: ["GPA + rigor", "SAT/ACT not used", "TOEFL 80+"],
    scholarships: ["Berkeley International Scholarship", "Departmental aid"],
    faqs: [{ q: "Does Berkeley use SAT?", a: "No — UC system is test-blind for admissions decisions." }],
  }),
  u({ slug: "ucla", name: "University of California, Los Angeles", country: "US", city: "Los Angeles, CA", founded: 1919, website: "https://www.ucla.edu", worldRanking: 29,
    overview: "Comprehensive public research university with top programs in film, medicine, business (Anderson), and engineering.",
    programs: ["Film & TV", "Computer Science", "Psychology", "MBA (Anderson)", "Engineering"],
    tuitionUsd: { undergrad: "$46,000/yr (intl)", postgrad: "$33,000–$70,000/yr" },
    admissions: ["GPA + rigor", "Test-blind", "TOEFL 87+"],
    scholarships: ["Regents Scholarship", "Need-based aid (US only)"],
    faqs: [{ q: "Can internationals get UCLA aid?", a: "Limited — most institutional need-based aid is restricted to US citizens/permanent residents." }],
  }),
  u({ slug: "university-of-michigan", name: "University of Michigan – Ann Arbor", country: "US", city: "Ann Arbor, MI", founded: 1817, website: "https://umich.edu", worldRanking: 33,
    overview: "Flagship public research university with top programs in engineering, business (Ross), and the social sciences.",
    programs: ["Engineering", "MBA (Ross)", "Computer Science", "Public Policy", "Nursing"],
    tuitionUsd: { undergrad: "$60,000/yr (intl)", postgrad: "$53,000–$72,000/yr" },
    admissions: ["Rigorous coursework", "SAT/ACT optional", "TOEFL 100+"],
    scholarships: ["Departmental fellowships", "Wolverine Pathways"],
    faqs: [{ q: "What is Ann Arbor like?", a: "A classic Big Ten college town — walkable, vibrant, and affordable for the US." }],
  }),
  u({ slug: "georgia-tech", name: "Georgia Institute of Technology", country: "US", city: "Atlanta, GA", founded: 1885, website: "https://www.gatech.edu", worldRanking: 36,
    overview: "Premier public tech university with top programs in CS, engineering, and analytics. Known for the affordable OMSCS online master's.",
    programs: ["Computer Science", "Engineering", "Analytics", "Industrial Engineering", "Cybersecurity"],
    tuitionUsd: { undergrad: "$33,000/yr (intl)", postgrad: "$30,000/yr; OMSCS ~$7,000 total" },
    admissions: ["Strong STEM record", "SAT/ACT required", "TOEFL 90+"],
    scholarships: ["Stamps President's Scholars", "Departmental aid"],
    faqs: [{ q: "Is OMSCS legit?", a: "Yes — same degree as on-campus MSCS, delivered online and globally respected." }],
  }),
  u({ slug: "uiuc", name: "University of Illinois Urbana-Champaign", country: "US", city: "Urbana-Champaign, IL", founded: 1867, website: "https://illinois.edu", worldRanking: 64,
    overview: "Top US public for engineering and computer science, with major contributions to graphics, databases, and AI.",
    programs: ["Computer Science", "Engineering", "Accountancy", "Agriculture", "Information Sciences"],
    tuitionUsd: { undergrad: "$36,000/yr (intl)", postgrad: "$22,000–$35,000/yr" },
    admissions: ["SAT/ACT", "TOEFL 79+"],
    scholarships: ["International Undergraduate Scholarship", "Departmental fellowships"],
    faqs: [{ q: "Is Grainger CS competitive?", a: "Highly — admission rate to CS is under 10%." }],
  }),
  u({ slug: "university-of-washington", name: "University of Washington", country: "US", city: "Seattle, WA", founded: 1861, website: "https://www.washington.edu", worldRanking: 25,
    overview: "Top-tier public research university in the heart of the Pacific Northwest tech ecosystem.",
    programs: ["Computer Science (Allen School)", "Bioengineering", "Public Health", "MBA (Foster)", "Aerospace"],
    tuitionUsd: { undergrad: "$42,000/yr (intl)", postgrad: "$32,000–$60,000/yr" },
    admissions: ["SAT/ACT optional", "TOEFL 76+"],
    scholarships: ["Husky Promise (WA residents)", "Departmental aid"],
    faqs: [{ q: "Is the Allen School hard to get into?", a: "Yes — direct admit acceptance is under 10%." }],
  }),
  u({ slug: "nyu", name: "New York University", country: "US", city: "New York, NY", founded: 1831, website: "https://www.nyu.edu", worldRanking: 38,
    overview: "Global university with strong programs in finance, film (Tisch), business (Stern), and the arts. Campuses in NYC, Abu Dhabi, and Shanghai.",
    programs: ["Business (Stern)", "Film (Tisch)", "Computer Science (Courant)", "Politics", "Data Science"],
    tuitionUsd: { undergrad: "$60,000/yr", postgrad: "$50,000–$80,000/yr" },
    admissions: ["Test-flexible", "TOEFL 100+", "Essays + LORs"],
    scholarships: ["AnBryce Scholarship", "Departmental aid"],
    faqs: [{ q: "Is NYU expensive?", a: "Yes — total cost of attendance often exceeds $90k/yr; aid is competitive." }],
  }),
  u({ slug: "duke-university", name: "Duke University", country: "US", city: "Durham, NC", founded: 1838, website: "https://www.duke.edu", worldRanking: 50,
    overview: "Top private university with strong programs in medicine, business (Fuqua), public policy, and engineering.",
    programs: ["Medicine", "MBA (Fuqua)", "Engineering", "Public Policy", "Computer Science"],
    tuitionUsd: { undergrad: "$63,000/yr", postgrad: "$75,000/yr (Fuqua)" },
    admissions: ["Holistic review", "SAT/ACT optional", "TOEFL 100+"],
    scholarships: ["Need-based aid", "Robertson Scholars"],
    faqs: [{ q: "Is Duke need-blind for internationals?", a: "No — Duke is need-aware for international applicants." }],
  }),
  u({ slug: "northwestern-university", name: "Northwestern University", country: "US", city: "Evanston, IL", founded: 1851, website: "https://www.northwestern.edu", worldRanking: 47,
    overview: "Top private research university with elite Medill journalism, Kellogg MBA, and strong engineering and theater programs.",
    programs: ["Journalism (Medill)", "MBA (Kellogg)", "Engineering", "Theatre", "Economics"],
    tuitionUsd: { undergrad: "$65,000/yr", postgrad: "$80,000/yr (Kellogg)" },
    admissions: ["SAT/ACT optional", "TOEFL 100+"],
    scholarships: ["Need-based aid"],
    faqs: [{ q: "Quarter or semester?", a: "Northwestern runs on the quarter system — three 10-week academic terms." }],
  }),

  // ===== UK (10) =====
  u({ slug: "oxford", name: "University of Oxford", country: "UK", city: "Oxford", founded: 1096, website: "https://www.ox.ac.uk", worldRanking: 2,
    overview: "World's oldest English-speaking university; tutorial-based education across 39 colleges with strengths across every discipline.",
    programs: ["PPE", "Computer Science", "Law", "Medicine", "MBA (Saïd)", "DPhil programmes"],
    tuitionUsd: { undergrad: "£35,000–£52,000/yr (intl)", postgrad: "£32,000–£75,000/yr" },
    admissions: ["A*AA–A*A*A (subject-specific)", "Admissions tests (LNAT, MAT, UCAT)", "Interviews", "IELTS 7.0+"],
    scholarships: ["Rhodes Scholarship", "Clarendon Scholarships", "Reach Oxford"],
    faqs: [{ q: "Can I apply to Oxford and Cambridge?", a: "No — UCAS rules prevent applying to both in the same cycle." }],
  }),
  u({ slug: "cambridge", name: "University of Cambridge", country: "UK", city: "Cambridge", founded: 1209, website: "https://www.cam.ac.uk", worldRanking: 5,
    overview: "Collegiate research university with supervisions, 31 colleges, and a global reputation across STEM, humanities, and business (Judge).",
    programs: ["Natural Sciences", "Mathematics", "Computer Science", "Engineering", "MBA (Judge)"],
    tuitionUsd: { undergrad: "£25,000–£67,000/yr (intl)", postgrad: "£32,000–£70,000/yr" },
    admissions: ["A*A*A–A*AA", "Admissions assessments", "Interviews", "IELTS 7.5+"],
    scholarships: ["Gates Cambridge", "Cambridge Trust"],
    faqs: [{ q: "What is a supervision?", a: "Small-group teaching (1–3 students) with a subject expert — Cambridge's core pedagogy." }],
  }),
  u({ slug: "imperial-college-london", name: "Imperial College London", country: "UK", city: "London", founded: 1907, website: "https://www.imperial.ac.uk", worldRanking: 8,
    overview: "STEM-focused research university with global leadership in engineering, medicine, business, and natural sciences.",
    programs: ["Computing", "Engineering", "Medicine", "Mathematics", "MBA"],
    tuitionUsd: { undergrad: "£37,000–£52,000/yr", postgrad: "£36,000–£62,000/yr" },
    admissions: ["A*A*A typical", "STEP for Math", "IELTS 6.5–7.0+"],
    scholarships: ["President's Undergraduate Scholarships", "Imperial Bursary"],
    faqs: [{ q: "Is Imperial only STEM?", a: "Mostly — it specialises in science, engineering, medicine, and business." }],
  }),
  u({ slug: "ucl", name: "University College London", country: "UK", city: "London", founded: 1826, website: "https://www.ucl.ac.uk", worldRanking: 9,
    overview: "London's leading multidisciplinary research university with strengths across humanities, social sciences, AI, and medicine.",
    programs: ["Computer Science", "Economics", "Architecture (Bartlett)", "Law", "Medicine"],
    tuitionUsd: { undergrad: "£30,000–£40,000/yr (intl)", postgrad: "£28,000–£42,000/yr" },
    admissions: ["A*AA–AAA", "IELTS 6.5–7.5"],
    scholarships: ["UCL Global Undergraduate Scholarship", "Denys Holland Scholarship"],
    faqs: [{ q: "Where is UCL located?", a: "Central London (Bloomsbury) with sites across the city." }],
  }),
  u({ slug: "lse", name: "London School of Economics and Political Science", country: "UK", city: "London", founded: 1895, website: "https://www.lse.ac.uk", worldRanking: 50,
    overview: "Globally elite social sciences university — economics, finance, politics, international relations, and law.",
    programs: ["Economics", "Finance", "International Relations", "Law", "Politics"],
    tuitionUsd: { undergrad: "£28,000/yr (intl)", postgrad: "£30,000–£42,000/yr" },
    admissions: ["A*AA typical", "IELTS 7.0+"],
    scholarships: ["LSE Undergraduate Support Scheme", "Graduate Support Scheme"],
    faqs: [{ q: "Does LSE have a campus?", a: "Yes — a compact central London campus near Holborn." }],
  }),
  u({ slug: "edinburgh", name: "University of Edinburgh", country: "UK", city: "Edinburgh, Scotland", founded: 1583, website: "https://www.ed.ac.uk", worldRanking: 27,
    overview: "Ancient Scottish university with leading programs in AI, informatics, medicine, and the humanities.",
    programs: ["AI & Informatics", "Medicine", "Business", "Veterinary Medicine", "Law"],
    tuitionUsd: { undergrad: "£26,000–£36,000/yr (intl)", postgrad: "£27,000–£37,000/yr" },
    admissions: ["AAA–A*AA", "IELTS 6.5+"],
    scholarships: ["Edinburgh Global Scholarships"],
    faqs: [{ q: "How long is a Scottish undergraduate degree?", a: "Typically four years vs. three in England." }],
  }),
  u({ slug: "kings-college-london", name: "King's College London", country: "UK", city: "London", founded: 1829, website: "https://www.kcl.ac.uk", worldRanking: 40,
    overview: "Russell Group university with prestigious programs in law, medicine, dentistry, and war studies.",
    programs: ["Law", "Medicine", "Dentistry", "War Studies", "Computer Science"],
    tuitionUsd: { undergrad: "£28,000–£40,000/yr", postgrad: "£28,000–£42,000/yr" },
    admissions: ["AAA typical", "IELTS 6.5–7.0+"],
    scholarships: ["King's International Scholarships"],
    faqs: [{ q: "Is King's part of the University of London?", a: "Yes — King's is a founding constituent of the federal University of London." }],
  }),
  u({ slug: "manchester", name: "University of Manchester", country: "UK", city: "Manchester", founded: 1824, website: "https://www.manchester.ac.uk", worldRanking: 35,
    overview: "Russell Group powerhouse with strong programs across engineering, materials, business (Alliance MBS), and the sciences.",
    programs: ["Engineering", "Computer Science", "Business (AMBS)", "Materials Science", "Medicine"],
    tuitionUsd: { undergrad: "£25,000–£35,000/yr", postgrad: "£26,000–£40,000/yr" },
    admissions: ["AAB–A*AA", "IELTS 6.0–7.0+"],
    scholarships: ["Manchester International Excellence Awards"],
    faqs: [{ q: "Is Manchester student-friendly?", a: "Very — one of the largest student populations in the UK with vibrant culture." }],
  }),
  u({ slug: "warwick", name: "University of Warwick", country: "UK", city: "Coventry", founded: 1965, website: "https://warwick.ac.uk", worldRanking: 69,
    overview: "Young Russell Group university with elite programs in mathematics, economics, business (WBS), and computer science.",
    programs: ["Mathematics", "Economics", "MBA (WBS)", "Computer Science", "Engineering"],
    tuitionUsd: { undergrad: "£24,000–£32,000/yr", postgrad: "£26,000–£55,000/yr" },
    admissions: ["A*AA typical", "IELTS 6.5+"],
    scholarships: ["Warwick Undergraduate Global Excellence Scholarships"],
    faqs: [{ q: "How is WBS ranked?", a: "Warwick Business School is consistently top-5 in the UK." }],
  }),
  u({ slug: "bristol", name: "University of Bristol", country: "UK", city: "Bristol", founded: 1876, website: "https://www.bristol.ac.uk", worldRanking: 54,
    overview: "Russell Group university with strong engineering, social sciences, and a culture of research-led teaching.",
    programs: ["Engineering", "Computer Science", "Medicine", "Veterinary Science", "Law"],
    tuitionUsd: { undergrad: "£26,000–£35,000/yr", postgrad: "£24,000–£40,000/yr" },
    admissions: ["AAA typical", "IELTS 6.5+"],
    scholarships: ["Think Big Scholarships"],
    faqs: [{ q: "Is Bristol good for engineering?", a: "Yes — particularly aerospace and electronics, with strong industry links." }],
  }),

  // ===== Canada (10) =====
  u({ slug: "toronto", name: "University of Toronto", country: "CA", city: "Toronto, ON", founded: 1827, website: "https://www.utoronto.ca", worldRanking: 21,
    overview: "Canada's top research university with global strengths in AI (birthplace of deep learning), medicine, business (Rotman), and engineering.",
    programs: ["Computer Science", "AI", "Engineering", "MBA (Rotman)", "Medicine"],
    tuitionUsd: { undergrad: "C$60,000/yr (intl)", postgrad: "C$30,000–C$80,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+ / TOEFL 100+"],
    scholarships: ["Lester B. Pearson", "U of T Scholars"],
    faqs: [{ q: "How competitive is U of T CS?", a: "Highly — direct-entry CS admit rate is in the low single digits." }],
  }),
  u({ slug: "ubc", name: "University of British Columbia", country: "CA", city: "Vancouver, BC", founded: 1908, website: "https://www.ubc.ca", worldRanking: 38,
    overview: "Top Canadian research university with leading programs in CS, forestry, oceanography, and Sauder School of Business.",
    programs: ["Computer Science", "Engineering", "Business (Sauder)", "Forestry", "Oceanography"],
    tuitionUsd: { undergrad: "C$45,000/yr (intl)", postgrad: "C$10,000–C$60,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+ / TOEFL 90+"],
    scholarships: ["Karen McKellin International Leader of Tomorrow Award"],
    faqs: [{ q: "Is Vancouver expensive?", a: "Yes — among Canada's most expensive cities for rent and groceries." }],
  }),
  u({ slug: "mcgill", name: "McGill University", country: "CA", city: "Montréal, QC", founded: 1821, website: "https://www.mcgill.ca", worldRanking: 27,
    overview: "Bilingual research university with top medicine, law, engineering, and management (Desautels) programs.",
    programs: ["Medicine", "Law", "Engineering", "Management (Desautels)", "Neuroscience"],
    tuitionUsd: { undergrad: "C$30,000–C$60,000/yr (intl)", postgrad: "C$20,000–C$50,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+ / TOEFL 90+"],
    scholarships: ["McCall MacBain Scholarships", "Entrance Scholarships"],
    faqs: [{ q: "Do I need to speak French?", a: "Most undergraduate teaching is in English; French helps for daily life in Montréal." }],
  }),
  u({ slug: "waterloo", name: "University of Waterloo", country: "CA", city: "Waterloo, ON", founded: 1957, website: "https://uwaterloo.ca", worldRanking: 115,
    overview: "Canada's tech & engineering powerhouse known for the world's largest co-op program and a top CS school.",
    programs: ["Computer Science", "Software Engineering", "Engineering", "Mathematics", "Co-op programs"],
    tuitionUsd: { undergrad: "C$45,000–C$70,000/yr (intl)", postgrad: "C$10,000–C$30,000/yr" },
    admissions: ["AIF + strong grades", "Euclid/CSMC for CS/Math", "IELTS 6.5+"],
    scholarships: ["President's Scholarship of Distinction", "International Master's Award"],
    faqs: [{ q: "What is the co-op program?", a: "Alternating 4-month study and paid work terms with companies worldwide." }],
  }),
  u({ slug: "mcmaster", name: "McMaster University", country: "CA", city: "Hamilton, ON", founded: 1887, website: "https://www.mcmaster.ca", worldRanking: 144,
    overview: "Research-intensive university known for health sciences, engineering, and pioneering problem-based learning.",
    programs: ["Health Sciences", "Engineering", "Computer Science", "Business (DeGroote)", "Nursing"],
    tuitionUsd: { undergrad: "C$45,000/yr (intl)", postgrad: "C$10,000–C$45,000/yr" },
    admissions: ["Strong grades + supplementary forms", "IELTS 6.5+"],
    scholarships: ["McMaster International Excellence Award"],
    faqs: [{ q: "Is McMaster good for medicine?", a: "Yes — its MD program pioneered problem-based learning globally." }],
  }),
  u({ slug: "alberta", name: "University of Alberta", country: "CA", city: "Edmonton, AB", founded: 1908, website: "https://www.ualberta.ca", worldRanking: 96,
    overview: "Top-5 Canadian research university with strengths in AI (Amii), engineering, business, and energy research.",
    programs: ["Computer Science (AI)", "Engineering", "Business", "Nursing", "Petroleum Engineering"],
    tuitionUsd: { undergrad: "C$30,000–C$45,000/yr (intl)", postgrad: "C$10,000–C$30,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["International Student Scholarships", "Gold Standard Scholarships"],
    faqs: [{ q: "Why is U of A strong in AI?", a: "Home to Amii and pioneers of reinforcement learning (Richard Sutton)." }],
  }),
  u({ slug: "queens-ca", name: "Queen's University", country: "CA", city: "Kingston, ON", founded: 1841, website: "https://www.queensu.ca", worldRanking: 240,
    overview: "Selective research university with a strong undergraduate experience, top commerce program (Smith), and engineering.",
    programs: ["Commerce (Smith)", "Engineering", "Computing", "Nursing", "Law"],
    tuitionUsd: { undergrad: "C$50,000–C$60,000/yr (intl)", postgrad: "C$10,000–C$80,000/yr" },
    admissions: ["Strong academics + PSE forms", "IELTS 6.5+"],
    scholarships: ["International Major Entrance Scholarships"],
    faqs: [{ q: "Is Queen's residential?", a: "Yes — strong residence culture and small-town college vibe." }],
  }),
  u({ slug: "western", name: "Western University", country: "CA", city: "London, ON", founded: 1878, website: "https://www.uwo.ca", worldRanking: 114,
    overview: "Comprehensive research university with the Ivey Business School, strong medicine, engineering, and a vibrant residential campus.",
    programs: ["MBA (Ivey)", "Medicine", "Engineering", "Computer Science", "Health Sciences"],
    tuitionUsd: { undergrad: "C$45,000–C$65,000/yr (intl)", postgrad: "C$15,000–C$110,000/yr (Ivey MBA)" },
    admissions: ["Strong grades + supplementary", "IELTS 6.5+"],
    scholarships: ["President's Entrance Scholarships"],
    faqs: [{ q: "Is Ivey case-based?", a: "Yes — Ivey pioneered case-method teaching outside Harvard." }],
  }),
  u({ slug: "calgary", name: "University of Calgary", country: "CA", city: "Calgary, AB", founded: 1966, website: "https://www.ucalgary.ca", worldRanking: 182,
    overview: "Research-intensive university with strengths in engineering, energy, veterinary medicine, and business (Haskayne).",
    programs: ["Engineering", "Business (Haskayne)", "Veterinary Medicine", "Geoscience", "Computer Science"],
    tuitionUsd: { undergrad: "C$25,000–C$40,000/yr (intl)", postgrad: "C$10,000–C$30,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["International Entrance Scholarships"],
    faqs: [{ q: "Is Calgary good for energy careers?", a: "Yes — it's the centre of Canada's energy industry." }],
  }),
  u({ slug: "ottawa", name: "University of Ottawa", country: "CA", city: "Ottawa, ON", founded: 1848, website: "https://www.uottawa.ca", worldRanking: 203,
    overview: "Bilingual G13 university in Canada's capital with leading law, medicine, public policy, and engineering programs.",
    programs: ["Law (Common & Civil)", "Medicine", "Public Policy", "Engineering", "Computer Science"],
    tuitionUsd: { undergrad: "C$30,000–C$55,000/yr (intl)", postgrad: "C$10,000–C$30,000/yr" },
    admissions: ["Strong grades", "IELTS 6.5+ / TOEFL 86+"],
    scholarships: ["International Scholarships", "Differential Tuition Fee Exemption (French)"],
    faqs: [{ q: "Is uOttawa bilingual?", a: "Yes — programs are offered in English and French; many bilingual streams." }],
  }),

  // ===== Australia (10) =====
  u({ slug: "unimelb", name: "University of Melbourne", country: "AU", city: "Melbourne, VIC", founded: 1853, website: "https://www.unimelb.edu.au", worldRanking: 13,
    overview: "Australia's leading research university with the Melbourne Model: broad undergraduate degrees followed by specialised graduate study.",
    programs: ["Medicine (MD)", "Law (JD)", "MBA (MBS)", "Engineering", "Computer Science"],
    tuitionUsd: { undergrad: "A$45,000–A$55,000/yr (intl)", postgrad: "A$45,000–A$110,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5–7.0+"],
    scholarships: ["Melbourne International Undergraduate Scholarship", "Graduate Research Scholarships"],
    faqs: [{ q: "What is the Melbourne Model?", a: "A broad 3-year bachelor's followed by a professional master's, similar to North American structures." }],
  }),
  u({ slug: "sydney", name: "University of Sydney", country: "AU", city: "Sydney, NSW", founded: 1850, website: "https://www.sydney.edu.au", worldRanking: 18,
    overview: "Australia's first university with comprehensive strengths in medicine, business, engineering, and the humanities.",
    programs: ["Medicine", "Business (USBS)", "Engineering", "Computer Science", "Architecture"],
    tuitionUsd: { undergrad: "A$50,000–A$60,000/yr", postgrad: "A$48,000–A$110,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5–7.5"],
    scholarships: ["Sydney Scholars Awards", "Vice-Chancellor's International Scholarships"],
    faqs: [{ q: "Is Sydney good for international students?", a: "Yes — large international cohort with strong support services." }],
  }),
  u({ slug: "unsw", name: "University of New South Wales", country: "AU", city: "Sydney, NSW", founded: 1949, website: "https://www.unsw.edu.au", worldRanking: 19,
    overview: "Top Go8 university with leading programs in engineering, business (AGSM), computer science, and design.",
    programs: ["Engineering", "Computer Science", "Business (AGSM)", "Built Environment", "Medicine"],
    tuitionUsd: { undergrad: "A$50,000–A$60,000/yr", postgrad: "A$45,000–A$95,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["UNSW International Scientia Scholarships"],
    faqs: [{ q: "Does UNSW run trimesters?", a: "Yes — three 10-week terms per year." }],
  }),
  u({ slug: "anu", name: "Australian National University", country: "AU", city: "Canberra, ACT", founded: 1946, website: "https://www.anu.edu.au", worldRanking: 30,
    overview: "Australia's national research university with global strengths in policy, international relations, physics, and astronomy.",
    programs: ["International Relations", "Public Policy", "Physics", "Computer Science", "Law"],
    tuitionUsd: { undergrad: "A$45,000–A$55,000/yr", postgrad: "A$45,000–A$60,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["ANU Chancellor's International Scholarship"],
    faqs: [{ q: "Is Canberra a good student city?", a: "Compact and safe, with policy/research opportunities in the capital." }],
  }),
  u({ slug: "monash", name: "Monash University", country: "AU", city: "Melbourne, VIC", founded: 1958, website: "https://www.monash.edu", worldRanking: 37,
    overview: "Large Go8 university with global campuses (Malaysia, Indonesia) and top programs in pharmacy, business, and engineering.",
    programs: ["Pharmacy", "Engineering", "Business", "Medicine", "Computer Science"],
    tuitionUsd: { undergrad: "A$45,000–A$55,000/yr", postgrad: "A$45,000–A$95,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["Monash International Merit Scholarship"],
    faqs: [{ q: "How big is Monash?", a: "Over 80,000 students — one of Australia's largest universities." }],
  }),
  u({ slug: "uq", name: "University of Queensland", country: "AU", city: "Brisbane, QLD", founded: 1909, website: "https://www.uq.edu.au", worldRanking: 40,
    overview: "Go8 research university with strong life sciences, engineering, and business (UQ Business School).",
    programs: ["Medicine", "Engineering", "Business", "Biotechnology", "Veterinary Science"],
    tuitionUsd: { undergrad: "A$45,000–A$55,000/yr", postgrad: "A$45,000–A$95,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["UQ Vice-Chancellor's Scholarships"],
    faqs: [{ q: "Is Brisbane warm year-round?", a: "Yes — subtropical climate with mild winters." }],
  }),
  u({ slug: "uwa", name: "University of Western Australia", country: "AU", city: "Perth, WA", founded: 1911, website: "https://www.uwa.edu.au", worldRanking: 77,
    overview: "Go8 university with strengths in mining engineering, agriculture, marine biology, and a leading business school.",
    programs: ["Mining Engineering", "Agriculture", "Medicine", "Business", "Marine Biology"],
    tuitionUsd: { undergrad: "A$40,000–A$50,000/yr", postgrad: "A$38,000–A$80,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["UWA Global Excellence Scholarship"],
    faqs: [{ q: "Is Perth isolated?", a: "Geographically yes, but it offers a relaxed lifestyle and strong industry links to mining and energy." }],
  }),
  u({ slug: "adelaide", name: "University of Adelaide", country: "AU", city: "Adelaide, SA", founded: 1874, website: "https://www.adelaide.edu.au", worldRanking: 82,
    overview: "Go8 research university known for wine science, defence, engineering, and health sciences.",
    programs: ["Wine Science", "Engineering", "Medicine", "Computer Science", "Defence"],
    tuitionUsd: { undergrad: "A$40,000–A$50,000/yr", postgrad: "A$38,000–A$70,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["Adelaide Global Citizens Scholarship"],
    faqs: [{ q: "Is Adelaide affordable?", a: "Yes — among the more affordable Australian capitals for students." }],
  }),
  u({ slug: "uts", name: "University of Technology Sydney", country: "AU", city: "Sydney, NSW", founded: 1988, website: "https://www.uts.edu.au", worldRanking: 88,
    overview: "Industry-focused research university with leading programs in IT, engineering, design, and business.",
    programs: ["Information Technology", "Engineering", "Design", "Business", "Nursing"],
    tuitionUsd: { undergrad: "A$40,000–A$50,000/yr", postgrad: "A$40,000–A$60,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["UTS International Undergraduate Scholarships"],
    faqs: [{ q: "Is UTS practical?", a: "Yes — strong industry placements and a practice-oriented curriculum." }],
  }),
  u({ slug: "macquarie", name: "Macquarie University", country: "AU", city: "Sydney, NSW", founded: 1964, website: "https://www.mq.edu.au", worldRanking: 178,
    overview: "Research-intensive university with strong programs in linguistics, actuarial studies, business, and cognitive science.",
    programs: ["Actuarial Studies", "Business", "Linguistics", "Cognitive Science", "Computing"],
    tuitionUsd: { undergrad: "A$38,000–A$48,000/yr", postgrad: "A$40,000–A$55,000/yr" },
    admissions: ["Strong academics", "IELTS 6.5+"],
    scholarships: ["Vice-Chancellor's International Scholarship"],
    faqs: [{ q: "What is Macquarie known for?", a: "Pioneering actuarial studies in Australia and a leading linguistics program." }],
  }),
];

export function getUniversityKB(slug: string): UniversityKB | undefined {
  return UNIVERSITIES_KB.find((u) => u.slug === slug);
}

export function getUniversitiesByCountry(country: CountryCode): UniversityKB[] {
  return UNIVERSITIES_KB.filter((u) => u.country === country);
}

export const KB_COUNTRIES: { code: CountryCode; name: string; flag: string }[] = [
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "UK", name: "United Kingdom", flag: "🇬🇧" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
];
